import {parseCSV} from './csv.js';
import {cents} from './model.js';
import {nonPurchaseReason} from './rules.js';
const clean=s=>String(s??'').trim();
const missing=s=>!clean(s)||/^(n\/a|not available)$/i.test(clean(s));
const money=s=>missing(s)?null:cents(s);
function date(s){if(missing(s))return null;let value=clean(s);const m=value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)value=m[3]+'-'+m[1].padStart(2,'0')+'-'+m[2].padStart(2,'0');if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value)throw Error('Invalid Amazon date.');return value;}
export function importAmazon(text){
 const rows=parseCSV(text,{excelText:true}),headers=rows.shift()||[];
 for(const h of ['Order Date','Order ID','Currency','Order Net Total','Order Status','ASIN','Title','Item Quantity','Item Net Total','Payment Reference ID','Payment Date','Payment Amount','Payment Instrument Type','Payment Identifier'])if(!headers.includes(h))throw Error('Missing '+h+'. Upload the Amazon order/item CSV report.');
 if(new Set(headers).size!==headers.length)throw Error('Repeated Amazon column names.');if(rows.length>100000)throw Error('Import up to 100,000 Amazon report rows.');
 return rows.map((row,index)=>{if(row.length!==headers.length)throw Error('Amazon row '+(index+2)+' has an unexpected number of columns.');const r=Object.fromEntries(headers.map((h,i)=>[h,row[i]]));if(!/^[A-Za-z0-9-]{5,80}$/.test(r['Order ID']))throw Error('Invalid Amazon order ID on row '+(index+2));const quantity=Number(r['Item Quantity']);if(!Number.isSafeInteger(quantity)||quantity<0)throw Error('Invalid Amazon quantity on row '+(index+2));return {orderId:r['Order ID'],date:date(r['Order Date']),currency:clean(r.Currency),net:money(r['Order Net Total']),status:clean(r['Order Status']),asin:clean(r.ASIN),title:clean(r.Title),productCategory:clean(r['Amazon-Internal Product Category']),lineId:clean(r['PO Line Item Id']),quantity,itemNet:money(r['Item Net Total']),itemSubtotal:money(r['Item Subtotal']),itemTax:money(r['Item Tax']),itemShipping:money(r['Item Shipping & Handling']),itemPromotion:money(r['Item Promotion']),paymentRef:clean(r['Payment Reference ID']),paymentDate:date(r['Payment Date']),paymentAmount:money(r['Payment Amount']),instrument:clean(r['Payment Instrument Type']),identifier:clean(r['Payment Identifier'])};});
}
const itemSignature=r=>JSON.stringify([r.asin,r.title,r.lineId,r.quantity,r.itemNet,r.itemSubtotal,r.itemTax,r.itemShipping,r.itemPromotion]);
export function groupAmazon(records){
 const rawUnique=new Map(records.map(r=>[JSON.stringify(r),r])),groups=new Map(),shared=new Map();
 for(const r of rawUnique.values()){if(!groups.has(r.orderId))groups.set(r.orderId,[]);groups.get(r.orderId).push(r);if(r.paymentRef&&!missing(r.paymentRef)){if(!shared.has(r.paymentRef))shared.set(r.paymentRef,new Set());shared.get(r.paymentRef).add(r.orderId);}}
 return [...groups].map(([id,rows])=>{const issues=[],nets=new Set(rows.map(r=>r.net)),dates=new Set(rows.map(r=>r.date)),currencies=new Set(rows.map(r=>r.currency)),statuses=new Set(rows.map(r=>r.status));if(nets.size!==1||nets.has(null))issues.push('Order total is missing or conflicting.');if(dates.size!==1||dates.has(null))issues.push('Order date is missing or conflicting.');if(currencies.size!==1||!currencies.has('USD'))issues.push('Only USD orders can match the current Wave export.');if(statuses.size!==1)issues.push('Conflicting order statuses.');const net=[...nets][0],items=new Map(),payments=new Map();
 for(const r of rows){const key=itemSignature(r);if(!items.has(key))items.set(key,{key:id+':'+key,asin:r.asin,title:r.title,productCategory:r.productCategory,quantity:r.quantity,net:r.itemNet});if(!r.title||r.itemNet===null)issues.push('An item has a missing title or amount.');if(r.paymentRef&&!missing(r.paymentRef)){const p={key:r.paymentRef,ref:r.paymentRef,date:r.paymentDate,amount:r.paymentAmount,instrument:r.instrument,identifier:r.identifier,shared:shared.get(r.paymentRef)?.size>1,rewards:/reward|gift|promotional/i.test(r.instrument)};if(payments.has(p.key)&&JSON.stringify(payments.get(p.key))!==JSON.stringify(p))issues.push('A payment reference has conflicting details.');else payments.set(p.key,p);}}
 const itemList=[...items.values()],paymentList=[...payments.values()],itemTotal=itemList.every(i=>i.net!==null)?itemList.reduce((s,i)=>s+i.net,0):null;
 if(itemTotal!==net)issues.push('Item totals do not reconcile to the order total; duplicate or separate item lines may be indistinguishable.');
 if(paymentList.some(p=>p.amount===null))issues.push('A payment amount is missing; reconcile before preparing a purchase.');const validPayments=paymentList.filter(p=>p.amount!==null);if(validPayments.reduce((s,p)=>s+p.amount,0)!==net)issues.push('Payment totals do not reconcile to the order total.');if(paymentList.some(p=>p.shared))issues.push('A payment reference spans multiple orders; allocation needs review.');
 const cancelled=[...statuses].some(s=>/cancel/i.test(s)),refund=net<0||itemList.some(i=>i.net<0)||paymentList.some(p=>p.amount<0);if(cancelled)issues.push('Cancelled order; no purchase action.');if(refund)issues.push('Refund or negative amount; reconcile separately.');
 return {id,date:[...dates][0],net,currency:[...currencies][0],status:[...statuses].join(', '),items:itemList,payments:paymentList,itemTotal,issues:[...new Set(issues)],cancelled,refund,sourceRows:rows.length};
 }).sort((a,b)=>(b.date||'').localeCompare(a.date||'')||a.id.localeCompare(b.id));
}
const categoryFor=(names,prefix)=>{const found=names.filter(n=>n.startsWith(prefix+' —')||n===prefix);return found.length===1?found[0]:'';};
export function suggestAmazonItem(item,categories=[]){
 const text=(item.title+' '+item.productCategory).toLowerCase();let purpose='Needs judgment',prefix='',reason='Confirm the item’s actual use. Product type alone does not establish business use.';
 const signals=[
 ['Likely personal','Personal Pets',/\b(cat litter|cat food|dog food|dog treats|pet food|pet products|dog toy|cat toy|aquarium)\b/,'Pet supplies suggest personal use.'],
 ['Likely personal','Personal Gaming',/\b(video games?|playstation|xbox|nintendo switch|digital video games)\b/,'Gaming products suggest personal use; hardware can have another purpose.'],
 ['Likely personal','Personal Miscellaneous',/\b(sex toy|vibrator|lingerie|jewelry|perfume|cologne|mascara|lipstick)\b/,'Personal-use product wording.'],
 ['Likely personal','Personal Groceries',/\b(grocery|breakfast cereal|snack bars|protein bars|coffee beans)\b/,'Food purchase; confirm personal groceries versus jobsite/client use.'],
 ['Likely business','Safety Gear & PPE',/\b(hard hat|safety glasses|safety goggles|respirator|hearing protection|high visibility|hi vis|cut resistant gloves|welding gloves|steel toe)\b/,'Work safety/PPE wording; confirm it was used for work.'],
 ['Likely business','Workplace Safety Health',/\b(first aid kit|first aid cabinet)\b/,'First-aid equipment; confirm workplace use.'],
 ['Likely business','Equipment & Tools',/\b(impact driver|hammer drill|rotary hammer|circular saw|reciprocating saw|oscillating tool|torque wrench|drill bits|saw blade|angle grinder|nail gun|caulking gun|laser level|socket set|tool belt|impact wrench|combination wrench|ratchet wrench|allen wrench|hex key|bolt cutter|pipe wrench|wire stripper|crimping tool|masonry bit|countersink|tap and die|hole saw|sanding disc|grinding wheel|cut off wheel|cutoff wheel|brad nailer|framing nailer)\b/,'Trade tool wording; confirm business use and the intended category.'],
 ['Likely business','Parts & Materials',/\b(pvc pipe|pipe fitting|pex tubing|electrical conduit|wire connector|drywall screw|deck screw|concrete anchor|joist hanger|plumbing fitting|construction adhesive)\b/,'Construction material wording; confirm it was for business rather than home use.'],
 ['Needs judgment','Vehicle – Repairs & Maintenance',/\b(automotive parts|brake pad|oil filter|spark plug|wiper blade|car wash)\b/,'Identify the vehicle and confirm business versus personal use.'],
 ['Needs judgment','Computer Hardware',/\b(personal computer|pc accessory|computer|laptop|monitor|keyboard|ssd|graphics card|motherboard|usb hub)\b/,'Computer equipment may be for work, streaming or personal use.'],
 ['Needs judgment','Streaming Supplies',/\b(microphone|webcam|streaming|capture card)\b/,'Confirm work/streaming use versus personal use.'],
 ['Needs judgment','Personal Miscellaneous',/\b(apparel|shoes|kitchen|home|health and beauty|beauty|toy|sports)\b/,'Mixed-use product group. Confirm personal, household, gift or business purpose.'],
 ['Needs judgment','Parts & Materials',/\b(home improvement|lawn & patio|industrial|scientific supplies)\b/,'Potential building/work supplies; identify the actual project or home use.'],
 ['Needs judgment','Personal Subscriptions',/\b(prime)\b/,'Membership usage may be business or personal.'],
 ['Needs judgment','Office Supplies',/\b(printer ink|toner cartridge|copy paper|office product|shipping label|label printer)\b/,'Office product; confirm the purchase purpose.']
 ];
 const hits=signals.filter(([, ,pattern])=>pattern.test(text));const likely=hits.filter(h=>h[0]!=='Needs judgment');if(new Set(likely.map(h=>h[0])).size>1)return {purpose,category:'',reason:'Conflicting personal and business product signals. Review the full title.'};const chosen=likely[0]||hits[0];if(chosen)[purpose,prefix,,reason]=chosen;let category=prefix==='Vehicle – Repairs & Maintenance'?categories.find(n=>n===prefix)||'':categoryFor(categories,prefix);if(prefix&&!category)reason+=' Collect your Chart of Accounts or choose an existing category manually.';return {purpose,category,reason};
}
export function amazonInstrumentKey(p){return p.instrument+' · '+(p.identifier||'No card identifier');}
const day=s=>Date.parse(s+'T00:00:00Z')/86400000;
export function matchAmazonPayments(orders,transactions=[],accountMap={}){
 const all=[];for(const order of orders)for(const p of order.payments){const account=accountMap[amazonInstrumentKey(p)],digits=p.identifier.match(/(?:^|\D)(\d{4})(?!\d)/g)?.at(-1)?.match(/\d{4}/)?.[0];const automatic=digits?[...new Set(transactions.filter(t=>t.primary?.type==='Credit Card').map(t=>t.primary.account).filter(a=>a&&new RegExp('(?:^|\\D)'+digits+'(?:\\D|$)').test(a)))]:[];const mapped=account|| (automatic.length===1?automatic[0]:'');const eligible=!order.cancelled&&!order.refund&&order.currency==='USD'&&!p.rewards&&!p.shared&&p.amount>0&&!!p.date&&!!mapped&&!missing(p.instrument);const candidates=eligible?transactions.filter(t=>t.primary&&!t.existingTransfer&&t.direction==='out'&&t.amount===p.amount&&t.primary.account===mapped&&Math.abs(day(t.date)-day(p.date))<=5&&/\bamazon\b|\bamzn\b/i.test(t.description)&&!nonPurchaseReason(t)):[];all.push({orderId:order.id,payment:p,account:mapped,candidates:candidates.map(t=>t.id),state:p.rewards?'Rewards / gift credit':p.shared?'Shared payment':!eligible?'Needs payment details':candidates.length===0?'No Wave match':candidates.length>1?'Ambiguous match':'Candidate',reason:order.cancelled?'Cancelled order; no purchase match.':order.refund?'Refund or negative amount; reconcile separately.':p.rewards?'Rewards or gift credit has no separate bank charge.':p.shared?'Shared payment reference needs allocation across orders.':!mapped?'Map this payment instrument to its Wave account.':!eligible?'Payment details are incomplete or ineligible.':candidates.length===0?'No exact outgoing Amazon charge found in this account within five days.':candidates.length>1?'Several exact candidates; choose and reconcile individually.':'Equal cents, matching account and Amazon wording, within five days of payment. Confirm the link.'});}
 const usage=new Map();for(const match of all)for(const id of match.candidates)usage.set(id,(usage.get(id)||0)+1);return all.map(m=>({...m,state:m.state==='Candidate'&&usage.get(m.candidates[0])!==1?'Ambiguous match':m.state}));
}
export function amazonActions(orders,matches,decisions,categories,from='2025-01-01'){
 const result=[];for(const order of orders){if(order.date<from||order.issues.length)continue;const approved=order.items.map(i=>decisions[i.key]);if(!approved.length||approved.some(d=>!d||!['Business','Personal'].includes(d.purpose)||!categories.includes(d.category)||(d.purpose==='Personal')!==(/^Personal\b|^Owner\b/i.test(d.category))))continue;const unique=new Set(approved.map(d=>d.category));if(unique.size!==1||new Set(approved.map(d=>d.purpose)).size!==1)continue;for(const m of matches.filter(m=>m.orderId===order.id&&m.state==='Candidate'))result.push({id:m.candidates[0],category:approved[0].category,orderId:order.id,paymentRef:m.payment.ref,purpose:approved[0].purpose,reason:'All order items explicitly approved with the same category. Exact payment candidate still needs confirmation and live validation.'});}return result;
}
