import {importAmazon,groupAmazon,suggestAmazonItem,matchAmazonPayments,amazonActions,amazonInstrumentKey} from './amazon.js';
import {loadLocalFeature,saveLocalFeature} from './session.js';
import {sourceHash} from './rule-pack.js';
import {buildPlan,recordSnapshot} from './plan.js';
import {activity,paintActivity} from './activity.js';
const cash=n=>n===null?'Missing':'$'+(n/100).toFixed(2);
export function installAmazonReview({getState,onChange=()=>{},onRunning=()=>{},inspect}){
 const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},section=make('section'),fold=make('details');fold.id='amazonReview';fold.className='step';const summary=make('summary','Amazon purchase solver');summary.setAttribute('role','heading');summary.setAttribute('aria-level','2');const body=make('div');body.className='step-body';fold.append(summary,body);section.append(fold);document.getElementById('fold-history').closest('section').after(section);
 const upload=make('input');upload.type='file';upload.accept='.csv';upload.multiple=true;upload.id='amazonFiles';const uploadLabel=make('label','Amazon order/item CSV reports');uploadLabel.htmlFor=upload.id;uploadLabel.append(upload);const status=make('p');status.setAttribute('role','status');const totals=make('p'),search=make('input');search.placeholder='Find an order, product or ASIN';search.setAttribute('aria-label','Find Amazon purchase');const view=make('select');view.setAttribute('aria-label','Amazon purchase filter');for(const [value,label] of [['','All purchases'],['Likely business','Likely business items'],['Likely personal','Likely personal items'],['Needs judgment','Needs judgment'],['issues','Payment / item reconciliation issues'],['ready','Approved matched purchases']])view.append(Object.assign(make('option',label),{value}));const historical=make('input');historical.type='checkbox';const historicalLabel=make('label',' Show completed years for reference');historicalLabel.className='plan-choice';historicalLabel.prepend(historical);
 const mappings=make('details');mappings.className='custom-rule';mappings.append(make('summary','Match Amazon payment instruments to Wave accounts'));const mappingBody=make('div');mappings.append(mappingBody);const bar=make('div');bar.className='bar';const select=make('button','Select visible suggestions'),clear=make('button','Clear item selection'),approve=make('button','Approve checked items'),count=make('span','0 checked');clear.className='secondary';bar.append(select,clear,approve,count);const results=make('div'),downloads=make('div');downloads.className='bar';const exportReview=make('button','Download Amazon review'),exportPlan=make('button','Download approved Amazon plan');exportReview.className=exportPlan.className='secondary';downloads.append(exportReview,exportPlan);
 body.append(make('p','Upload Amazon item reports, review the suggested purpose and exact category, then approve checked items. Confirm each unique payment match before preparing a Wave change. Shared payments, refunds, cancelled orders and mixed categories need individual review or a split in Wave. No purchase is changed by importing or approving here.'),uploadLabel,status,totals,mappings,search,view,historicalLabel,bar,results,downloads);
 let state={version:1,files:[],decisions:{},accountMap:{},links:{}},seen=null,loading=false,busy=false,cache=null,limit=25,visible=[],selection=new Set(),drafts={},openOrders=new Set();
 const rows=()=>state.files.flatMap(f=>f.records);const model=()=>{const s=getState(),map=JSON.stringify(state.accountMap);if(!cache||cache.files!==state.files||cache.dataset!==s.dataset||cache.map!==map||cache.names!==s.categories.join('\n')){const orders=groupAmazon(rows());cache={files:state.files,dataset:s.dataset,map,names:s.categories.join('\n'),orders,matches:matchAmazonPayments(orders,s.dataset?.transactions||[],state.accountMap),signals:new Map(orders.flatMap(o=>o.items.map(i=>[i.key,suggestAmazonItem(i,s.categories)])))};}return cache;};
 function approvedActions(){const s=getState(),m=model(),byId=new Map((s.dataset?.transactions||[]).map(t=>[t.id,t]));return amazonActions(m.orders,m.matches,state.decisions,s.categories,s.from).filter(a=>{const link=state.links[a.orderId+':'+a.paymentRef],t=byId.get(a.id);return s.report?.records?.find(r=>r.id===a.id)?.reviewed!=='Reviewed'&&link?.id===a.id&&t&&JSON.stringify(link.snapshot)===JSON.stringify(recordSnapshot(t));});}
 function proposalFor(t,a){return {...t,kind:'Merchant rule',proposed:a.category,reason:'Approved Amazon order '+a.orderId+': '+a.purpose+'. All items approved; payment match confirmed locally. Live fields must still be checked.',amazonOrder:a.orderId,partner:null};}
 async function persist(next=state){const business=seen;await saveLocalFeature('amazon:'+business,{...next,business});if(getState().business!==business)throw Error('Business changed; the saved Amazon work remains with its original business.');state=next;}
 async function restore(){const s=getState();if(seen===s.business&&!loading)return;if(loading)return;seen=s.business;selection.clear();drafts={};cache=null;state={version:1,files:[],decisions:{},accountMap:{},links:{}};if(!seen){render();return;}const business=seen;loading=true;render();try{const saved=await loadLocalFeature('amazon:'+business);if(getState().business===business&&saved?.version===1&&saved.business===business&&Array.isArray(saved.files))state={...state,...saved};}catch(e){status.textContent='Could not restore Amazon report: '+e.message;}finally{loading=false;if(getState().business!==business){seen=null;return restore();}render();onChange();}}
 const chosenFor=(item,signal)=>drafts[item.key]||state.decisions[item.key]||{purpose:signal.purpose==='Likely business'?'Business':signal.purpose==='Likely personal'?'Personal':'Needs judgment',category:signal.category};
 function render(){const s=getState();if(seen!==s.business){void restore();return;}const locked=busy||loading||s.busy||!s.business;upload.disabled=locked;select.disabled=clear.disabled=approve.disabled=locked;exportReview.disabled=!state.files.length;exportPlan.disabled=locked||!approvedActions().length;results.replaceChildren();mappingBody.replaceChildren();if(loading){status.textContent='Loading saved Amazon reports…';return;}const m=model();totals.textContent=state.files.length?state.files.map(f=>f.name).join(', ')+' saved locally. '+rows().length+' report rows → '+m.orders.length+' orders / '+m.orders.reduce((n,o)=>n+o.items.length,0)+' item lines. '+m.orders.filter(o=>!o.issues.length).length+' orders reconcile; '+approvedActions().length+' approved payment links ready for live validation.':'No Amazon reports loaded. Your accounting.csv and merchant rules stay in place.';
 const accounts=[...new Set((s.dataset?.transactions||[]).map(t=>t.primary?.account).filter(Boolean))].sort(),instruments=[...new Map(m.orders.flatMap(o=>o.payments.filter(p=>!p.rewards&&!/^(N\/A)?$/i.test(p.instrument)).map(p=>[amazonInstrumentKey(p),p]))).values()];for(const p of instruments){const key=amazonInstrumentKey(p),label=make('label',key),input=make('select');input.setAttribute('aria-label','Wave account for '+key);input.append(Object.assign(make('option','Auto-match unique card ending, otherwise choose'),{value:''}));for(const account of accounts)input.append(Object.assign(make('option',account),{value:account}));input.value=state.accountMap[key]||'';input.disabled=locked;input.onchange=async()=>{try{await persist({...state,accountMap:{...state.accountMap,[key]:input.value}});cache=null;render();onChange();}catch(e){status.textContent=e.message;}};label.append(input);mappingBody.append(label);}
 const query=search.value.trim().toLowerCase(),actions=approvedActions();visible=m.orders.filter(o=>(historical.checked||o.date>=s.from)&&(!query||[o.id,...o.items.map(i=>i.title+' '+i.asin)].join(' ').toLowerCase().includes(query))&&(!view.value||(view.value==='issues'?o.issues.length:view.value==='ready'?actions.some(a=>a.orderId===o.id):o.items.some(i=>m.signals.get(i.key).purpose===view.value)))).slice(0,limit);
 count.textContent=selection.size+' checked';clear.disabled=locked||!selection.size;approve.disabled=locked||!selection.size;select.disabled=locked||!visible.length;
 for(const order of visible){const card=make('details');card.className='amazon-order inspection-row';card.dataset.order=order.id;card.open=openOrders.has(order.id);card.ontoggle=()=>{if(card.open)openOrders.add(order.id);else openOrders.delete(order.id);};const signals=order.items.map(i=>m.signals.get(i.key));card.append(make('summary',order.date+' · '+cash(order.net)+' · '+order.id+' · '+order.items.length+' items'),make('p',signals.filter(i=>i.purpose==='Likely business').length+' likely business / '+signals.filter(i=>i.purpose==='Likely personal').length+' likely personal / '+signals.filter(i=>i.purpose==='Needs judgment').length+' need judgment. '+order.status));for(const issue of order.issues){const warning=make('p',issue);warning.className='warning';card.append(warning);};const items=make('div');items.className='amazon-items';
 for(const item of order.items){const signal=m.signals.get(item.key),decision=chosenFor(item,signal),row=make('div');row.className='amazon-item';const title=make('strong',item.title||'Missing item title'),meta=make('p','ASIN '+(item.asin||'Missing')+' · Qty '+item.quantity+' · Item total '+cash(item.net)),reason=make('p',signal.purpose+': '+signal.reason);row.append(title,meta,reason);const controls=make('div');controls.className='amazon-item-controls';const checkbox=make('input');checkbox.type='checkbox';checkbox.checked=selection.has(item.key);checkbox.disabled=locked;checkbox.setAttribute('aria-label','Select Amazon item '+item.asin+' '+order.id);checkbox.onchange=()=>{if(checkbox.checked)selection.add(item.key);else selection.delete(item.key);count.textContent=selection.size+' checked';clear.disabled=approve.disabled=locked||!selection.size;};const purpose=make('select');purpose.setAttribute('aria-label','Purpose for '+item.asin+' '+order.id);for(const value of ['Needs judgment','Business','Personal'])purpose.append(Object.assign(make('option',value),{value}));purpose.value=decision.purpose;const category=make('select');category.setAttribute('aria-label','Category for '+item.asin+' '+order.id);category.append(Object.assign(make('option','Choose exact category'),{value:''}));for(const name of s.categories)category.append(Object.assign(make('option',name),{value:name}));category.value=decision.category;purpose.disabled=category.disabled=locked;purpose.onchange=category.onchange=()=>{drafts[item.key]={purpose:purpose.value,category:category.value};};const approved=state.decisions[item.key];controls.append(checkbox,purpose,category,make('span',approved?'Approved locally':'Not approved'));row.append(controls);items.append(row);}card.append(items);
 const categoryTotals={};for(const item of order.items){const d=state.decisions[item.key];if(d?.category)categoryTotals[d.category]=(categoryTotals[d.category]||0)+(item.net||0);}if(Object.keys(categoryTotals).length>1)card.append(make('p','Mixed categories — split manually in Wave. Approved item totals: '+Object.entries(categoryTotals).map(([name,n])=>name+' '+cash(n)).join('; ')));
 for(const match of m.matches.filter(m=>m.orderId===order.id)){const p=match.payment,line=make('div');line.className='amazon-payment';line.append(make('p',p.instrument+' · '+p.identifier+' · '+(p.date||'No payment date')+' · '+cash(p.amount)+' · '+match.state),make('p',match.reason));if(match.state==='Candidate'){const t=s.dataset.transactions.find(t=>t.id===match.candidates[0]),reviewed=s.report?.records.find(r=>r.id===t.id)?.reviewed||'Unknown',a=actions.find(a=>a.id===t.id);line.append(make('p','Wave: '+t.date+' · '+t.primary.account+' · '+t.description+' · '+cash(t.amount)+' · Reviewed status '+reviewed));const confirm=make('button',state.links[order.id+':'+p.ref]?.id===t.id?'Reconfirm payment match':'Confirm payment match');confirm.disabled=locked||order.date<s.from||reviewed==='Reviewed'||!!order.issues.length;confirm.onclick=async()=>{try{await persist({...state,links:{...state.links,[order.id+':'+p.ref]:{id:t.id,snapshot:recordSnapshot(t),confirmedAt:new Date().toISOString()}}});render();onChange();}catch(e){status.textContent=e.message;}};const open=make('button',a?'Prepare matched transaction':'Inspect Wave candidate');open.className='secondary';open.disabled=locked;open.onclick=()=>inspect(a?proposalFor(t,a):t,a);line.append(confirm,open);}card.append(line);}results.append(card);}
 if(m.orders.filter(o=>historical.checked||o.date>=s.from).length>limit){const more=make('button','Show more Amazon orders');more.onclick=()=>{limit+=25;render();};results.append(more);}
 }
 async function importFiles(files){if(busy||loading||getState().busy||!getState().business)throw Error('Select the Wave business first.');if(files.length>10)throw Error('Choose up to ten Amazon reports at a time.');busy=true;onRunning(true);const business=getState().business,task=activity.begin('Reading Amazon item reports');render();try{await paintActivity();const additions=[];for(const file of files){if(file.size>30*1024*1024)throw Error('Choose CSV reports under 30 MB.');const text=await file.text();additions.push({name:file.name,sha256:await sourceHash(text),records:importAmazon(text)});}if(getState().business!==business)throw Error('Business changed during import.');const filesByHash=new Map([...state.files,...additions].map(f=>[f.sha256,f]));if([...filesByHash.values()].reduce((n,f)=>n+f.records.length,0)>100000)throw Error('Saved reports exceed 100,000 rows.');const next={...state,files:[...filesByHash.values()]};groupAmazon(next.files.flatMap(f=>f.records));await persist(next);cache=null;status.textContent='Amazon reports imported and saved locally. Review item purposes, then confirm payment matches.';selection.clear();onChange();}finally{busy=false;render();onRunning(false);task.finish();}}
 upload.onchange=async()=>{try{await importFiles([...upload.files]);}catch(e){status.textContent='Amazon import stopped: '+e.message;}upload.value='';};search.oninput=view.onchange=historical.onchange=()=>{limit=25;render();};
 select.onclick=()=>{const m=model();for(const o of visible)if(!o.cancelled&&!o.refund)for(const i of o.items){const suggestion=m.signals.get(i.key);if(suggestion.purpose!=='Needs judgment'&&suggestion.category)selection.add(i.key);}render();};clear.onclick=()=>{selection.clear();render();};
 approve.onclick=async()=>{if(busy||getState().busy)return;busy=true;onRunning(true);const task=activity.begin('Saving approved Amazon item purposes');try{await paintActivity();const m=model(),decisions={...state.decisions};for(const key of selection){const item=m.orders.flatMap(o=>o.items).find(i=>i.key===key);if(!item)throw Error('An item is no longer in the loaded report.');const d=chosenFor(item,m.signals.get(key));if(!['Business','Personal'].includes(d.purpose)||!getState().categories.includes(d.category))throw Error('Choose Business or Personal and an exact category for every checked item.');const personal=/^Personal\b|^Owner\b/i.test(d.category);if((d.purpose==='Business'&&personal)||(d.purpose==='Personal'&&!personal))throw Error('The selected purpose and category disagree. Choose a personal category for personal items.');decisions[key]={...d,approvedAt:new Date().toISOString()};}await persist({...state,decisions});selection.clear();status.textContent='Checked items approved locally. Confirm the payment match to prepare a transaction.';onChange();}catch(e){status.textContent=e.message;}finally{busy=false;render();onRunning(false);task.finish();}};
 const download=(value,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};exportReview.onclick=()=>download({format:'wave-solver-amazon-review',version:1,business:seen,createdAt:new Date().toISOString(),sources:state.files.map(f=>({name:f.name,sha256:f.sha256})),orders:model().orders,matches:model().matches,decisions:state.decisions,links:state.links},'wave-amazon-review.local.json');exportPlan.onclick=()=>{const s=getState(),actions=approvedActions(),byId=new Map(s.dataset.transactions.map(t=>[t.id,t])),queue=actions.map(a=>proposalFor(byId.get(a.id),a));download(buildPlan(queue,new Set(queue.map(t=>t.id)),{business:s.business,sourceName:state.files.map(f=>f.name).join(', '),sample:s.sample}),'wave-amazon-draft.local.json');};
 render();return {render,restore,importFiles,approvedActions,proposalFor,busy:()=>busy||loading};
}
