import {activity,paintActivity} from './activity.js';
import {runRecognizedWork} from './automation.js';
export function installAutomation({getState,refresh,prepare,list,execute,receipt,onChange=()=>{},showInput=()=>{}}){
 const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;},section=el('section'),fold=el('details'),body=el('div');fold.id='knownWork';fold.className='step';body.className='step-body';fold.append(el('summary','Solve recognized work automatically'),body);section.append(fold);document.getElementById('expenseBatch').closest('section').before(section);
 const run=el('button','Solve recognized work'),status=el('p'),next=el('button','Show only work needing my input'),transfers=el('input'),transferLabel=el('label',' Include unique existing transfer pairs');transfers.type='checkbox';transfers.checked=true;transferLabel.className='plan-choice';transferLabel.prepend(transfers);next.className='secondary';next.onclick=()=>showInput();body.append(el('p','One click refreshes Not Reviewed, prepares purchases recognized by your approved rules or saved group choices, runs them, checks Wave after every save, and refreshes what remains. Matching Wave suggestions use thumbs-up first. Safe preflight exceptions are skipped; uncertain saves stop and remain locked.'),transferLabel,run,next,status);
 const quick=el('div');quick.className='automation-shortcut';const shortcut=el('button','Solve recognized work'),hint=el('span','Let the solver handle known expenses and transfers; review only exceptions.');quick.append(shortcut,hint);document.querySelector('main .notice')?.after(quick);let running=false,last='';
 function render(){const s=getState();run.disabled=shortcut.disabled=running||s.busy||!s.business||!s.dataset||!s.extensionMode||s.sample;transfers.disabled=running;status.textContent=last||'Sources and rules stay saved. This button executes eligible work and verifies it in Wave.';}
 async function start(){const s=getState();if(running||s.busy||!s.business||!s.dataset||!s.extensionMode||s.sample)return;running=true;render();const task=activity.begin('Solving recognized work',{priority:5}),main=document.querySelector('main'),panel=el('div'),text=el('p'),stopButton=el('button','Stop after current step');panel.className='transfer-run-progress';panel.append(text,stopButton);document.body.append(panel);let stop=false;stopButton.onclick=()=>{stop=true;stopButton.disabled=true;text.textContent='Stopping after the current step finishes.';};main.inert=true;
 const current=()=>{const now=getState();return now.business===s.business&&now.dataset===s.dataset&&now.from===s.from;};try{await paintActivity();const result=await runRecognizedWork({refresh,prepare,list:()=>list(transfers.checked),execute,receipt,current,stopped:()=>stop,progress:p=>{main.inert=true;text.textContent=p.phase+(p.total?' · '+(p.index+1)+' of '+p.total:'');task.update({detail:text.textContent,...(p.total?{total:p.total,completed:p.index}:{})});}});last=result.completed+' completed and verified · '+result.skipped+' already completed skipped · '+result.attention.length+' need attention'+(result.uncertain?' · stopped on an uncertain result':result.stopped?' · stopped':' · remaining work refreshed');if(result.attention.length)last+=' · '+result.attention.slice(0,2).map(a=>a.reason).join(' | ');}catch(e){last='Run stopped: '+e.message;}finally{running=false;panel.remove();main.inert=false;task.finish(last);onChange();render();}}
 run.onclick=shortcut.onclick=()=>void start();render();return {render,start,busy:()=>running};
}
