import {normalize,matchingRules,nonPurchaseReason} from './rules.js';
import {evidenceSnapshot,sourceReviewStatuses,serviceSuggestion} from './service-solvers.js';
import {recordSnapshot} from './plan.js';
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const categoryOK=(d,categories)=>d&&['Business','Personal'].includes(d.purpose)&&categories.includes(d.category)&&!/(?:Uncategorized\b|Needs Review)|^(?:Transfer\b|Retained Earnings|Opening balance)/i.test(d.category)&&(d.purpose==='Personal')===/^Personal\b|^Owner\b/i.test(d.category);
export function sourceGroupKey(r){return JSON.stringify([r.provider,r.profileIdentity||'',normalize(r.merchant).replace(/\b(inc|incorporated|llc|ltd|limited|corporation)\b/g,'').trim(),r.instrumentKey,r.currency,r.provider==='venmo'?String(r.note||'').normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim():'',r.provider==='amazon'&&(!(r.items||[]).length||(r.items||[]).some(i=>!i.title))?['missing-item-evidence',r.sourceId]:r.provider==='amazon'?(r.items||[]).map(i=>[i.asin||'',normalize(i.title),i.quantity]).sort():[]]);}
export function knownSourceChoice(r,t,state,{rules=[],categories=[],business}={}){
 const d=state.decisions?.[r.key];if(d){if(!same(d.expected,evidenceSnapshot(r)))return {problem:'Source details changed since approval.'};if(!categoryOK(d,categories))return {problem:'Saved purpose/category is not valid.'};if(d.approvedBy==='merchant-rule'){const hits=approvedHits(r,t,rules,business);if(!hits.some(rule=>same(rule,d.approvedRule)))return {problem:'The rule behind this source approval changed.'};}if(d.approvedBy==='similar-group'&&t.categories.some(c=>!/^Uncategorized\b|Needs Review/i.test(c)&&c!==d.category))return {problem:'Existing category differs from the group choice.'};if(d.approvedBy==='similar-group'&&!same(state.groups?.[d.groupKey],d.groupPolicy))return {problem:'The similar-purchase decision changed.'};return {choice:d,reason:'Saved source decision'};}
 const policy=state.groups?.[sourceGroupKey(r)];if(policy&&categoryOK(policy,categories)){if(t.categories.some(c=>!/^Uncategorized\b|Needs Review/i.test(c)&&c!==policy.category))return {problem:'Existing category differs from the group choice.'};return {choice:{purpose:policy.purpose,category:policy.category,approvedBy:'similar-group',groupKey:sourceGroupKey(r),groupPolicy:policy},reason:'Your similar-purchase decision'};}
 const hits=approvedHits(r,t,rules,business),targets=[...new Set(hits.map(rule=>rule.category))];if(targets.length!==1)return {problem:targets.length?'Approved rules disagree.':'No approved rule or group decision applies.'};const category=targets[0],choice={purpose:/^Personal\b|^Owner\b/i.test(category)?'Personal':'Business',category,approvedBy:'merchant-rule',approvedRule:hits[0]};return categoryOK(choice,categories)?{choice,reason:'Approved merchant rule'}:{problem:'Approved category is not a spending category.'};
}
function approvedHits(r,t,rules,business){return [...new Set([...matchingRules(r.merchant,rules,t,business),...matchingRules(t.description,rules,t,business)])];}
export function sourceAutomation(records,matches,state,{transactions=[],queue=[],rules=[],categories=[],business,from='2025-01-01',reports=[],receipt=()=>null}={}){
 const byID=new Map(transactions.map(t=>[t.id,t])),byMatch=new Map(matches.map(m=>[m.key,m])),byQueue=new Map(queue.map(t=>[t.id,t])),reviewed=sourceReviewStatuses(reports,business),decisions={...state.decisions},links={...state.links},ready=[],attention=[];
 for(const r of records){if(r.kind!=='Purchase'||r.date<from)continue;const m=byMatch.get(r.key),id=m?.candidates.length===1?m.candidates[0]:null,t=byID.get(id);if(id&&reviewed.get(id)?.reviewed==='Reviewed')continue;const fail=reason=>attention.push({key:r.key,id,reason});if(state.exclusions?.[r.key]){fail('You removed this source approval.');continue;}if(r.blocked||r.conflict||!r.bankExpected){fail(r.blocked||'Source conflict or unconfirmed funding.');continue;}if(!t||m.state!=='Candidate'){fail(m?.reason||'Needs an unambiguous Wave match.');continue;}if(t.date<from||t.direction!=='out'||!t.primary||/loan/i.test(t.primary.type)||t.existingTransfer||t.postings.length!==2||t.categories.length!==1||['Transfer candidate','Ambiguous transfer','Possible refund','Existing multi-account'].includes(byQueue.get(id)?.kind)){fail('Transfer, refund, loan or split needs separate review.');continue;}const excluded=nonPurchaseReason(t);if(excluded&&(!/Payment, cash, transfer, check, or loan needs separate review/.test(excluded)||!new RegExp('^'+r.provider+'\\b','i').test(t.description)||/\b(cash|atm|loan|check|card payment|credit crd|autopay)\b/i.test(t.description))){fail(excluded);continue;}const old=receipt(t);if(old?.reviewedVerified){fail('Previously verified record returned to the live backlog; recheck its saved result.');continue;}if(old?.stage==='expense-preflight'||(old?.saveAttempted&&(!old.categoryVerified||old.reviewAttempted))){fail('A previous attempt requires attention; no automatic retry.');continue;}if(state.links?.[r.key]&&!same(state.links[r.key].expected,recordSnapshot(t))){fail('Wave export changed since the saved link.');continue;}const result=knownSourceChoice(r,t,state,{rules,categories,business});if(result.problem){fail(result.problem);continue;}if(r.provider==='amazon'&&result.choice.approvedBy==='merchant-rule'){const signal=serviceSuggestion(r,rules,categories,t,business);if(r.allocationNeedsReview||signal.category!==result.choice.category||signal.purpose!==result.choice.purpose){fail('Amazon items or payment allocation need your input.');continue;}}decisions[r.key]={...result.choice,expected:evidenceSnapshot(r),approvedAt:state.decisions?.[r.key]?.approvedAt||new Date().toISOString()};links[r.key]={id,expected:recordSnapshot(t),confirmedAt:state.links?.[r.key]?.confirmedAt||new Date().toISOString(),automatic:true};ready.push({key:r.key,id,category:result.choice.category,reason:result.reason});}
 const counts=new Map();for(const r of ready)counts.set(r.id,(counts.get(r.id)||0)+1);for(const r of ready.filter(r=>counts.get(r.id)>1)){delete decisions[r.key];delete links[r.key];attention.push({key:r.key,id:r.id,reason:'Multiple sources claim the same Wave record.'});}return {state:{...state,decisions,links},ready:ready.filter(r=>counts.get(r.id)===1),attention};
}
export function chooseSimilarSources(records,anchor,choice,state,{categories=[],from='2025-01-01',matches=[],transactions=[],reports=[],business}={}){
 if(!categoryOK(choice,categories))throw Error('Choose a consistent purpose and exact spending category.');const exclusions={...state.exclusions},groupKey=sourceGroupKey(anchor),policy={purpose:choice.purpose,category:choice.category,approvedAt:new Date().toISOString()},groups={...state.groups,[groupKey]:policy},decisions={...state.decisions},byID=new Map(transactions.map(t=>[t.id,t])),reviewed=sourceReviewStatuses(reports,business),changed=[],held=[];
 for(const r of records){if(r.kind!=='Purchase'||r.date<from||sourceGroupKey(r)!==groupKey)continue;const match=matches.find(m=>m.key===r.key),t=match?.candidates.length===1?byID.get(match.candidates[0]):null;if(t&&reviewed.get(t.id)?.reviewed==='Reviewed')continue;if(r.blocked||r.conflict||(t&&t.categories.some(c=>!/^Uncategorized\b|Needs Review/i.test(c)&&c!==choice.category))){held.push(r.key);continue;}decisions[r.key]={purpose:choice.purpose,category:choice.category,expected:evidenceSnapshot(r),approvedBy:'similar-group',groupKey,groupPolicy:policy,approvedAt:policy.approvedAt};delete exclusions[r.key];changed.push(r.key);}
 return {state:{...state,groups,decisions,exclusions},changed,held};
}
export function automationReceiptState(type,r){if(!r)return 'ready';if(type==='transfer'&&r.verified&&r.reviewed||type==='expense'&&r.reviewedVerified)return 'completed';if(['preflight','expense-preflight'].includes(r.stage))return 'attention';if(r.saveAttempted){if(type==='expense'&&r.categoryVerified&&!r.reviewAttempted)return 'ready';if(type==='transfer'&&r.verified&&!Object.values(r.reviewAttempts||{}).some(a=>a.attempted))return 'ready';return 'attention';}return 'ready';}
export async function runRecognizedWork({refresh,prepare,list,execute,current=()=>true,stopped=()=>false,progress=()=>{},receipt=()=>null}){
 const result={completed:0,skipped:0,attention:[],stopped:false,uncertain:false};const check=()=>{if(!current())throw Error('Session changed.');};check();progress({phase:'Collecting current Not Reviewed list'});await refresh();check();if(stopped()){result.stopped=true;return result;}progress({phase:'Preparing recognized source purchases'});await prepare();check();const tasks=list();
 for(const [index,task] of tasks.entries()){check();if(stopped()){result.stopped=true;break;}const state=automationReceiptState(task.type,receipt(task));if(state==='completed'&&!task.recheck){result.skipped++;continue;}if(state==='attention'){result.attention.push({task,reason:'Previous attempt needs a recheck.'});continue;}progress({phase:'Checking and saving '+task.type,index,total:tasks.length,task});let outcome;try{outcome=await execute(task,state==='completed');}catch(e){result.attention.push({task,reason:e.message});if(state==='completed')continue;result.stopped=true;result.uncertain=true;break;}check();if(state==='completed'){if(task.type==='expense'?outcome?.reviewedVerified:outcome?.verified&&outcome.reviewed)result.skipped++;else result.attention.push({task,reason:outcome?.message||'Previously completed record needs attention; no repeat save.'});continue;}if(outcome?.needsAttention&&!outcome.saveAttempted){result.attention.push({task,reason:outcome.message||'Live preflight needs attention.'});continue;}if(outcome?.skipped){result.skipped++;continue;}if(task.type==='expense'?outcome?.reviewedVerified:outcome?.verified&&outcome.reviewed){result.completed++;continue;}result.attention.push({task,reason:outcome?.message||'Saved result is not verified.'});result.stopped=true;result.uncertain=true;break;}
 if(current()){progress({phase:'Refreshing remaining work'});try{await refresh();}catch(e){result.attention.push({reason:'Final collection: '+e.message});}}return result;
}
