import {importAmazon} from './amazon.js';
import {importAccounting} from './model.js';
import {venmoDigest} from './venmo.js';
export const amazonReportURL='https://www.amazon.com/b2b/aba/reports?reportType=items_report_1&dateSpanSelection=MONTH_TO_DATE';
export const amazonPrivacyURL='https://www.amazon.com/hz/privacy-central/data-requests/preview.html';
export const amazonReportOrigins=['https://www.amazon.com/b2b/aba/*'];
export const waveHelperOrigins=['https://accounting.waveapps.com/settings/export/*','https://mail.google.com/mail/*','https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/*'];
export function validRange(start,end){const valid=d=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&Number.isFinite(Date.parse(d+'T00:00:00Z'))&&new Date(d+'T00:00:00Z').toISOString().slice(0,10)===d;if(!valid(start)||!valid(end)||end<start)throw Error('Choose valid start and end dates.');return {start,end};}
export function amazonDownloadName(filename,range){const name=String(filename||'').split(/[\\/]/).at(-1);const m=name.match(/^orders_from_(\d{8})_to_(\d{8})_.*\.csv$/i);return !!m&&m[1]===range.start.replaceAll('-','')&&m[2]===range.end.replaceAll('-','');}
export function amazonDownloadItem(item,range){if(!amazonDownloadName(item.filename,range))return false;return [item.referrer,item.url].some(value=>{try{return new URL(value).origin==='https://www.amazon.com';}catch{return false;}});}
export function waveDownloadURL(value){try{const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)return false;if(url.hostname==='wave-prod-accounting.s3.amazonaws.com')return /^\/accounting_exports\/[a-z0-9-]+\.zip$/i.test(url.pathname);if(url.hostname==='track.pstmrk.it'){const part=url.pathname.match(/^\/3s\/([^/]+)\//)?.[1];if(!part)return false;return waveDownloadURL('https://'+decodeURIComponent(part));}return false;}catch{return false;}}
export function waveMailSearch(index=0){if(!Number.isInteger(index)||index<0||index>20)throw Error('Choose a valid Gmail account number.');return 'https://mail.google.com/mail/u/'+index+'/#search/'+encodeURIComponent('from:no-reply@waveapps.com subject:"Your transactions data export is ready" newer_than:1d');}
export async function readInboxFile(inbox,item,{maxBytes=40*1024*1024,pause=()=>new Promise(r=>setTimeout(r,250)),current=()=>true}={}){const name=String(item.filename||'').split(/[\\/]/).at(-1);if(!name||/[\\/]/.test(name)||name==='.'||name==='..')throw Error('Download filename is unavailable.');for(let i=0;i<20;i++){if(!current())throw Error('Stopped before reading the downloaded file.');try{const file=await(await inbox.getFileHandle(name)).getFile();if(file.size>maxBytes)throw Error('Downloaded file is too large for local import.');return file;}catch(e){if(e.name!=='NotFoundError'||i===19)throw e;await pause();}}}
export async function observeNativeDownload({downloads,inbox,accept,trigger,current=()=>true,checkpoint=async()=>{},timeoutMs=240000,pause=ms=>new Promise(r=>setTimeout(r,ms)),onProgress=()=>{},resumeId=null}){
 const started=Date.now(),ids=new Set(),completed=new Map();if(resumeId!==null)ids.add(resumeId);
 const created=item=>{if(Date.parse(item.startTime||'')>=started-1000)ids.add(item.id);};
 const changed=delta=>{if(ids.has(delta.id)&&delta.state?.current)completed.set(delta.id,delta.state.current);};downloads.onCreated.addListener(created);downloads.onChanged.addListener(changed);
 try{if(!current())throw Error('Stopped before requesting a download.');if(trigger){const provided=await trigger();if(provided?.file){if(!current())throw Error('Stopped before reading the downloaded file.');return {file:provided.file,provided:true};}}while(Date.now()-started<timeoutMs){if(!current())throw Error('Stopped. Resume can collect a report that finishes later.');for(const id of ids){const items=await downloads.search({id});const item=items[0];if(!item||!accept(item))continue;await checkpoint({downloadId:id,filename:String(item.filename||'').split(/[\\/]/).at(-1)});if(item.state==='interrupted'||completed.get(id)==='interrupted')throw Error('The browser download was interrupted. Retry it in the provider page, then Resume.');if(item.state==='complete'||completed.get(id)==='complete')return {item,file:await readInboxFile(inbox,item,{current})};}onProgress('Waiting for the browser download…');await pause(500);}return {waiting:true};}finally{downloads.onCreated.removeListener(created);downloads.onChanged.removeListener(changed);}
}
export async function findAmazonInbox(inbox,job){const files=[];for await(const [name,handle] of inbox.entries()){if(handle.kind!=='file'||!amazonDownloadName(name,job))continue;const file=await handle.getFile();if(file.lastModified>=Date.parse(job.requestedAt)-2000)files.push(file);}if(files.length>1)throw Error('Several matching Amazon downloads exist. Choose the exact CSV manually.');return files[0]||null;}
async function writeFile(dir,name,bytes){const file=await dir.getFileHandle(name,{create:true}),stream=await file.createWritable();try{await stream.write(bytes);await stream.close();}catch(e){await stream.abort?.();throw e;}}
export async function saveDistinctFile(dir,stem,extension,bytes){if(!/^[a-z0-9_-]+$/i.test(stem)||!/^\.[a-z0-9]+$/i.test(extension))throw Error('Unsafe destination filename.');const raw=bytes instanceof Uint8Array?bytes:new TextEncoder().encode(bytes),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',raw)),n=>n.toString(16).padStart(2,'0')).join('');const same=async name=>{try{const f=await(await dir.getFileHandle(name)).getFile(),b=new Uint8Array(await f.arrayBuffer());return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',b)),n=>n.toString(16).padStart(2,'0')).join('');}catch(e){if(e.name==='NotFoundError')return null;throw e;}};let name=stem+extension;const first=await same(name);if(first===hash)return {name,hash,reused:true};if(first!==null){name=stem+'-'+hash.slice(0,16)+extension;const second=await same(name);if(second===hash)return {name,hash,reused:true};if(second!==null)throw Error('Conflicting destination file; no file overwritten.');}await writeFile(dir,name,bytes);return {name,hash,reused:false};}
export async function saveAmazonReport(root,file,range){validRange(range.start,range.end);if(file.size>30*1024*1024)throw Error('Use an Amazon CSV smaller than 30 MB.');const text=await file.text(),rows=importAmazon(text);if(rows.some(r=>!r.date||r.date<range.start||r.date>range.end))throw Error('Amazon order dates disagree with the requested range.');const amazon=await root.getDirectoryHandle('amazon',{create:true}),business=await amazon.getDirectoryHandle('business',{create:true}),result=await saveDistinctFile(business,'amazon-business-'+range.start+'-to-'+range.end,'.csv',text);return {...result,path:'amazon/business/'+result.name,count:rows.length,orders:new Set(rows.map(r=>r.orderId)).size};}
export function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^0xffffffff)>>>0;}
export async function unpackWaveZIP(input){const bytes=input instanceof Uint8Array?input:new Uint8Array(input);if(bytes.length>40*1024*1024||bytes.length<22)throw Error('Use a Wave ZIP under 40 MB.');const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),u16=p=>view.getUint16(p,true),u32=p=>view.getUint32(p,true);let end=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--){if(u32(p)===0x06054b50&&p+22+u16(p+20)===bytes.length){end=p;break;}}if(end<0||u16(end+4)||u16(end+6)||u16(end+8)!==u16(end+10))throw Error('Unsupported or incomplete ZIP.');const count=u16(end+10),central=u32(end+16),centralSize=u32(end+12);if(!count||count>12||central+centralSize!==end)throw Error('Wave ZIP has an unexpected entry count or directory.');const files=[],names=new Set();let offset=central,total=0;
 for(let i=0;i<count;i++){if(offset+46>end||u32(offset)!==0x02014b50)throw Error('Malformed ZIP directory.');const flags=u16(offset+8),method=u16(offset+10),crc=u32(offset+16),compressed=u32(offset+20),size=u32(offset+24),length=u16(offset+28),extra=u16(offset+30),comment=u16(offset+32),local=u32(offset+42),attributes=u32(offset+38),next=offset+46+length+extra+comment;if(next>end||flags&1||![0,8].includes(method)||u16(offset+34)||((attributes>>>16)&0xf000)===0xa000||[size,compressed,local].includes(0xffffffff))throw Error('Encrypted, linked or unsupported ZIP entry.');const name=new TextDecoder('utf-8',{fatal:true}).decode(bytes.slice(offset+46,offset+46+length));offset=next;if(name.endsWith('/'))continue;if(!/^[a-z0-9_-]+\.csv$/i.test(name)||names.has(name.toLowerCase()))throw Error('Wave ZIP contains unsafe paths or duplicate files.');names.add(name.toLowerCase());total+=size;if(size>30*1024*1024||total>80*1024*1024||local+30>central||u32(local)!==0x04034b50)throw Error('ZIP size or local header is invalid.');const localName=u16(local+26),localExtra=u16(local+28),start=local+30+localName+localExtra;if(start+compressed>central||u16(local+6)!==flags||u16(local+8)!==method||new TextDecoder().decode(bytes.slice(local+30,local+30+localName))!==name)throw Error('ZIP headers disagree.');let content=bytes.slice(start,start+compressed);if(method===8){const reader=new Blob([content]).stream().pipeThrough(new DecompressionStream('deflate-raw')).getReader(),parts=[];let n=0;try{while(true){const part=await reader.read();if(part.done)break;n+=part.value.length;if(n>size||n>30*1024*1024)throw Error('ZIP decompressed size exceeded its limit.');parts.push(part.value);}}catch(e){await reader.cancel().catch(()=>{});throw e;}content=new Uint8Array(n);let p=0;for(const part of parts){content.set(part,p);p+=part.length;}}if(content.length!==size||crc32(content)!==crc)throw Error('ZIP entry failed its checksum or size check.');files.push({name,bytes:content});}
 if(offset!==end||files.length!==4||!files.some(f=>f.name.toLowerCase()==='accounting.csv'))throw Error('Expected the four-file Wave accounting CSV export.');const accounting=files.find(f=>f.name.toLowerCase()==='accounting.csv'),text=new TextDecoder('utf-8',{fatal:true}).decode(accounting.bytes),dataset=importAccounting(text);return {files,text,dataset};
}
export function sameWaveHistory(previous,next){const byID=new Map(next.transactions.map(t=>[t.id,t])),shared=previous.transactions.filter(t=>byID.has(t.id));if(!previous.transactions.length||shared.length<Math.max(1,Math.ceil(previous.transactions.length*0.8)))return false;return shared.every(t=>{const n=byID.get(t.id);return t.date===n.date&&t.direction===n.direction&&t.amount===n.amount&&t.description===n.description&&t.primary?.account===n.primary?.account;});}
export async function saveWaveArchive(root,bytes,{business,confirmed=false}={}){if(!/^[0-9a-f-]{36}$/i.test(business||''))throw Error('Select the Wave business first.');const parsed=await unpackWaveZIP(bytes),wave=await root.getDirectoryHandle('wave',{create:true});let previous=null;try{previous=await(await wave.getFileHandle('accounting.csv')).getFile();}catch(e){if(e.name!=='NotFoundError')throw e;}const matched=previous?sameWaveHistory(importAccounting(await previous.text()),parsed.dataset):false;if(!matched&&!confirmed)return {needsConfirmation:true,count:parsed.dataset.transactions.length,accounts:[...new Set(parsed.dataset.transactions.map(t=>t.primary?.account).filter(Boolean))]};
 const snapshots=await wave.getDirectoryHandle('exports',{create:true}),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),n=>n.toString(16).padStart(2,'0')).join(''),dir=await snapshots.getDirectoryHandle('export-'+hash.slice(0,16),{create:true});await saveDistinctFile(dir,'wave-export','.zip',bytes);for(const file of parsed.files)await saveDistinctFile(dir,file.name.slice(0,-4),'.csv',file.bytes);if(previous){const history=await wave.getDirectoryHandle('history',{create:true});await saveDistinctFile(history,'accounting','.csv',new Uint8Array(await previous.arrayBuffer()));}await writeFile(wave,'accounting.csv',new TextEncoder().encode(parsed.text));await writeFile(dir,'manifest.local.json',JSON.stringify({format:'wave-solver-wave-export',version:1,business,hash,importedAt:new Date().toISOString(),files:parsed.files.map(f=>f.name),transactionCount:parsed.dataset.transactions.length,historyMatched:matched},null,2));return {hash,count:parsed.dataset.transactions.length,path:'wave/accounting.csv',historyMatched:matched};}
// Signed export URLs live only in memory, never in checkpoints or diagnostics.
export async function fetchWaveArchive(value,{fetcher=fetch,current=()=>true,maxBytes=40*1024*1024,timeoutMs=60000}={}){
 let url;try{url=new URL(value);}catch{throw Error('The Wave export link is invalid.');}
 if(url.origin!=='https://wave-prod-accounting.s3.amazonaws.com'||!waveDownloadURL(value)||Number(url.searchParams.get('Expires'))*1000<=Date.now()||!Number.isFinite(Number(url.searchParams.get('Expires')))||!url.searchParams.has('Expires'))throw Error('The Wave export link is invalid or expired.');
 if(!current())throw Error('Stopped before fetching the Wave ZIP.');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs),stop=setInterval(()=>{if(!current())controller.abort();},200);
 let reader;try{
  const response=await fetcher(url.href,{credentials:'omit',redirect:'error',signal:controller.signal,referrerPolicy:'no-referrer'});
  if(!response.ok||!response.body)throw Error('Wave did not return a downloadable ZIP.');
  const length=Number(response.headers.get('content-length'));if(length>maxBytes)throw Error('Use a Wave ZIP under 40 MB.');
  reader=response.body.getReader();const parts=[];let size=0;
  while(true){if(!current())throw Error('Stopped while fetching the Wave ZIP.');const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>maxBytes)throw Error('Use a Wave ZIP under 40 MB.');parts.push(part.value);}
  if(!current())throw Error('Stopped before importing the Wave ZIP.');const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}return bytes;
 }catch(e){await reader?.cancel().catch(()=>{});if(!current())throw Error('Stopped. Resume uses the existing export request.');if(e.message==='Use a Wave ZIP under 40 MB.')throw e;throw Error('Could not fetch the Wave ZIP directly. Resume or download it from the email and select the ZIP here.');}
 finally{clearTimeout(timeout);clearInterval(stop);}
}
export async function waitWaveMail({read,openLatest,refresh,current=()=>true,onProgress=()=>{},pause=ms=>new Promise(r=>setTimeout(r,ms)),now=()=>Date.now(),timeoutMs=600000,refreshMs=5000}){
 const started=now();let refreshed=started,initialFailures=0;
 while(now()-started<timeoutMs){
  if(!current())throw Error('Stopped. Export request saved for Resume.');
  const seconds=Math.floor((now()-started)/1000);onProgress('Waiting for Wave export email · '+seconds+' seconds · search refreshes every 5 seconds');
  let info;try{info=await read();initialFailures=0;}catch(e){if(initialFailures++>=2)throw e;await pause(1000);continue;}
  if(info.readyLinks)return {ready:true};
  if(info.searchPage)await openLatest();
  if(now()-refreshed>=refreshMs){await refresh();refreshed=now();}
  await pause(1000);
 }
 return {waiting:true};
}
