import {amazonDownloadPage,waveExportPage,waveMailPage} from './download-pages.js';
const $=id=>document.getElementById(id),saved=new Map();
function folder(name){const dirs=new Map(),files=new Map();return {name,dirs,files,queryPermission:async()=> 'granted',requestPermission:async()=> 'granted',entries:async function*(){for(const [n,d] of dirs)yield [n,{...d,kind:'directory'}];for(const [n,f] of files)yield [n,{kind:'file',getFile:async()=>f}];},getDirectoryHandle:async(n,{create=false}={})=>{if(!dirs.has(n)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});dirs.set(n,folder(n));}return dirs.get(n);},getFileHandle:async(n,{create=false}={})=>{if(!files.has(n)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});files.set(n,new File([],n));}return {getFile:async()=>files.get(n),createWritable:async()=>({write:async value=>files.set(n,new File([value],n)),close:async()=>{},abort:async()=>{}})};}};}
Object.defineProperty(window,'indexedDB',{value:{open:()=>{const request={result:{transaction:()=>{const tx={objectStore:()=>({get:key=>{const r={};setTimeout(()=>{r.result=saved.get(key);setTimeout(()=>tx.oncomplete?.(),0);},0);return r;},put:(value,key)=>{saved.set(key,value);setTimeout(()=>tx.oncomplete?.(),0);}})};return tx;},close(){}}};setTimeout(()=>request.onsuccess?.(),0);return request;}}});
const data=folder('data'),inbox=folder('Downloads');window.showDirectoryPicker=async options=>options.id.includes('browser')?inbox:data;
const section=document.createElement('section');section.innerHTML='<h2>Business analytics</h2><h3>Orders report</h3><label>Order Date<select id="mockRange"><option>Month to date</option><option>Custom Range</option></select></label><label>Start date<input id="mockStart" disabled></label><label>End date<input id="mockEnd" disabled></label><button id="mockSubmit">Submit</button><button id="mockGenerate" disabled>Generate report</button><a href="#mock-history">Download history</a>';document.querySelector('main').append(section);
const amazonLocation={origin:'https://www.amazon.com',pathname:'/b2b/aba/reports',href:'https://www.amazon.com/b2b/aba/reports?reportType=items_report_1'},context={document,root:section,location:amazonLocation,pause:async()=>{}};
let submits=0,generations=0,serial=0;const created=new Set(),changed=new Set(),items=new Map();
$('mockRange').onchange=()=>{$('mockStart').disabled=$('mockEnd').disabled=$('mockRange').value!=='Custom Range';};
$('mockSubmit').onclick=()=>{submits++;$('mockGenerate').disabled=false;};$('mockGenerate').onclick=()=>{generations++;const date=v=>v.slice(6)+'-'+v.slice(0,2)+'-'+v.slice(3,5),start=date($('mockStart').value),end=date($('mockEnd').value),filename='orders_from_'+start.replaceAll('-','')+'_to_'+end.replaceAll('-','')+'_synthetic.csv';const text='Order Date,Order ID,Currency,Order Net Total,Order Status,ASIN,Title,Item Quantity,Item Net Total,Payment Reference ID,Payment Date,Payment Amount,Payment Instrument Type,Payment Identifier\n'+start+',fictional-order-01,USD,10.00,Closed,FAKEASIN,Fictional item,1,10.00,fictional-ref,'+start+',10.00,Visa,1111';data.files.set(filename,new File([text],filename));const item={id:++serial,filename:'C:/Downloads/'+filename,startTime:new Date().toISOString(),state:'complete',referrer:'https://www.amazon.com/'};items.set(item.id,item);for(const fn of created)fn(item);};
window.chrome={runtime:{id:'synthetic-downloads'},permissions:{contains:async()=>true,request:async()=>true},tabs:{query:async()=>[{id:1,url:amazonLocation.href,title:'Synthetic Amazon reports'}],get:async()=>({id:1,url:amazonLocation.href}),update:async()=>({id:1}),create:async()=>({id:1})},downloads:{onCreated:{addListener:fn=>created.add(fn),removeListener:fn=>created.delete(fn)},onChanged:{addListener:fn=>changed.add(fn),removeListener:fn=>changed.delete(fn)},search:async({id})=>items.has(id)?[items.get(id)]:[]},scripting:{executeScript:async({func,args})=>[{result:await func(args[0],context)}]}};
await import('./download-app.js');
$('fixtureRun').onclick=async()=>{const log=[],check=(ok,name)=>{if(!ok)throw Error(name);log.push('PASS '+name);};try{
 check($('run').disabled,'Collection explains missing folders');await $('data').onclick();check(!$('run').disabled,'Linking folders enables Amazon collection');await $('run').onclick();check($('status').textContent.includes('Amazon report saved'),'Native download copied and validated');check(submits===1&&generations===1,'Dates submit before one Generate report click');check($('mockRange').value==='Custom Range','Custom Range is selected before date entry');check(data.dirs.get('amazon').dirs.get('business').files.size===1,'Business reports use a separate destination');check(created.size===0&&changed.size===0,'Download listeners are released');check(!$('run').disabled&&$('stop').disabled,'Busy controls return to ready');await $('diagnose').onclick();check(JSON.parse($('diagnostics').textContent).businessReport===true,'Safe Amazon diagnostics identify report controls');
 let rejected=false;try{await amazonDownloadPage({action:'read'},{...context,location:{...amazonLocation,pathname:'/gp/your-account/order-history'}});}catch{rejected=true;}check(rejected,'Regular Amazon is not treated as Business analytics');$('mockSubmit').disabled=true;const unsubmitted=await amazonDownloadPage({action:'generate',start:'2026-01-01',end:'2026-12-31'},context);check(unsubmitted.notSubmitted&&generations===1,'Disabled Submit does not generate');$('mockSubmit').disabled=false;
 const wave=document.createElement('section');wave.innerHTML='<h2>Accounting</h2><button id="mockWaveExport">Export all transactions as CSV</button>';document.querySelector('main').append(wave);let requests=0;$('mockWaveExport').onclick=()=>requests++;const exportURL='https://accounting.waveapps.com/settings/export/123456/',waveContext={...context,root:wave,location:{origin:'https://accounting.waveapps.com',pathname:'/settings/export/123456/',href:exportURL}};
 const info=await waveExportPage({action:'read',exportURL},waveContext);check(info.accountingExportButtons===1,'Accounting CSV export identified');await waveExportPage({action:'request',exportURL},waveContext);check(requests===1,'Wave request clicks its exact export button once');rejected=false;try{await waveExportPage({action:'request',exportURL:exportURL.replace('123456','654321')},waveContext);}catch{rejected=true;}check(rejected&&requests===1,'Another business export page rejected');
 const mail=document.createElement('section');mail.innerHTML='<button aria-label="Google Account: Fictional (fictional@example.invalid)">Synthetic mailbox</button><h2>Your transactions data export is ready</h2><article data-wave-message><span email="no-reply@waveapps.com">The Wave Team</span><a id="mockWaveLink">Download data export</a></article>';document.querySelector('main').append(mail);const expires=Math.floor((Date.now()+24*3600000)/1000),direct='https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/fictional-export.zip?Expires='+expires;const link=$('mockWaveLink');link.href='https://track.pstmrk.it/3s/'+encodeURIComponent(direct.replace('https://',''))+'/fake';let clicks=0;link.onclick=e=>{e.preventDefault();clicks++;};mail.querySelector('article').setAttribute('data-time',Date.now());const mailContext={...context,root:mail,location:{origin:'https://mail.google.com',pathname:'/mail/u/1/',href:'https://mail.google.com/mail/u/1/#inbox/fake'}},request={mailbox:'fictional@example.invalid',mailIndex:1,requestedAt:new Date().toISOString()};
 const safe=await waveMailPage({...request,action:'read'},mailContext);check(safe.readyLinks===1&&safe.mailboxMatched,'Fresh matching export email is identified');check(!JSON.stringify(safe).includes('Expires')&&!JSON.stringify(safe).includes('example.invalid'),'Email diagnostics omit addresses and signed URLs');await waveMailPage({...request,action:'download'},mailContext);check(clicks===1,'Fresh export link is clicked once');rejected=false;try{await waveMailPage({...request,mailbox:'other@example.invalid',action:'download'},mailContext);}catch{rejected=true;}check(rejected&&clicks===1,'Wrong Gmail mailbox cannot click the link');link.href=direct.replace('Expires='+expires,'Expires=1');check((await waveMailPage({...request,action:'read'},mailContext)).readyLinks===0,'Expired links excluded');link.href='https://evil.example/report.zip';check((await waveMailPage({...request,action:'read'},mailContext)).readyLinks===0,'Unapproved export destination excluded');link.href=direct;mail.querySelector('[email]').setAttribute('email','fake@example.invalid');check((await waveMailPage({...request,action:'read'},mailContext)).readyLinks===0,'Wrong sender excluded');
 $('fixtureResult').textContent=log.join('\n');
 }catch(e){$('fixtureResult').textContent=log.join('\n')+'\nFAIL '+e.message;}};
