import {amazonReportURL,amazonPrivacyURL,amazonReportOrigins,waveHelperOrigins,validRange,amazonDownloadName,amazonDownloadItem,waveDownloadURL,waveMailSearch,observeNativeDownload,findAmazonInbox,saveAmazonReport,saveWaveArchive} from './download-files.js';
import {amazonDownloadPage,waveExportPage,waveMailPage} from './download-pages.js';
import {loadLocalFeature,saveLocalFeature,loadSession} from './session.js';
import {exportUrlFor,onlyBusiness} from './workflow.js';
import {activity,paintActivity} from './activity.js';
const $=id=>document.getElementById(id),mode=document.body.dataset.helper,real=!!globalThis.chrome?.runtime?.id,origins=mode==='amazon'?amazonReportOrigins:waveHelperOrigins;
let shared={version:1,data:null,inbox:null},state={version:1,job:null,start:'2019-09-01',end:'',business:'',exportURL:'',mailbox:'',mailIndex:0},busy=false,connected=false,generation=0,diagnostics=null,pendingBytes=null,pendingBusiness=null,pendingFolder=null,exportPages={},settings={};
const day=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const save=async()=>{await saveLocalFeature('downloads:folders',shared);await saveLocalFeature('downloads:'+mode,state);};
function controls(){if(mode==='amazon'){state.start=$('start').value;state.end=$('end').value;validRange(state.start,state.end);}else{state.business=$('business').value;state.exportURL=$('exportURL').value;state.mailbox=$('mailbox').value.trim();state.mailIndex=Number($('mailIndex').value);if(!exportUrlFor(state.business,{[state.business]:state.exportURL}))throw Error('Set a valid Wave export page for the selected business.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(state.mailbox))throw Error('Enter the mailbox that receives your Wave exports.');waveMailSearch(state.mailIndex);}}
function paint(){for(const id of ['connect','data','inbox','reset','diagnose','copy','run','stop','start','end','manual','tabs','open','tabsRefresh','history','personal','business','mailbox','exportURL','mailIndex','email','confirm'])if($(id))$(id).disabled=busy;$('manual').disabled=busy||!shared.data;const ready=real&&connected&&shared.data&&shared.inbox;$('run').disabled=busy||!ready;$('stop').disabled=!busy;$('reset').disabled=busy||!state.job;$('setup').textContent=!real?'Open this helper from the installed Chrome extension.':!connected?'Connect report access first.':!shared.data?'Choose your project data folder.':!shared.inbox?'Link Chrome’s download destination folder so completed files can be collected automatically.':'Ready · data folder and download folder linked.';$('progress').hidden=!busy;}
const guarded=fn=>async()=>{if(busy)return;busy=true;paint();const task=activity.begin('Preparing download helper');try{await fn();}catch(e){$('status').textContent=e.message;}finally{busy=false;task.finish();paint();}};
async function permissionFolder(folder,mode='read'){if(await folder.queryPermission({mode})!=='granted'&&await folder.requestPermission({mode})!=='granted')throw Error('Allow access to the selected folder to continue.');}
async function refreshTabs(){if(!real)return;connected=await chrome.permissions.contains({permissions:['downloads'],origins});if(mode!=='amazon'||!connected)return;const selected=$('tabs').value;$('tabs').replaceChildren();for(const tab of await chrome.tabs.query({url:amazonReportOrigins})){const u=new URL(tab.url);if(u.pathname!=='/b2b/aba/reports'||u.searchParams.get('reportType')!=='items_report_1')continue;const o=document.createElement('option');o.value=tab.id;o.textContent=tab.title||'Amazon Business Orders report';$('tabs').append(o);}if([...$('tabs').options].some(o=>o.value===selected))$('tabs').value=selected;}
async function open(url,active=false){const tabs=await chrome.tabs.query({url:url.split('#')[0].split('?')[0]+'*'});if(tabs.length===1){await chrome.tabs.update(tabs[0].id,{url,active});return tabs[0].id;}return (await chrome.tabs.create({url,active})).id;}
async function inject(tabId,func,request){const result=await chrome.scripting.executeScript({target:{tabId},world:'ISOLATED',func,args:[request]});if(!result[0]?.result)throw Error('No export controls were returned.');return result[0].result;}
$('connect').onclick=guarded(async()=>{if(!real)throw Error('Use the installed extension.');if(!await chrome.permissions.request({permissions:['downloads'],origins}))throw Error('Download helper access was not granted.');await refreshTabs();$('status').textContent='Connected. Link your project data folder and browser Downloads folder once.';});
$('data').onclick=guarded(async()=>{const folder=await showDirectoryPicker({id:'wave-data-downloads',mode:'readwrite',startIn:'desktop'});if(folder.name.toLowerCase()!=='data')throw Error('Choose the data folder in the correct wave-solver project.');if(state.job||pendingBytes)throw Error('Finish or reset the pending export before changing its destination.');shared.data=folder;await save();});
$('inbox').onclick=guarded(async()=>{shared.inbox=await showDirectoryPicker({id:'wave-browser-downloads',mode:'read',startIn:'downloads'});await save();$('status').textContent='Download folder linked. Chrome must save exports directly into this folder; if it asks where to save, choose this same folder.';});
$('reset').onclick=guarded(async()=>{state.job=null;pendingBytes=null;if($('confirmPanel'))$('confirmPanel').hidden=true;await save();$('status').textContent='Request checkpoint cleared. Saved files are preserved.';});
$('copy').onclick=guarded(async()=>{if(!diagnostics)throw Error('Read controls first.');await navigator.clipboard.writeText(JSON.stringify(diagnostics,null,2));$('status').textContent='Controls copied; signed URLs and mailbox details excluded.';});
$('stop').onclick=()=>{generation++;$('status').textContent='Stopping. The provider’s report may finish later; Resume collects it.';};
async function checkpoint(job){state.job={...state.job,...job};await save();}
async function collectAmazon(file){const result=await saveAmazonReport(shared.data,file,state.job||state);state.job=null;await save();$('result').textContent=result.path+' · '+result.orders+' orders / '+result.count+' source rows';$('status').textContent='Amazon report saved. Refresh data folder in the Command center.';}
async function collectWave(file,confirmed=false){const bytes=new Uint8Array(await file.arrayBuffer()),result=await saveWaveArchive(shared.data,bytes,{business:state.business,confirmed});if(result.needsConfirmation){pendingBytes=bytes;pendingBusiness=state.business;pendingFolder=shared.data;$('confirmPanel').hidden=false;$('confirmation').textContent=result.count+' transactions · Accounts: '+result.accounts.join(', ')+'. This export does not match enough existing history to confirm the business automatically.';$('status').textContent='ZIP validated. Confirm its business before saving.';return;}state.job=null;pendingBytes=null;$('confirmPanel').hidden=true;await save();$('result').textContent=result.path+' · '+result.count+' unique transactions · Previous history preserved';$('status').textContent='Wave export saved. Refresh data folder in the Command center.';}
$('manual').onchange=guarded(async()=>{const file=$('manual').files?.[0];if(!file)return;if(mode==='amazon')controls();else{state.business=$('business').value;if(!/^[0-9a-f-]{36}$/i.test(state.business))throw Error('Select the Wave business for this ZIP.');}await permissionFolder(shared.data,'readwrite');if(mode==='amazon')await collectAmazon(file);else await collectWave(file);$('manual').value='';});
if(mode==='amazon'){
 $('end').value=day();$('open').onclick=guarded(async()=>{if(!real)throw Error('Use the extension.');await open(amazonReportURL,true);await refreshTabs();});$('tabsRefresh').onclick=guarded(refreshTabs);$('history').onclick=guarded(()=>inject(Number($('tabs').value),amazonDownloadPage,{action:'history'}));$('personal').onclick=guarded(async()=>{if(!real)throw Error('Use the extension.');await chrome.tabs.create({url:amazonPrivacyURL,active:true});});
 $('diagnose').onclick=guarded(async()=>{diagnostics=await inject(Number($('tabs').value),amazonDownloadPage,{action:'read'});$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);});
}else{
 $('open').onclick=guarded(async()=>{controls();await save();await open(state.exportURL,true);});$('email').onclick=guarded(async()=>{controls();await save();await open(waveMailSearch(state.mailIndex),true);});
 $('business').onchange=()=>{$('exportURL').value=exportPages[$('business').value]||'';};
 $('diagnose').onclick=guarded(async()=>{controls();const tabId=await open(state.exportURL);diagnostics=await inject(tabId,waveExportPage,{action:'read',exportURL:state.exportURL});$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);});
 $('confirm').onclick=guarded(async()=>{if(!pendingBytes)throw Error('Read the downloaded ZIP again.');if($('business').value!==pendingBusiness||state.business!==pendingBusiness||shared.data!==pendingFolder)throw Error('Restore the business and destination that were selected when this ZIP was read.');await collectWave(new File([pendingBytes],'wave-export.zip'),true);});
}
$('run').onclick=async()=>{if(busy)return;const runId=++generation;busy=true;paint();const task=activity.begin(mode==='amazon'?'Collecting Amazon report':'Collecting Wave export');try{controls();if(!real||!connected||!shared.data||!shared.inbox)throw Error('Finish the connection and folder setup first.');await permissionFolder(shared.data,'readwrite');await permissionFolder(shared.inbox);await save();await paintActivity();const current=()=>generation===runId,progress=message=>{$('status').textContent=message;task.update({detail:message});};
 if(mode==='amazon'){
  const range=validRange(state.start,state.end);if(state.job&&(state.job.start!==range.start||state.job.end!==range.end))throw Error('A different range is pending. Resume it or explicitly reset its checkpoint first.');if(state.job){const found=await findAmazonInbox(shared.inbox,state.job);if(found){await collectAmazon(found);return;}}
  const tabId=Number($('tabs').value);if(!tabId)throw Error('Open Amazon Business reports and refresh report tabs.');await inject(tabId,amazonDownloadPage,{action:'read'});
  const isNew=!state.job;if(isNew){await checkpoint({...range,requestedAt:new Date().toISOString(),phase:'requested'});if(!current()){state.job=null;await save();throw Error('Stopped before generating an Amazon report.');}}
  const result=await observeNativeDownload({downloads:chrome.downloads,inbox:shared.inbox,current,accept:item=>amazonDownloadItem(item,range),resumeId:state.job.downloadId??null,checkpoint,onProgress:progress,trigger:isNew?async()=>{progress('Setting dates, submitting and generating the Amazon report…');const response=await inject(tabId,amazonDownloadPage,{action:'generate',...range});if(response.notSubmitted){state.job=null;await save();throw Error(response.message);}}:null});if(result.waiting)progress('Amazon is still generating. Resume later or open Download history and download the report there. Nothing was regenerated.');else if(current())await collectAmazon(result.file);
 }else{
  if(state.job&&(state.job.business!==state.business||state.job.exportURL!==state.exportURL||state.job.mailbox!==state.mailbox||state.job.mailIndex!==state.mailIndex))throw Error('The pending export belongs to different business/mailbox settings. Restore them before resuming.');
  if(state.job?.downloadId!==undefined){const local=await observeNativeDownload({downloads:chrome.downloads,inbox:shared.inbox,current,resumeId:state.job.downloadId,checkpoint,onProgress:progress,accept:item=>/\.zip$/i.test(String(item.filename||''))&&waveDownloadURL(item.finalUrl||item.url)});if(local.file){await collectWave(local.file);return;}progress('The saved ZIP download is still pending. Retry its download or Resume later.');return;}
  if(!state.job){const tabId=await open(state.exportURL);let info=null;for(let i=0;i<30&&current();i++){try{info=await inject(tabId,waveExportPage,{action:'read',exportURL:state.exportURL});if(info.accountingExportButtons)break;}catch{}await new Promise(r=>setTimeout(r,300));}if(!current())throw Error('Stopped before requesting an export.');if(!info?.accountingExportButtons)throw Error('Export page is not ready or the Accounting CSV button is unrecognized. Read controls first.');await checkpoint({business:state.business,exportURL:state.exportURL,mailbox:state.mailbox,mailIndex:state.mailIndex,requestedAt:new Date().toISOString(),phase:'requested'});if(!current()){state.job=null;await save();throw Error('Stopped before requesting a Wave export.');}const response=await inject(tabId,waveExportPage,{action:'request',exportURL:state.exportURL});if(response.notSubmitted){state.job=null;await save();throw Error(response.message);}}
  progress('Looking for the new Wave export email…');const tabId=await open(waveMailSearch(state.mailIndex)),mail={mailbox:state.mailbox,mailIndex:state.mailIndex,requestedAt:state.job.requestedAt};let ready=false;
  for(let attempt=0;attempt<60&&current();attempt++){try{const info=await inject(tabId,waveMailPage,{action:'read',...mail});if(info.readyLinks){ready=true;break;}if(info.searchPage)await inject(tabId,waveMailPage,{action:'openLatest',...mail});else if(attempt%5===4)await chrome.tabs.update(tabId,{url:waveMailSearch(state.mailIndex),active:false});}catch(e){if(attempt>2)throw e;}await new Promise(r=>setTimeout(r,1000));}
  if(!current())throw Error('Stopped. Export request saved for Resume.');if(!ready){progress('Wave’s export email is still pending. Find Wave export email or Resume later; no duplicate was requested.');return;}
  const result=await observeNativeDownload({downloads:chrome.downloads,inbox:shared.inbox,current,resumeId:state.job.downloadId??null,checkpoint,onProgress:progress,accept:item=>/\.zip$/i.test(String(item.filename||''))&&waveDownloadURL(item.finalUrl||item.url),trigger:state.job.downloadId?null:async()=>{const clicked=await inject(tabId,waveMailPage,{action:'download',...mail});if(!clicked.clicked)throw Error('The fresh Wave export link is no longer available.');}});if(result.waiting)progress('Waiting for the Wave ZIP download. Resume collects it when complete.');else if(current())await collectWave(result.file);
 }
 }catch(e){$('status').textContent='Stopped: '+e.message;}finally{busy=false;task.finish();paint();}};
try{settings=await import('./settings.local.js');exportPages=settings.exportPages||{};}catch{}
try{const folders=await loadLocalFeature('downloads:folders'),saved=await loadLocalFeature('downloads:'+mode);if(folders?.version===1)shared=folders;if(saved?.version===1)state=saved;}catch(e){$('status').textContent='Saved setup could not be restored.';}
if(mode==='amazon'){$('start').value=state.start;$('end').value=state.end||day();}else{const current=real?onlyBusiness(await chrome.tabs.query({url:'https://next.waveapps.com/*'})):null,session=await loadSession();const businesses=[...new Set([current,session?.business,...Object.keys(exportPages)].filter(Boolean))];for(const business of businesses){const o=document.createElement('option');o.value=business;o.textContent=business;o.textContent=business===current?'Current Wave business':business===session?.business?'Saved Wave business':business;$('business').append(o);}$('business').value=state.business||current||session?.business||businesses[0]||'';$('exportURL').value=state.exportURL||exportPages[$('business').value]||'';$('mailbox').value=state.mailbox||settings.waveExportMailbox||'';$('mailIndex').value=state.mailbox?state.mailIndex:settings.waveExportGmailIndex??0;}
await refreshTabs();paint();

if(mode==='wave'&&$('configuration'))$('configuration').open=!$('exportURL').value||!$('mailbox').value;
