import {historySuggestions,acceptHistoryRules} from './history.js';
const make=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
const money=c=>'$'+(c/100).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
export function installHistoryReview({getState,accept,prepare}) {
  const $=id=>document.getElementById(id),chosen=new Map(),selected=new Set();let items=[],visible=[],cache=null,scope=null,limit=40,busy=false;
  const toolbar=make('div',undefined,'bar history-selection'),select=make('button','Select visible suggestions','secondary'),clear=make('button','Clear history selection','secondary'),add=make('button','Add selected rules'),count=make('span');
  const status=make('p');status.setAttribute('role','status');const filter=make('select');filter.setAttribute('aria-label','History suggestion scope');for(const [value,text] of [['all','All repeated merchants'],['backlog','In the last Not Reviewed scan'],['consistent','Consistent history'],['mixed','Conflicting history']]){const o=make('option',text);o.value=value;filter.append(o);}
  const more=make('button','Show more historical merchants','secondary');toolbar.append(select,clear,add,count);$('historySearch').after(filter,toolbar,status);$('historyRows').closest('.table-wrap').after(more);
  function update(){count.textContent=selected.size+' selected';add.disabled=busy || !selected.size;select.disabled=busy || !getState().business || !visible.some(g=>chosen.get(g.id));clear.disabled=busy || !selected.size;filter.disabled=busy;more.disabled=busy;}
  function refresh(){const s=getState();if(!s.dataset){$('history').hidden=true;return;} $('history').hidden=false;
    if(scope?.dataset!==s.dataset || scope?.business!==s.business){selected.clear();chosen.clear();limit=40;scope={dataset:s.dataset,business:s.business};}
    if(!cache || cache.dataset!==s.dataset || cache.rules!==s.rules || cache.signature!==JSON.stringify(s.rules) || cache.pack!==s.pack || cache.report!==s.report || cache.from!==s.from){items=historySuggestions(s.dataset.transactions,s.rules,3,s.business,{families:s.pack?.proposals.map(p=>p.rule),backlogIds:s.report?.records.map(r=>r.id),from:s.from});cache={dataset:s.dataset,rules:s.rules,signature:JSON.stringify(s.rules),pack:s.pack,report:s.report,from:s.from};
      for(const g of items)if(!chosen.has(g.id))chosen.set(g.id,g.category);for(const id of selected)if(!items.some(g=>g.id===id))selected.delete(id);
    }
    const q=$('historySearch').value.toLowerCase(),matches=items.filter(g=>(filter.value!=='backlog'||g.backlog>0)&&(filter.value!=='consistent'||g.category)&&(filter.value!=='mixed'||g.mixed)&&[g.merchant,...g.aliases,...g.distribution.map(c=>c.category)].join(' ').toLowerCase().includes(q));visible=matches.slice(0,limit);
    $('historyInfo').textContent='Showing '+visible.length+' of '+matches.length+' merchants. Full history supports evidence; '+s.from+' onward supports the working queue. '+(s.report?'Last scan: '+s.report.capturedAt+'.':'Collect Not Reviewed transactions to prioritize remaining purchases.');
    const wrap=$('historyRows').closest('.table-wrap'),scroll=wrap.scrollTop;$('historyRows').replaceChildren();
    for(const g of visible){const row=make('tr');row.classList.toggle('history-selected',selected.has(g.id));const merchant=make('td'),label=make('label',undefined,'history-choice'),check=make('input');check.type='checkbox';check.setAttribute('aria-label','Select history rule '+g.merchant);check.checked=selected.has(g.id);check.disabled=busy || !chosen.get(g.id) || !s.business;label.append(check,make('strong',g.merchant));merchant.append(label,make('small',g.earliest+' to '+g.latest+' · '+g.accounts.length+(g.accounts.length===1?' account':' accounts')));
      const evidence=make('td',g.count+' purchases · '+money(g.outgoingCents));evidence.append(make('small',g.uncovered+' uncovered · '+g.working+' working period · '+g.backlog+' in last scan'));
      const categoryCell=make('td'),picker=make('select');picker.setAttribute('aria-label','Category for history rule '+g.merchant);picker.disabled=busy;const placeholder=make('option','Choose a category');placeholder.value='';picker.append(placeholder);for(const c of s.categories.filter(c=>! /^(?:Uncategorized |Personal Uncategorized)/i.test(c))){const o=make('option',c);o.value=c;picker.append(o);}picker.value=chosen.get(g.id)||'';
      categoryCell.append(picker,make('small',g.reason));if(g.recommendedCategory && !g.category)categoryCell.append(make('small','2023–2024 recommendation: '+g.recommendedCategory));
      const details=make('details'),summary=make('summary','Evidence and aliases');details.append(summary);details.ontoggle=()=>{if(!details.open || details.children.length>1)return;details.append(make('p',g.distribution.map(c=>c.category+': '+c.count).join('; ') || 'No established category'),make('p','2023–2024: '+(g.recentDistribution.map(c=>c.category+': '+c.count).join('; ')||'No categorized examples')),make('p','Year-by-year: '+g.byYear.map(y=>y.year+' — '+Object.entries(y.categories).map(([c,n])=>c+': '+n).join('; ')).join(' · ')),make('p','Weighted historical leader: '+(g.weightedCategory || 'Unknown')+'. Weights: 2023–2024 ×5, 2025 onward ×2, earlier ×1. Purpose still needs confirmation.'),make('p','Exact aliases: '+g.aliases.join(' · ')),make('p',g.incoming+' incoming records and '+g.excluded+' other unsafe records excluded. Existing different categories are protected. Reviewed status is unknown.'));};categoryCell.append(details);
      const actions=make('td'),button=make('button','Prepare individually','secondary');button.disabled=busy;button.onclick=()=>prepare(g,chosen.get(g.id)||'');actions.append(button);
      check.onchange=()=>{if(check.checked)selected.add(g.id);else selected.delete(g.id);row.classList.toggle('history-selected',check.checked);update();};picker.onchange=()=>{chosen.set(g.id,picker.value);if(!picker.value){selected.delete(g.id);check.checked=false;row.classList.remove('history-selected');}check.disabled=busy || !picker.value || !s.business;update();};row.append(merchant,evidence,categoryCell,actions);$('historyRows').append(row);
    }
    wrap.scrollTop=scroll;more.hidden=matches.length<=limit;update();
  }
  select.onclick=()=>{for(const g of visible)if(chosen.get(g.id))selected.add(g.id);refresh();};clear.onclick=()=>{selected.clear();refresh();};more.onclick=()=>{limit+=40;refresh();};filter.onchange=()=>{limit=40;refresh();};$('historySearch').oninput=()=>{limit=40;refresh();};
  add.onclick=async()=>{if(busy)return;busy=true;status.textContent='Saving selected rules…';refresh();try{const s=getState();const result=acceptHistoryRules(items,[...selected].map(id=>({id,category:chosen.get(id)})),s.rules,{business:s.business,categories:s.categories,transactions:s.dataset.transactions});await accept(result.rules);selected.clear();status.textContent=result.added.length+' rules added to Current rules in one save. Nothing changed in Wave.';}catch(e){status.textContent='Nothing added: '+e.message;}finally{busy=false;cache=null;refresh();}};
  return {render:refresh};
}
