import {activity,paintActivity} from './activity.js';
import {compareCollectedRows,compareInspectedRecord} from './inspection.js';
import {sourceHash} from './rule-pack.js';
import {showUsageSection} from './workspace-ui.js';
export function installBulkInspector({getState,read,inspect,onChange=()=>{}}){
 const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const section=make('section'),fold=make('details');fold.id='bulkInspector';fold.className='step';const heading=make('summary','Compare with your accounting export');heading.setAttribute('role','heading');heading.setAttribute('aria-level','2');const body=make('div');body.className='step-body';fold.append(heading,body);section.append(fold);document.getElementById('liveList').parentElement.after(section);
 const intro=make('p','The quick comparison checks every collected row against accounting.csv. Inspect all opens transaction dialogs in a background tab to also read direction, full category and reviewed status. Both are read-only; neither applies a plan.');
 const bar=make('div');bar.className='bar';const run=make('button','Inspect all collected records'),stop=make('button','Stop after current record'),refresh=make('button','Compare collected rows');refresh.className=stop.className='secondary';bar.append(refresh,run,stop);
 const status=make('p');status.setAttribute('role','status');const cards=make('div');cards.className='inspection-counts';const filter=make('select');filter.setAttribute('aria-label','Inspection results');for(const [v,label] of [['','All results'],['changed','Changed from CSV'],['needs-details','Needs closer inspection'],['missing-export','Missing from CSV'],['inspected-match','Dialog fields match'],['list-match','List fields match']]){const o=make('option',label);o.value=v;filter.append(o);}
 const results=make('div'),download=make('button','Download inspection report');download.className='secondary';body.append(intro,bar,status,cards,filter,results,download);
 let saved={},active=null,running=false,stopped=false,limit=50,cache=null;
 const context=()=>{const s=getState();return {business:s.business,csv:s.csvText,report:s.report,from:s.workFrom};};
 const same=(a,b)=>a && b && a.business===b.business && a.csv===b.csv && a.report?.capturedAt===b.report?.capturedAt && a.from===b.from;
 function rows(){const s=getState(),c=context();if(!same(cache?.context,c)){cache={context:c,rows:compareCollectedRows(s.report,s.dataset?.transactions,{business:s.business,from:s.workFrom})};}return cache.rows.map(row=>same(active?.context,c)&&active.records[row.id]?active.records[row.id]:row);}
 function render(){const s=getState(),all=rows(),count=key=>all.filter(r=>r.state===key).length;const savedCount=same(active?.context,context())?Object.keys(active.records).length:0;run.textContent=savedCount?'Resume or recheck inspection':'Inspect all collected records';run.disabled=running || s.busy || !s.extensionMode || s.sample || !s.dataset || !s.report || s.report.running || s.report.completeness!=='count-confirmed';refresh.disabled=running || !s.dataset || !s.report;stop.hidden=!running;stop.disabled=stopped;download.disabled=!all.length;
 if(!running)status.textContent=!s.dataset?'Import accounting.csv first.':!s.report?'Collect Not Reviewed transactions first.':(same(active?.context,context())?Object.keys(active.records).length+' dialog inspections saved. ':'')+'Quick comparison: '+all.length+' collected rows. '+(s.report.completeness!=='count-confirmed'?'Collection is partial; complete it before bulk inspection.':'Use Inspect all for a full dialog check.');
 cards.replaceChildren();for(const [key,label] of [['list-match','List fields match'],['inspected-match','Dialog fields match'],['changed','Changed'],['needs-details','Need details'],['missing-export','Missing export']]){const card=make('button');card.className='inspection-count';card.append(make('strong',String(count(key))),make('span',label));card.onclick=()=>{filter.value=key;limit=50;render();};cards.append(card);}
 results.replaceChildren();const shown=all.filter(r=>!filter.value || r.state===filter.value);for(const row of shown.slice(0,limit)){const card=make('details');card.className='inspection-row';card.dataset.state=row.state;card.append(make('summary',(row.description || 'Unresolved transaction')+' · '+row.state.replaceAll('-',' ')),make('p',(row.date || '')+' · '+(row.account || '')+' · '+row.reason));for(const c of row.checks.filter(c=>c.state!=='Match'))card.append(make('p',c.field+': CSV '+c.exported+' → Wave '+c.live+' ('+c.state+')'));const t=s.queue?.find(t=>t.id===row.id);if(t){const open=make('button','Review this transaction');open.className='secondary';open.onclick=()=>inspect(t);card.append(open);}results.append(card);}if(shown.length>limit){const more=make('button','Show more inspection results');more.onclick=()=>{limit+=50;render();};results.append(more);}}
 async function persist(){if(getState().extensionMode && active){saved[active.context.business]={hash:active.hash,capturedAt:active.context.report.capturedAt,from:active.context.from,records:active.records};await chrome.storage.local.set({solverInspectionReports:saved});}}
 refresh.onclick=async()=>{const task=activity.begin('Comparing collected rows with accounting.csv');try{await paintActivity();cache=null;render();onChange();}finally{task.finish();}};
 run.onclick=async()=>{if(run.disabled || running)return;running=true;stopped=false;const s=getState(),c=context(),task=activity.begin('Inspecting collected Wave records',{priority:10});render();onChange();try{await paintActivity();const hash=await sourceHash(c.csv);if(!same(active?.context,c))active={context:c,hash,records:{}};const byId=new Map(s.dataset.transactions.map(t=>[t.id,t]));const ids=[...new Set(rows().filter(r=>r.id && r.date>=s.workFrom && byId.has(r.id) && r.state!=='before-period').map(r=>r.id))];let pending=ids.filter(id=>!active.records[id] || active.records[id].state==='needs-details');if(!pending.length){active.records={};pending=ids;}task.update({total:ids.length,completed:ids.length-pending.length});
 for(const id of pending){if(stopped)break;if(!same(c,context()))throw Error('Session or collection changed. Inspect the new collection separately.');const t=byId.get(id);status.textContent=Object.keys(active.records).length+' of '+ids.length+' inspected · '+t.description;task.update({detail:t.description});try{const snapshot=await read(t,()=>same(c,context()));if(!same(c,context()))throw Error('Session changed.');if(!snapshot)throw Error('No dialog details returned.');active.records[id]=compareInspectedRecord(t,snapshot,c.business);}catch(e){if(!same(c,context()))throw e;active.records[id]={id,date:t.date,description:t.description,account:t.primary?.account,level:'dialog',state:'needs-details',checks:[],reviewed:'Unknown',reason:e.message};}task.update({completed:ids.length-pending.length+pending.indexOf(id)+1});if(Object.keys(active.records).length%10===0)await persist();}
 await persist();status.textContent=(stopped?'Inspection stopped. ':'Inspection complete. ')+Object.keys(active.records).length+' of '+ids.length+' records inspected. Nothing edited in Wave.';
 }catch(e){status.textContent='Inspection stopped: '+e.message;}finally{const message=status.textContent;running=false;render();status.textContent=message;task.finish(message);onChange();}};
 stop.onclick=()=>{stopped=true;stop.disabled=true;};filter.onchange=()=>{limit=50;render();};download.onclick=()=>{const s=getState(),blob=new Blob([JSON.stringify({format:'wave-solver-inspection',version:1,business:s.business,collectionCapturedAt:s.report?.capturedAt,rows:rows()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download='wave-inspection.local.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const ready=(async()=>{if(getState().extensionMode)saved=(await chrome.storage.local.get('solverInspectionReports')).solverInspectionReports || {};})();
 return {ready,render,reviewedIds(){if(!same(active?.context,context()))return new Set();return new Set(Object.values(active.records).filter(r=>r.reviewed==='Reviewed' && !r.problems?.length && r.checks?.some(c=>c.field==='Transaction ID' && c.state==='Match')).map(r=>r.id));},async restore(){await ready;const c=context(),previous=saved[c.business];if(previous && c.csv && previous.capturedAt===c.report?.capturedAt && previous.from===c.from && previous.hash===await sourceHash(c.csv))active={context:c,hash:previous.hash,records:previous.records};render();},busy:()=>running};
}
