// Fictional Chrome bindings for the local integration preview only.
async function storage(key, value) {
 const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('wave-solver-local',1);r.onupgradeneeded=()=>r.result.createObjectStore('session');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 try {return await new Promise((resolve,reject)=>{const tx=db.transaction('session',value?'readwrite':'readonly'),store=tx.objectStore('session');let result;const r=store.get('fictional-chrome-storage');r.onsuccess=()=>{const saved=r.result || {};if(value){Object.assign(saved,value);store.put(saved,'fictional-chrome-storage');}result=Array.isArray(key)?Object.fromEntries(key.map(k=>[k,saved[k]])):key?{[key]:saved[key]}:saved;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}finally{db.close();}
}
const {loadSession}=await import('./session.js');const {importAccounting}=await import('./model.js');
const saved=await loadSession(),fictional=importAccounting(saved.csvText).transactions,virtualTabs=new Map();let virtualId=100;
const transferOutcome=document.createElement('select');transferOutcome.setAttribute('aria-label','Fictional transfer outcome');for(const value of ['already-linked','success','lost-response','missing-incoming','incoming-unreviewed','changed-amount','first-changed','selection-aborted']){const option=document.createElement('option');option.value=value;option.textContent=value;transferOutcome.append(option);}transferOutcome.value='success';document.querySelector('main').prepend(transferOutcome);const resetTest=document.createElement('button');resetTest.textContent='Reset fictional transfer attempts';resetTest.onclick=async()=>{await storage(null,{solverEditReceipts:{},fictionalTransfers:{}});location.reload();};document.querySelector('main').prepend(resetTest);
const expenseOutcome=document.createElement('select');expenseOutcome.setAttribute('aria-label','Fictional expense outcome');for(const value of ['success','review-after-save','changed-expense','review-updates','lost-response']){const option=document.createElement('option');option.value=value;option.textContent=value;expenseOutcome.append(option);}document.querySelector('main').prepend(expenseOutcome);
const seedExpenses=document.createElement('button');seedExpenses.textContent='Seed approved fictional expense rules';seedExpenses.onclick=async()=>{await storage(null,{solverRules:[{name:'Fictional Cloud',aliases:['Example Cloud'],category:'Software'},{name:'Fictional fuel',aliases:['Chevron'],category:'Equipment Fuel — Diesel, Gas, Machinery Fuel'}],solverEditReceipts:{},fictionalTransfers:{}});location.reload();};document.querySelector('main').prepend(seedExpenses);
const expenseLog=document.createElement('p');expenseLog.id='expenseTestLog';document.querySelector('main').prepend(expenseLog);
window.chrome={runtime:{id:'fictional-local-test'},storage:{local:{get:key=>storage(key),set:value=>storage(null,value)}},tabs:{query:async()=>[...virtualTabs.values()],getCurrent:async()=>({windowId:1}),create:async options=>{const tab={...options,id:++virtualId,status:'complete'};virtualTabs.set(tab.id,tab);return tab;},get:async id=>{if(!virtualTabs.has(id))throw Error('Only fictional tabs are available.');return virtualTabs.get(id);},update:async(id,options)=>{const tab=virtualTabs.get(id);Object.assign(tab,options,{status:'complete'});return tab;},reload:async()=>{},onRemoved:{addListener(){}},onUpdated:{addListener(){}}},scripting:{executeScript:async ({target,func,args})=>{if(func.name==='waveListScan'){
 const value=await storage(null);if(args[0].action!=='start')return [{result:value.fictionalLiveList}];
 const records=fictional.filter(t=>t.id!=='1000000000000000001' && t.direction==='out' && value.fictionalTransfers?.[t.id]?.reviewed!=='Reviewed').map(t=>({id:t.id,identity:'Wave transaction ID',date:t.date,description:t.description,account:t.primary.account,category:t.categories[0],amountText:(t.amount/100).toFixed(2),amountCents:t.amount,reviewed:'Not reviewed',reviewEvidence:'Fictional explicit row status',sourceFilter:'NOT_VERIFIED',uncategorized:/^Uncategorized/.test(t.categories[0])}));
 const report={format:'wave-solver-live-list',version:1,business:saved.business,filter:'NOT_VERIFIED',filterChipObserved:true,records,running:false,status:'Complete fictional list',capturedAt:new Date().toISOString(),expectedTotal:records.length,completeness:'count-confirmed',problems:[],rowDiagnostics:[]};await storage(null,{fictionalLiveList:report});return [{result:report}];
 }const tab=virtualTabs.get(target.tabId),id=tab.url.split('/').pop(),t=fictional.find(t=>t.id===id);if(!t)throw Error('Only fictional records are available.');const state=await storage(null),ledger=state.fictionalTransfers || {};
if(func.name==='editWaveTransaction'){if(expenseOutcome.value==='review-updates' && t.id==='1000000000000000004')throw Error('Review updates record must remain unedited.');if(transferOutcome.value==='already-linked')throw Error('Completed fictional transfers must never be edited.');const request=args[0];if(request.openTransferMenu)return [{result:{menuOpened:true,saveAttempted:false}}];if(request.reviewOnly){expenseLog.textContent+=' Review-only '+t.id+';';ledger[t.id]={...ledger[t.id],reviewed:'Reviewed'};await storage(null,{fictionalTransfers:ledger});return [{result:{saveAttempted:true,reviewRequested:true,stage:'review'}}];}if(!request.transfer){expenseLog.textContent+=' Category change '+t.id+';';ledger[t.id]={category:request.category,reviewed:expenseOutcome.value==='review-after-save'?'Unknown':'Reviewed'};await storage(null,{fictionalTransfers:ledger});if(expenseOutcome.value==='lost-response')return [];return [{result:{saveAttempted:true,reviewRequested:expenseOutcome.value!=='review-after-save',stage:'save'}}];}if(transferOutcome.value==='selection-aborted')return [{result:{saveAttempted:true,stage:'existing transfer selection',problem:'Fictional old-label selection failure',selectedCategory:'Transfer to Fictional Credit Card - Oct 1, 2026 - Payment thank you'}}];ledger[t.id]={category:request.category,reviewed:'Reviewed'};if(transferOutcome.value!=='missing-incoming')ledger[request.transfer.id]={category:'Transfer from '+t.primary.account,reviewed:transferOutcome.value==='incoming-unreviewed'?'Unknown':'Reviewed'};await storage(null,{fictionalTransfers:ledger});if(transferOutcome.value==='lost-response')return [];return [{result:{saveAttempted:true,reviewRequested:true,stage:'save'}}];}
if(func.name==='readTransferMenu'){const incoming=fictional.find(x=>x.direction==='in' && x.amount===t.amount);return [{result:{format:'wave-solver-transfer-menu',version:1,identity:{business:saved.business,transaction:t.id},matchingGroups:1,createGroups:1,matchingOptions:[{text:incoming.primary.account+' - '+new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(incoming.date+'T00:00:00Z'))+' - '+incoming.description,transactionId:incoming.id}],createOptions:[{text:'Fictional new transfer account'}],menuHtml:['<div>Fictional menu only</div>'],problems:[]}}];}return [{result:{identity:{business:saved.business,transaction:t.id},fields:{date:t.date,description:t.description,account:t.primary.account,amount:((t.amount+((expenseOutcome.value==='changed-expense' && t.id==='1000000000000000004')?1:0)+((transferOutcome.value==='changed-amount' || (transferOutcome.value==='first-changed' && t.amount===8700)) && t.direction==='in'?1:0))/100).toFixed(2),type:t.direction==='out'?'Withdrawal':'Deposit',category:ledger[t.id]?.category || (transferOutcome.value==='already-linked'?(t.direction==='out'?'Transfer to Fictional Credit Card':'Transfer from Fictional Checking'):t.categories[0])},reviewed:ledger[t.id]?.reviewed || (transferOutcome.value==='already-linked'?'Reviewed':transferOutcome.value==='selection-aborted'?'Unknown':t.direction==='in'?'Reviewed':'Unknown'),problems:[],controls:expenseOutcome.value==='review-updates' && t.id==='1000000000000000004'?['Review updates','Save','Cancel']:[(ledger[t.id]?.reviewed==='Reviewed' || (transferOutcome.value!=='selection-aborted' && !ledger[t.id] && t.direction==='in'))?'Reviewed':'Mark as reviewed'],capturedAt:new Date().toISOString()}}];}}};
document.addEventListener('click',event=>{if(event.target.tagName==='BUTTON' && event.target.textContent==='Accept rule')document.body.dataset.acceptScrollBefore=String(window.scrollY);},true);
const oldPreflight=document.createElement('button');oldPreflight.textContent='Seed stopped expense preflight';oldPreflight.onclick=async()=>{const t=fictional.find(t=>t.id==='1000000000000000004');const originalSnapshot={identity:{business:saved.business,transaction:t.id},fields:{date:t.date,description:t.description,account:t.primary.account,amount:(t.amount/100).toFixed(2),type:'Withdrawal',category:t.categories[0]},reviewed:'Unknown',controls:['Review updates'],problems:[]};await storage(null,{solverEditReceipts:{[saved.business+':'+t.id]:{category:'Software',saveAttempted:true,categoryVerified:false,reviewAttempted:true,stage:'expense-edit',originalSnapshot,editOutcome:{stage:'preflight',saveAttempted:false,problem:'Cannot identify a reviewed-state control.'}}},fictionalTransfers:{}});location.reload();};document.querySelector('main').prepend(oldPreflight);
await import('./app.js');
