// Fictional Chrome bindings for the local integration preview only.
async function storage(key, value) {
 const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('wave-solver-local',1);r.onupgradeneeded=()=>r.result.createObjectStore('session');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 try {return await new Promise((resolve,reject)=>{const tx=db.transaction('session',value?'readwrite':'readonly'),store=tx.objectStore('session');let result;const r=store.get('fictional-chrome-storage');r.onsuccess=()=>{const saved=r.result || {};if(value){Object.assign(saved,value);store.put(saved,'fictional-chrome-storage');}result=key?{[key]:saved[key]}:saved;};tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}finally{db.close();}
}
const {loadSession}=await import('./session.js');const {importAccounting}=await import('./model.js');
const saved=await loadSession(),fictional=importAccounting(saved.csvText).transactions,virtualTabs=new Map();let virtualId=100;
window.chrome={runtime:{id:'fictional-local-test'},storage:{local:{get:key=>storage(key),set:value=>storage(null,value)}},tabs:{query:async()=>[],getCurrent:async()=>({windowId:1}),create:async options=>{const tab={...options,id:++virtualId};virtualTabs.set(tab.id,tab);return tab;},get:async id=>{if(!virtualTabs.has(id))throw Error('Only fictional tabs are available.');return virtualTabs.get(id);},onRemoved:{addListener(){}},onUpdated:{addListener(){}}},scripting:{executeScript:async ({target})=>{const tab=virtualTabs.get(target.tabId),id=tab.url.split('/').pop(),t=fictional.find(t=>t.id===id);if(!t)throw Error('Only fictional records are available.');return [{result:{identity:{business:saved.business,transaction:t.id},fields:{date:t.date,description:t.description,account:t.primary.account,amount:(t.amount/100).toFixed(2),type:t.direction==='out'?'Withdrawal':'Deposit',category:t.categories[0]},reviewed:t.direction==='in'?'Reviewed':'Unknown',problems:[],controls:[],capturedAt:new Date().toISOString()}}];}}};
document.addEventListener('click',event=>{if(event.target.tagName==='BUTTON' && event.target.textContent==='Accept rule')document.body.dataset.acceptScrollBefore=String(window.scrollY);},true);
await import('./app.js');
