import {waveListScan} from './list-scan.js';
import {scopedListIds} from './list-view.js';
const business='11111111-1111-1111-1111-111111111111',mount=document.getElementById('fixture');
const records=Array.from({length:25},(_,i)=>({id:String(1000000000000000000n+BigInt(i+1)),date:'2026-10-01',description:'Fictional Merchant '+i,account:'Fictional Checking',category:i%3===0?'Uncategorized Expense':'Software',amountText:'$'+(i+1)+'.00',amountCents:(i+1)*100}));
function setup({unknown=false,total=true,stop=false,navigate=false,initialBottom=false}={}){
 mount.replaceChildren();const chip=document.createElement('span');chip.textContent='Not Reviewed';mount.append(chip);if(total){const count=document.createElement('p');count.textContent='Showing 1 of 25 transactions';mount.append(count);}
 const scroll=document.createElement('div');scroll.style.height='160px';scroll.style.overflowY='auto';const table=document.createElement('table');table.innerHTML='<thead><tr><th>Date</th><th>Description</th><th>Account</th><th>Category</th><th>Amount</th><th>Actions</th></tr></thead><tbody></tbody>';scroll.append(table);mount.append(scroll);let loaded=0,clicks=0,ticks=0;
 const known=records.map(r=>({...r}));if(unknown){for(const n of [17,18])known[n]={...known[n],description:'Identical merchant',amountCents:9900};}
 const append=()=>{for(let n=0;n<5 && loaded<25;n++,loaded++){const source=records[loaded],r=unknown && [17,18].includes(loaded)?{...source,description:'Identical merchant',amountText:'$99.00'}:source;const row=document.createElement('tr');if(!unknown || ![16,17,18].includes(loaded))row.dataset.transactionId=r.id;if(loaded===0)row.dataset.reviewed='false';if(loaded===1)row.dataset.reviewed='true';for(const value of [r.date,r.description,r.account,r.category,r.amountText]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}const cell=document.createElement('td'),edit=document.createElement('button');edit.textContent='Edit transaction';edit.onclick=()=>clicks++;cell.append(edit);row.append(cell);table.querySelector('tbody').append(row);}};
 append();if(initialBottom)scroll.scrollTop=scroll.scrollHeight;const fakeWindow={},fakeLocation={href:'https://next.waveapps.com/'+business+'/transactions?status=NOT_VERIFIED'};
 const context={document,window:fakeWindow,location:fakeLocation,getComputedStyle,wait:async()=>{ticks++;if(scroll.scrollTop+scroll.clientHeight>=scroll.scrollHeight-3 && loaded<25)append();if(stop && ticks===2)waveListScan({action:'stop'},context);if(navigate && ticks===2)fakeLocation.href='https://next.waveapps.com/'+business+'/transactions';await new Promise(resolve=>setTimeout(resolve,0));}};
 return {context,known,clicks:()=>clicks};
}
document.getElementById('run').onclick=async()=>{const output=document.getElementById('checks');output.replaceChildren();let failed=0,passed=0;
 async function check(name,options,assert){try{const f=setup(options);waveListScan({action:'start',business,known:f.known},f.context);await f.context.window.__dandelionWaveListScanV1.done;const r=waveListScan({action:'poll'},f.context);assert(r);if(f.clicks())throw Error('An edit control was clicked');passed++;const li=document.createElement('li');li.textContent='PASS '+name;output.append(li);}catch(e){failed++;const li=document.createElement('li');li.textContent='FAIL '+name+': '+e.message;output.append(li);}}
 const equal=(a,b)=>{if(a!==b)throw Error('Expected '+b+', got '+a);};
 await check('Lazy-loaded rows are all collected once without clicking edit controls',{},r=>{equal(r.records.length,25);equal(new Set(r.records.map(x=>x.id)).size,25);equal(r.completeness,'count-confirmed');equal(r.filterChipObserved,true);equal(r.records[0].reviewed,'Not reviewed');equal(r.records[1].reviewed,'Reviewed');equal(r.records[2].reviewed,'Unknown');});
 await check('Unique export identities resolve, duplicate full-field matches remain unresolved',{unknown:true},r=>{equal(r.records.length,25);equal(r.records.find(x=>x.description==='Fictional Merchant 16').identity,'Unique full-field export match');equal(r.records.filter(x=>x.description==='Identical merchant' && !x.id).length,2);equal(scopedListIds(r).size,22);});
 await check('Bottom stability does not invent an independent total',{total:false},r=>{equal(r.records.length,25);equal(r.expectedTotal,null);equal(r.completeness,'bottom-reached');});
 await check('A reused scrolled tab starts again from the top',{initialBottom:true},r=>{equal(r.records.length,25);equal(r.completeness,'count-confirmed');});
 await check('Stop retains partial collection',{stop:true},r=>{equal(r.running,false);if(!r.status.startsWith('Stopped') || r.records.length>=25)throw Error('Stop did not retain partial state');});
 await check('Changed filter stops collection rather than mixing pages',{navigate:true},r=>{equal(r.running,false);if(!r.status.includes('filter changed') || r.completeness==='count-confirmed')throw Error('Navigation did not stop capture');});
 try{const f=setup();f.context.location.href='https://next.waveapps.com/'+business+'/transactions';let rejected=false;try{waveListScan({business,action:'start'},f.context);}catch{rejected=true;}if(!rejected)throw Error('Missing NOT_VERIFIED filter accepted');passed++;const li=document.createElement('li');li.textContent='PASS Start requires the exact business list and filter';output.append(li);}catch(e){failed++;}
 document.getElementById('result').textContent=passed+' passed, '+failed+' failed';mount.replaceChildren();
};
