import {activity,paintActivity} from './activity.js';
import {debugSlot,debugLink,showWorkspace,showUsageSection} from './workspace-ui.js';
import {matchingRules,matchesDescription,nonPurchaseReason} from './rules.js';
import {expenseCandidates} from './expense-batch.js';
import {waveListScan} from './list-scan.js';
import {openBackgroundTab} from './workflow.js';
export function scopedListIds(report){return new Set((report?.records || []).filter(r=>typeof r.id==='string' && /^\d+$/.test(r.id) && r.reviewed!=='Reviewed' && ['Wave transaction ID','Unique full-field export match'].includes(r.identity)).map(r=>r.id));}
export function liveExpenseLinks(report,queue=[],transactions=[],from='2025-01-01'){
 const ids=scopedListIds(report),eligible=new Set(expenseCandidates(queue,ids).map(t=>t.id)),exports=new Set(transactions.map(t=>t.id));
 const result={known:0,needsReview:0,missingExport:0,completedPeriod:0,unresolved:0,reviewed:0};
 for(const row of report?.records || []){if(row.reviewed==='Reviewed'){result.reviewed++;continue;}if(!ids.has(row.id)){result.unresolved++;continue;}if(row.date && row.date<from){result.completedPeriod++;continue;}if(!exports.has(row.id)){result.missingExport++;continue;}if(eligible.has(row.id))result.known++;else result.needsReview++;}
 return result;
}
export function liveMerchantAudit(report,rules=[],transactions=[],queue=[],business=null,from='2025-01-01'){
 const byId=new Map(transactions.map(t=>[t.id,t])),plans=new Map(queue.map(t=>[t.id,t])),eligible=new Map(expenseCandidates(queue,scopedListIds(report)).map(t=>[t.id,t]));
 const rows=(report?.records || []).map(row=>{
  const t=byId.get(row.id),plan=plans.get(row.id),named=rules.filter(r=>(!r.business || r.business===business) && matchesDescription(row.description,r));
  const matches=t?matchingRules(row.description,rules,t,business):[],categories=[...new Set(matches.map(r=>r.category))];let state='unmatched',reason='No matching approved merchant rule.';
  if(!scopedListIds({records:[row]}).has(row.id)){state='blocked';reason=row.reviewed==='Reviewed'?'Already reviewed.':'No confirmed transaction identity.';}
  else if(row.date<from){state='blocked';reason='Before the working period.';}
  else if(!t){state='blocked';reason='Missing from accounting.csv; import a fresh export.';}
  else if(categories.length>1){state='blocked';reason='Conflicting approved categories.';}
  else if(matches.length && eligible.has(row.id) && eligible.get(row.id).proposed===categories[0] && row.description.trim()===t.description.trim()){state='known';reason='Approved rule; ready for live expense validation.';}
  else if(matches.length){state='blocked';reason=plan?.reason || 'Export and live merchant or transaction eligibility differ; inspect individually.';}
  else if(named.length){state='blocked';reason='Merchant alias matches, but the rule excludes this account, category, or transaction direction.';}
  const bucket=state==='known'?'approved_expense':!t?'missing_export':t.direction==='in'?'incoming_credit_or_income':nonPurchaseReason(t)?'payment_refund_or_nonpurchase':['Transfer candidate','Ambiguous transfer','Possible refund','Existing multi-account','Manual review'].includes(plan?.kind)?'transfer_refund_or_structure':state==='blocked'?'rule_scope_or_conflict':'purchase_needing_rule';
  if(state==='unmatched' && t){if(t.direction==='in')reason='Incoming credit or income; review payment/refund context separately.';else if(nonPurchaseReason(t))reason=nonPurchaseReason(t);else if(['Transfer candidate','Ambiguous transfer','Possible refund','Existing multi-account','Manual review'].includes(plan?.kind))reason=plan.reason;}
  return {id:row.id,state,reason,bucket,rules:matches.map(r=>({name:r.name,category:r.category})),aliasRules:named.map(r=>({name:r.name,category:r.category}))};
 });
 const buckets=rows.reduce((counts,row)=>(counts[row.bucket]=(counts[row.bucket]||0)+1,counts),{});
 return {buckets,business,rulesLoaded:rules.length,businessRules:rules.filter(r=>!r.business || r.business===business).length,rows,known:rows.filter(r=>r.state==='known').length,blocked:rows.filter(r=>r.state==='blocked').length,unmatched:rows.filter(r=>r.state==='unmatched').length};
}
export function installLiveList({getState,onRunning,onScope,refreshExpenses,refreshRules,showExpenses}){
 const make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
 const scanDebug=debugSlot('scanTools','Live list and merchant-rule diagnostics'),debugActions=make('div'),debugResults=make('div');debugActions.className='bar';scanDebug.append(debugActions,debugResults);
 const section=make('section'),fold=make('details');fold.className='step';fold.id='liveList';const summary=make('summary','Live Not Reviewed list');summary.setAttribute('role','heading');summary.setAttribute('aria-level','2');fold.append(summary);const body=make('div');body.className='step-body';
 const start=make('button','Collect Not Reviewed transactions'),stop=make('button','Stop collecting'),download=make('button','Download collected list'),copy=make('button','Copy list diagnostics');stop.className=download.className=copy.className='secondary';
 const checkRules=make('button','Check merchant rules'),copyRules=make('button','Copy rule-check diagnostics');copyRules.className='secondary';let checkingRules=false;
 const ruleView=make('select');ruleView.setAttribute('aria-label','Merchant rule results');for(const [value,text] of [['all','All merchant rule results'],['known','Matched known expenses'],['blocked','Matched or excluded — needs review'],['unmatched','No matching approved rule']]){const o=make('option',text);o.value=value;ruleView.append(o);}
 const view=make('select');view.setAttribute('aria-label','Collected transaction categories');for(const [value,text] of [['all','All Not Reviewed list rows'],['uncategorized','Uncategorized expenses and income']]){const o=make('option',text);o.value=value;view.append(o);}
 const scope=make('input');scope.type='checkbox';const scopeLabel=make('label',' Limit known-expense batches to identified rows from this collection');scopeLabel.prepend(scope);
 const prepare=make('button','Prepare known expenses');
 const expenses=make('button','Open known-expense runner');expenses.className='secondary';expenses.onclick=async()=>{if(busy || checkingRules || getState().busy)return;try{await refreshRules?.();}catch(e){status.textContent=e.message;return;}refreshExpenses();if(showExpenses){showExpenses();return;}showUsageSection('expenseBatch');const panel=document.getElementById('expenseBatch');panel.open=true;panel.scrollIntoView({block:'start',behavior:'smooth'});const heading=panel.querySelector('summary');heading.tabIndex=-1;heading.focus({preventScroll:true});};
 const ruleNotice=make('p');ruleNotice.setAttribute('role','status');
 const inspectCollection=make('button','Compare and inspect this collection');inspectCollection.className='secondary';inspectCollection.onclick=()=>showUsageSection('bulkInspector');const bar=make('div');bar.className='bar';bar.append(start,stop,inspectCollection);debugActions.append(copy,copyRules);const status=make('p');status.setAttribute('role','status');const results=make('div');
 const actions=make('div');actions.className='bar';actions.append(checkRules,prepare,expenses,debugLink('scanTools'));const filters=make('div');filters.className='bar';filters.append(ruleView,view);const options=make('details');options.className='scan-options';options.append(make('summary','More scan options'),actions,download,filters,scopeLabel);body.append(make('p','Collect the live list first. Then continue to Review rules to approve new matches. Collection does not edit Wave.'),bar,status,ruleNotice,results,options);fold.append(body);section.append(fold);document.getElementById('expenseBatch').parentElement.before(section);
 let reports={},scopes={},busy=false,tabId=null,limit=100,currentBusiness=null,listOpen=false;
 const selectedReport=()=>reports[getState().business];
 const applyScope=()=>{const business=getState().business;if(scopes[business]===undefined && reports[business]?.completeness==='count-confirmed')scopes[business]=true;scope.checked=!!scopes[business];onScope(scope.checked && reports[business]?scopedListIds(reports[business]):null);};
 function render(){const s=getState(),r=selectedReport();start.textContent=r?'Refresh Not Reviewed transactions':'Collect Not Reviewed transactions';if(currentBusiness!==s.business){currentBusiness=s.business;limit=100;listOpen=false;}applyScope();start.disabled=busy || s.busy || !s.extensionMode || s.sample || !s.business;stop.disabled=!busy;stop.hidden=!busy;download.disabled=copy.disabled=!r;scope.disabled=busy || !r || !scopedListIds(r).size;checkRules.disabled=busy || checkingRules || s.busy || !r;copyRules.disabled=!r;expenses.disabled=busy || checkingRules || s.busy;inspectCollection.hidden=!r;inspectCollection.disabled=busy || s.busy || !s.dataset || r?.running;const prepared=liveMerchantAudit(r,s.rules,s.dataset?.transactions,s.queue,s.business,s.workFrom);prepare.textContent='Prepare '+prepared.known+' known expenses';prepare.disabled=busy || checkingRules || s.busy || !prepared.known;
  results.replaceChildren();debugResults.replaceChildren();if(!r){status.textContent='No live list collected for this business.';return;}
  const links=liveExpenseLinks(r,s.queue,s.dataset?.transactions,s.workFrom);const connection=make('p');connection.setAttribute('role','status');connection.textContent=(scope.checked?'Linked to known expenses: ':'Available to link: ')+links.known+' approved-rule expenses; '+links.needsReview+' need individual review; '+links.missingExport+' missing from the imported CSV; '+links.completedPeriod+' before the working period; '+links.unresolved+' unresolved IDs.';results.append(connection);if(links.missingExport)results.append(make('p','Import a fresh accounting.csv to include the missing transactions. Scanned rows do not replace ledger postings or approve merchant rules.'));
 const audit=liveMerchantAudit(r,s.rules,s.dataset?.transactions,s.queue,s.business,s.workFrom),audited=new Map(audit.rows.map(row=>[row.id,row]));debugResults.append(make('p','Merchant rules checked: '+audit.businessRules+' for this business ('+audit.rulesLoaded+' saved total) against '+audit.rows.length+' scanned rows. '+audit.known+' known expenses; '+audit.blocked+' excluded or need review; '+audit.unmatched+' without an approved rule.')) ;
 results.append(make('p','Backlog breakdown: '+(audit.buckets.approved_expense || 0)+' known expenses; '+(audit.buckets.purchase_needing_rule || 0)+' purchases need a merchant rule; '+(audit.buckets.incoming_credit_or_income || 0)+' incoming credits/income; '+((audit.buckets.payment_refund_or_nonpurchase || 0)+(audit.buckets.transfer_refund_or_structure || 0))+' payments, transfers, refunds or structural checks; '+(audit.buckets.rule_scope_or_conflict || 0)+' rule exclusions/conflicts.'));
  const list=(r.records || []).filter(row=>(view.value!=='uncategorized' || row.uncategorized) && (ruleView.value==='all' || audited.get(row.id)?.state===ruleView.value)),identified=r.records.filter(row=>row.id).length;
  const complete=r.completeness==='count-confirmed' && !r.running;status.textContent=(r.running?'Collecting transactions':complete?'Collection complete':'Collection needs attention')+' · '+identified+' identified transactions · '+r.records.filter(row=>row.uncategorized).length+' uncategorized'+(complete?' · Updated '+new Date(r.capturedAt).toLocaleString():'. '+r.status);
  const table=make('table'),head=make('tr');for(const text of ['Date / ID','Description / Account','Category','Amount','Review status','Merchant rule / result'])head.append(make('th',text));const thead=make('thead');thead.append(head);table.append(thead);const tbody=make('tbody');for(const row of list.slice(0,limit)){const tr=make('tr');tr.append(make('td',(row.date || 'Unknown')+' · '+(row.id || 'ID unresolved')),make('td',row.description+' · '+row.account),make('td',row.category || 'Unknown'),make('td',row.amountText),make('td',row.reviewed+(row.reviewEvidence?' · '+row.reviewEvidence:'')));const match=audited.get(row.id);tr.append(make('td',(match?.rules.length?match.rules:match?.aliasRules || []).map(rule=>rule.name+' → '+rule.category).join('; ')+(match?' · '+match.reason:'')));tbody.append(tr);}table.append(tbody);const tableWrap=make('div');tableWrap.className='table-wrap';tableWrap.append(table);const collected=make('details');collected.className='collected-list';collected.open=listOpen;collected.ontoggle=()=>{listOpen=collected.open;};collected.append(make('summary','Collected transactions ('+list.length+')'),make('p','Showing '+Math.min(limit,list.length)+' of '+list.length+' collected transactions.'),tableWrap);results.append(collected);debugResults.append(make('p','Filter source: NOT_VERIFIED. Completion evidence: '+r.completeness+'.'),make('pre',JSON.stringify({status:r.status,total:r.expectedTotal,totalEvidence:r.totalEvidence,loadMoreClicks:r.loadMoreClicks,problems:r.problems},null,2)));
  if(list.length>limit){const more=make('button','Show more collected transactions');more.onclick=()=>{limit+=100;render();};collected.append(more);}
  if(r.problems?.length){const d=make('details');d.append(make('summary','Collection diagnostics'),make('pre',JSON.stringify({status:r.status,filterChipObserved:r.filterChipObserved,expectedTotal:r.expectedTotal,problems:r.problems,rowDiagnostics:r.rowDiagnostics,tableDiagnostics:r.tableDiagnostics,countDiagnostics:r.countDiagnostics,totalEvidence:r.totalEvidence,loadMoreClicks:r.loadMoreClicks},null,2)));debugResults.append(d);}
 }
 prepare.onclick=async()=>{
  if(busy || checkingRules || getState().busy)return;checkingRules=true;const task=activity.begin('Preparing known expenses');await paintActivity();render();
  try{
   await refreshRules?.();const s=getState(),r=selectedReport(),audit=liveMerchantAudit(r,s.rules,s.dataset?.transactions,s.queue,s.business,s.workFrom);
   const ids=new Set(audit.rows.filter(row=>row.state==='known').map(row=>row.id));if(!ids.size)throw Error('No approved-rule expenses are ready. Check the rule results.');
   scopes[s.business]=true;applyScope();await persist();view.value='all';ruleView.value='known';limit=100;refreshExpenses();
   ruleNotice.textContent=ids.size+' known expenses prepared. Review the selection below, then click Run selected expenses. Nothing applied yet.';
   showWorkspace('usage');if(showExpenses)showExpenses(ids);
  }catch(e){ruleNotice.textContent=e.message;}finally{checkingRules=false;render();task.finish();}
 };
 const persist=async()=>{if(getState().extensionMode)await chrome.storage.local.set({solverLiveLists:reports,solverLiveListScopes:scopes});};
 scope.onchange=async()=>{scopes[getState().business]=scope.checked;applyScope();await persist();refreshExpenses();};view.onchange=ruleView.onchange=()=>{limit=100;render();};
 checkRules.onclick=async()=>{checkingRules=true;const task=activity.begin('Checking merchant rules against live transactions');await paintActivity();render();try{await refreshRules?.();refreshExpenses();ruleNotice.textContent='Saved merchant rules reloaded and checked against the scanned list.';}catch(e){ruleNotice.textContent=e.message;}finally{checkingRules=false;render();task.finish();}};
 copyRules.onclick=async()=>{const s=getState();try{await navigator.clipboard.writeText(JSON.stringify({audit:liveMerchantAudit(selectedReport(),s.rules,s.dataset?.transactions,s.queue,s.business,s.workFrom),rules:s.rules},null,2));copyRules.textContent='Copied';}catch{status.textContent='Clipboard unavailable.';}};
 copy.onclick=async()=>{const r=selectedReport();try{await navigator.clipboard.writeText(JSON.stringify({...r,records:undefined},null,2));copy.textContent='Copied';}catch{status.textContent='Clipboard unavailable. Download the collected list to retain diagnostics.';}};
 download.onclick=()=>{const blob=new Blob([JSON.stringify(selectedReport(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download='wave-live-not-reviewed.local.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 stop.onclick=async()=>{stop.disabled=true;if(tabId!==null)await chrome.scripting.executeScript({target:{tabId},func:waveListScan,args:[{action:'stop'}]});};
 start.onclick=async()=>{const s=getState(),business=s.business;if(busy || s.busy || !business)return;busy=true;const task=activity.begin('Collecting Not Reviewed transactions',{priority:10});await paintActivity();onRunning(true);render();let report=null;
  try{
   const tab=await openBackgroundTab(chrome.tabs,'https://next.waveapps.com/'+business+'/transactions?status=NOT_VERIFIED',tabId);tabId=tab.id;
   for(let i=0;i<30;i++){const current=await chrome.tabs.get(tabId);if(current.status==='complete' && current.url==='https://next.waveapps.com/'+business+'/transactions?status=NOT_VERIFIED' && !current.pendingUrl)break;await new Promise(resolve=>setTimeout(resolve,500));}
   if(getState().business!==business)throw Error('Business changed. Collection cancelled.');
   const known=(s.dataset?.transactions || []).filter(t=>t.primary).map(t=>({id:t.id,date:t.date,description:t.description,account:t.primary.account,amountCents:t.amount}));
   report=(await chrome.scripting.executeScript({target:{tabId},func:waveListScan,args:[{action:'start',business,known}]}))[0]?.result;if(!report)throw Error('No list collection response.');
   while(report.running){task.update({detail:(report.records?.length || 0)+' transactions read · '+(report.loadMoreClicks || 0)+' pages loaded',completed:report.records?.length || 0,total:report.expectedTotal});reports[business]=report;render();await new Promise(resolve=>setTimeout(resolve,1400));if(getState().business!==business)await chrome.scripting.executeScript({target:{tabId},func:waveListScan,args:[{action:'stop'}]});report=(await chrome.scripting.executeScript({target:{tabId},func:waveListScan,args:[{action:'poll'}]}))[0]?.result;if(!report)throw Error('The collection tab was closed or reloaded. Partial results retained.');}
   reports[business]=report;if(report.completeness==='count-confirmed')scopes[business]=true;await persist();
  }catch(e){if(report){report={...report,running:false,status:'Collection interrupted: '+e.message,completeness:'unconfirmed'};reports[business]=report;await persist();}else status.textContent=e.message;}
  finally{busy=false;onRunning(false);if(report)render();else{start.disabled=false;stop.disabled=true;stop.hidden=true;}try{refreshExpenses();}finally{task.finish(report?.completeness==='count-confirmed'?'Live collection ready.':'Collection stopped; check its completion status.');}}
 };
 const ready=(async()=>{if(getState().extensionMode){const stored=await chrome.storage.local.get(['solverLiveLists','solverLiveListScopes']);reports=stored.solverLiveLists || {};scopes=stored.solverLiveListScopes || {};}render();refreshExpenses();})();
 return {render,ready,report:selectedReport,tab:()=>tabId,collect:async()=>{showUsageSection('liveList');fold.open=true;await start.onclick();}};
}
