import {waveListScan} from './list-scan.js';
import {scopedListIds} from './list-view.js';
const business='11111111-1111-1111-1111-111111111111',mount=document.getElementById('fixture');
const records=Array.from({length:25},(_,i)=>({id:String(1000000000000000000n+BigInt(i+1)),date:'2026-10-01',description:'Fictional Merchant '+i,account:'Fictional Checking',category:i%3===0?'Uncategorized Expense':'Software',amountText:'$'+(i+1)+'.00',amountCents:(i+1)*100}));
function setup({unknown=false,total=true,stop=false,navigate=false,initialBottom=false,paged=false,preselected=false,wrongCount=false,changingLabel=false,waveLayout=false,encoded=false,foreign=false,conflictingStatus=false,all=false,leakedFilter=false,search=false}={}){
 mount.replaceChildren();const chip=document.createElement('span');chip.textContent='Not Reviewed';if(!all || leakedFilter)mount.append(chip);if(search){const input=document.createElement('input');input.placeholder='Search transactions';input.value='Fictional';mount.append(input);}if(total){const count=document.createElement('p');count.textContent='Showing 1 of 25 transactions';mount.append(count);}
 const scroll=document.createElement('div');scroll.style.height='160px';scroll.style.overflowY='auto';const table=document.createElement('table');table.innerHTML='<thead><tr><th>Date</th><th>Description</th><th>Account</th><th>Category</th><th>Amount</th><th>Actions</th></tr></thead><tbody></tbody>';scroll.append(table);mount.append(scroll);let loaded=0,clicks=0,ticks=0,loads=0,selectionClicks=0;
 if(waveLayout){const header=document.createElement('table');header.innerHTML='<thead class="wv-table__header"><tr class="wv-table__row"><td></td><td></td><td>Date</td><td>Description</td><td>Account</td><td>Category</td><td>Amount</td><td></td><td>Actions</td></tr></thead>';table.querySelector('thead').remove();scroll.prepend(header);}
 const known=records.map(r=>({...r}));if(unknown){for(const n of [17,18])known[n]={...known[n],description:'Identical merchant',amountCents:9900};}
 const append=()=>{for(let n=0;n<5 && loaded<25;n++,loaded++){const source=records[loaded],r=unknown && [17,18].includes(loaded)?{...source,description:'Identical merchant',amountText:'$99.00'}:source;const row=document.createElement('tr');row.className='wv-table__row';if(waveLayout){row.append(document.createElement('td'),document.createElement('td'));}if(!encoded && (!unknown || ![16,17,18].includes(loaded)))row.dataset.transactionId=r.id;if(encoded){const identity=document.createElement('div');identity.dataset.testid='BulkCheckbox'+btoa('Business:'+(foreign && loaded===0?'22222222-2222-2222-2222-222222222222':business)+';Transaction:'+r.id);row.prepend(identity);const marker=document.createElement('div');marker.className='transactions-list-v2__row__verify-icon transactions-list-v2__row__verify-icon--'+(loaded===1?'verified':'unverified');if(loaded===0)marker.classList.add('transactions-list-v2__row__verify-icon--unverified--is-disabled');if(conflictingStatus && loaded===2)marker.setAttribute('aria-label','Reviewed');identity.append(marker);}if(loaded===0)row.dataset.reviewed='false';if(loaded===1)row.dataset.reviewed='true';for(const value of [r.date,r.description,r.account,r.category,r.amountText]){const cell=document.createElement('td');cell.textContent=value;row.append(cell);}if(waveLayout)row.append(document.createElement('td'));const cell=document.createElement('td'),edit=document.createElement('button');edit.textContent='Edit transaction';edit.onclick=()=>clicks++;cell.append(edit);row.append(cell);const metadata=row.querySelector(':scope > div');if(metadata)row.querySelector('td').append(metadata);table.querySelector('tbody').append(row);}};
 const more=document.createElement('button');more.textContent='Load More Transactions';if(paged){mount.append(more);more.onclick=()=>{loads++;append();if(loaded===25)more.remove();};}
 const selection=document.createElement('input');selection.type='checkbox';selection.checked=preselected;const label=document.createElement('label');label.append(selection,document.createTextNode('Select all'));const selected=document.createElement('span');
 if(paged){mount.prepend(label,selected);selection.onclick=()=>{selectionClicks++;selected.textContent=selection.checked?(wrongCount?'26 selected':loaded+' selected'):'';if(changingLabel)label.lastChild.textContent=selection.checked?loaded+' selected':'Select all';};if(preselected)selected.textContent='5 selected';}
 append();if(initialBottom)scroll.scrollTop=scroll.scrollHeight;const fakeWindow={},fakeLocation={href:'https://next.waveapps.com/'+business+(all?'/transactions':'/transactions?status=NOT_VERIFIED')};
 const context={document,window:fakeWindow,location:fakeLocation,getComputedStyle,wait:async()=>{ticks++;if(!paged && scroll.scrollTop+scroll.clientHeight>=scroll.scrollHeight-3 && loaded<25)append();if(stop && ticks===2)waveListScan({action:'stop'},context);if(navigate && ticks===2)fakeLocation.href='https://next.waveapps.com/'+business+'/transactions';await new Promise(resolve=>setTimeout(resolve,0));}};
 return {context,known,clicks:()=>clicks,loads:()=>loads,selectionClicks:()=>selectionClicks,selection};
}
document.getElementById('run').onclick=async()=>{const output=document.getElementById('checks');output.replaceChildren();let failed=0,passed=0;
 async function check(name,options,assert){try{const f=setup(options);waveListScan({action:'start',business,mode:options.all?'ALL':'NOT_VERIFIED',known:f.known},f.context);await f.context.window.__dandelionWaveListScanV1.done;const r=waveListScan({action:'poll'},f.context);assert(r,f);if(f.clicks())throw Error('An edit control was clicked');passed++;const li=document.createElement('li');li.textContent='PASS '+name;output.append(li);}catch(e){failed++;const li=document.createElement('li');li.textContent='FAIL '+name+': '+e.message;output.append(li);}}
 const equal=(a,b)=>{if(a!==b)throw Error('Expected '+b+', got '+a);};
 await check('Lazy-loaded rows are all collected once without clicking edit controls',{},r=>{equal(r.records.length,25);equal(new Set(r.records.map(x=>x.id)).size,25);equal(r.completeness,'count-confirmed');equal(r.filterChipObserved,true);equal(r.records[0].reviewed,'Not reviewed');equal(r.records[1].reviewed,'Reviewed');equal(r.records[2].reviewed,'Unknown');});
 await check('Unique export identities resolve, duplicate full-field matches remain unresolved',{unknown:true},r=>{equal(r.records.length,25);equal(r.records.find(x=>x.description==='Fictional Merchant 16').identity,'Unique full-field export match');equal(r.records.filter(x=>x.description==='Identical merchant' && !x.id).length,2);equal(scopedListIds(r).size,22);});
 await check('Bottom stability does not invent an independent total',{total:false},r=>{equal(r.records.length,25);equal(r.expectedTotal,null);equal(r.completeness,'bottom-reached');});
 await check('A reused scrolled tab starts again from the top',{initialBottom:true},r=>{equal(r.records.length,25);equal(r.completeness,'count-confirmed');});
 await check('Load More is pressed until absent and Select All count is cleared',{paged:true,total:false},(r,f)=>{equal(r.records.length,25);equal(f.loads(),4);equal(r.expectedTotal,25);equal(r.totalEvidence,'Select All selected count');equal(r.completeness,'count-confirmed');equal(f.selectionClicks(),2);equal(f.selection.checked,false);});
 await check('Count cleanup survives Select All changing to the selected count',{paged:true,total:false,changingLabel:true},(r,f)=>{equal(r.expectedTotal,25);equal(r.completeness,'count-confirmed');equal(f.selectionClicks(),2);equal(f.selection.checked,false);});
 await check('Existing selection is preserved without inventing a full count',{paged:true,total:false,preselected:true},(r,f)=>{equal(f.selectionClicks(),0);equal(f.selection.checked,true);equal(r.expectedTotal,null);equal(r.completeness,'bottom-reached');});
 await check('A mismatched selected count never confirms completeness',{paged:true,total:false,wrongCount:true},(r,f)=>{equal(r.expectedTotal,26);equal(r.completeness,'bottom-reached');equal(f.selection.checked,false);});
 await check('Wave td headers and separate body table map all nine columns',{paged:true,total:false,waveLayout:true},(r,f)=>{equal(r.records.length,25);equal(r.tableDiagnostics.headers[2],'Date');equal(r.records[0].description,'Fictional Merchant 0');equal(r.records[0].category,'Uncategorized Expense');equal(f.loads(),4);equal(r.completeness,'count-confirmed');if(r.problems.some(p=>p.includes('could not be parsed')))throw Error('Header was parsed as data');});
 await check('Encoded Wave business and transaction IDs distinguish identical purchases',{paged:true,total:false,waveLayout:true,encoded:true,unknown:true},r=>{equal(r.records.length,25);equal(r.records.filter(x=>x.id).length,25);equal(r.records.filter(x=>x.description==='Identical merchant').length,2);equal(new Set(r.records.filter(x=>x.description==='Identical merchant').map(x=>x.id)).size,2);equal(r.records[0].reviewed,'Not reviewed');equal(r.records[0].reviewControlDisabled,true);equal(r.records[1].reviewed,'Reviewed');equal(r.records[2].reviewed,'Not reviewed');equal(r.completeness,'count-confirmed');});
 await check('Encoded IDs from another business cannot resolve via the export',{paged:true,total:false,waveLayout:true,encoded:true,foreign:true},r=>{equal(r.records.filter(x=>x.id).length,24);equal(r.records.find(x=>x.description==='Fictional Merchant 0').id,null);equal(r.completeness,'bottom-reached');});
 await check('Conflicting review markers remain unknown',{paged:true,total:false,waveLayout:true,encoded:true,conflictingStatus:true},r=>{equal(r.records.find(x=>x.description==='Fictional Merchant 2').reviewed,'Unknown');});
 await check('Stop retains partial collection',{stop:true},r=>{equal(r.running,false);if(!r.status.startsWith('Stopped') || r.records.length>=25)throw Error('Stop did not retain partial state');});
 await check('Changed filter stops collection rather than mixing pages',{navigate:true},r=>{equal(r.running,false);if(!r.status.includes('filter changed') || r.completeness==='count-confirmed')throw Error('Navigation did not stop capture');});
 await check('Unfiltered full collection loads every page and preserves reviewed states',{all:true,paged:true,total:false},(r,f)=>{equal(r.records.length,25);equal(r.filter,'ALL');equal(r.records[1].reviewed,'Reviewed');equal(r.records[0].reviewed,'Not reviewed');equal(r.records[2].reviewed,'Unknown');equal(r.completeness,'count-confirmed');equal(f.loads(),4);equal(scopedListIds(r).size,0);});
 await check('Full collection refuses a lingering Not Reviewed chip',{all:true,leakedFilter:true,paged:true},r=>{equal(r.completeness,'unconfirmed');if(!r.status.includes('active filters'))throw Error('Filter leakage accepted');});
 await check('Full collection refuses an active transaction search',{all:true,search:true,paged:true},r=>{equal(r.completeness,'unconfirmed');if(!r.status.includes('active filters'))throw Error('Search leakage accepted');});
 try{const f=setup();f.context.location.href='https://next.waveapps.com/'+business+'/transactions';let rejected=false;try{waveListScan({business,action:'start'},f.context);}catch{rejected=true;}if(!rejected)throw Error('Missing NOT_VERIFIED filter accepted');passed++;const li=document.createElement('li');li.textContent='PASS Start requires the exact business list and filter';output.append(li);}catch(e){failed++;}
 document.getElementById('result').textContent=passed+' passed, '+failed+' failed';mount.replaceChildren();
};
