import {paypalOrigins,paypalReportURL,paypalPeriods,paypalReportKey,savePayPalCSV,verifyPayPalFile,collectPayPalReports} from './paypal.js';
import {paypalPage} from './paypal-page.js';
import {loadLocalFeature,saveLocalFeature} from './session.js';
import {activity,paintActivity} from './activity.js';
const $=id=>document.getElementById(id),real=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
let state={version:1,folder:null,entries:{},fromYear:2019,dateOrder:'mdy'},connected=false,busy=false,generation=0,diagnostics=null;
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const save=()=>saveLocalFeature('paypal:downloader',state);
function paint(){for(const id of ['connect','open','folder','tabs','refreshTabs','year','dateOrder','read','copy','clearRequest'])$(id).disabled=busy;$('stop').disabled=!busy;$('run').disabled=busy||!real||!connected||!state.folder||!$('tabs').value;$('setup').textContent=!real?'Open this helper from the installed extension.':!connected?'Connect PayPal, then choose your data/paypal folder.':!state.folder?'Choose the paypal folder inside your project data folder.':!$('tabs').value?'Open the signed-in PayPal Activity download page, then refresh the tab list.':'Ready · Folder: '+state.folder.name;try{const plan=paypalPeriods(Number($('year').value),today());$('limits').textContent='New requests: '+plan.periods[0].start+' through '+today()+'. '+(plan.limited?'PayPal’s seven-year limit clips the first year. Older ready CSVs are still saved.':'Current year is a partial report.');}catch(e){$('limits').textContent=e.message;}
 const entries=Object.values(state.entries),files=entries.filter(e=>e.hash);$('coverage').textContent=files.length+' saved CSVs · '+entries.filter(e=>['requesting','requested'].includes(e.status)).length+' waiting or unconfirmed requests. Saved report ranges are not proof of complete historical coverage.';$('files').replaceChildren();for(const entry of files.slice(-8).reverse()){const p=document.createElement('p');p.textContent=entry.name+' · '+entry.count+' activity rows';$('files').append(p);}}
async function refreshTabs(){if(!real)return;connected=await chrome.permissions.contains({origins:paypalOrigins});const selected=$('tabs').value;$('tabs').replaceChildren();if(!connected)return;const tabs=await chrome.tabs.query({url:paypalOrigins});for(const tab of tabs){try{const u=new URL(tab.url);if(u.origin!=='https://www.paypal.com'||!/^\/reports\/dlog\/?$/.test(u.pathname))continue;const o=document.createElement('option');o.value=tab.id;o.textContent=tab.title||'PayPal Activity download';$('tabs').append(o);}catch{}}if([...$('tabs').options].some(o=>o.value===selected))$('tabs').value=selected;}
async function page(action,request={}){const tabId=Number($('tabs').value);if(!tabId)throw Error('Open PayPal reports and refresh the tab list.');const tab=await chrome.tabs.get(tabId),url=new URL(tab.url);if(url.origin!=='https://www.paypal.com'||!/^\/reports\/dlog\/?$/.test(url.pathname))throw Error('The selected tab left PayPal reports. Log in, reopen the report page, then Resume.');const result=await chrome.scripting.executeScript({target:{tabId},world:['create','download'].includes(action)?'MAIN':'ISOLATED',func:paypalPage,args:[{dateOrder:state.dateOrder,...request,action}]});if(!result[0]?.result)throw Error('PayPal returned no report information.');return result[0].result;}
const guarded=fn=>async()=>{if(busy)return;busy=true;paint();const task=activity.begin('Preparing PayPal downloads');try{await fn();}catch(e){$('status').textContent=e.message;}finally{busy=false;task.finish();paint();}};
$('connect').onclick=guarded(async()=>{if(!real)throw Error('Use the installed extension.');if(!await chrome.permissions.request({origins:paypalOrigins}))throw Error('PayPal report access was not granted.');await refreshTabs();$('status').textContent='PayPal connected. Open its Activity download page and choose the destination.';});
$('open').onclick=guarded(async()=>{if(!real)throw Error('Use the installed extension.');const tabs=connected?await chrome.tabs.query({url:paypalReportURL+'*'}):[];if(tabs.length===1)await chrome.tabs.update(tabs[0].id,{active:true});else await chrome.tabs.create({url:paypalReportURL,active:true});await refreshTabs();$('status').textContent='Sign in to PayPal if needed, then return here and refresh the tab list.';});
$('refreshTabs').onclick=guarded(refreshTabs);
$('folder').onclick=guarded(async()=>{if(typeof showDirectoryPicker!=='function')throw Error('Folder access requires the extension in Chrome.');const folder=await showDirectoryPicker({id:'wave-paypal',mode:'readwrite',startIn:'desktop'});if(folder.name.toLowerCase()!=='paypal')throw Error('Choose the paypal folder inside wave-solver/data.');state.folder=folder;await save();$('status').textContent='Destination saved. Ready to collect CSV reports.';});
$('year').onchange=$('dateOrder').onchange=()=>paint();$('tabs').onchange=()=>paint();
$('read').onclick=guarded(async()=>{diagnostics=await page('read');$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);$('status').textContent=diagnostics.reports.length+' recognizable reports found.';});
$('copy').onclick=guarded(async()=>{if(!diagnostics)throw Error('Read report controls first.');await navigator.clipboard.writeText(JSON.stringify(diagnostics,null,2));$('status').textContent='Report controls copied.';});
$('clearRequest').onclick=guarded(async()=>{const info=await page('read'),entries={...state.entries};let cleared=0;for(const [key,entry] of Object.entries(entries)){if(['requesting','requested'].includes(entry.status)&&!(info.reports||[]).some(r=>paypalReportKey(r)===key)){delete entries[key];cleared++;}}state.entries=entries;await save();$('status').textContent=cleared+' absent request checkpoints cleared. Visible waiting reports remain protected.';});
async function persist(entries){state.entries=entries;await save();const file=await state.folder.getFileHandle('paypal-manifest.local.json',{create:true}),stream=await file.createWritable();try{await stream.write(JSON.stringify({format:'wave-solver-paypal-downloads',version:1,dateOrder:state.dateOrder,entries},null,2));await stream.close();}catch(e){await stream.abort?.();throw e;}paint();}
$('run').onclick=async()=>{if(busy)return;const runId=++generation;busy=true;paint();const task=activity.begin('Collecting PayPal activity CSVs');try{if(!real||!connected||!state.folder||!$('tabs').value)throw Error('Finish Connect, destination and report-tab setup first.');if(await state.folder.requestPermission({mode:'readwrite'})!=='granted')throw Error('Allow access to the selected paypal folder to resume.');state.fromYear=Number($('year').value);state.dateOrder=$('dateOrder').value;const plan=paypalPeriods(state.fromYear,today());await save();await paintActivity();const progress=(report,message)=>{const index=plan.periods.findIndex(p=>paypalReportKey(p)===paypalReportKey(report));$('progress').max=plan.periods.length;$('progress').value=Math.max(0,index);$('status').textContent=message+' · '+report.start+' to '+report.end;task.update({detail:$('status').textContent,completed:Math.max(0,index),total:plan.periods.length});};const result=await collectPayPalReports({periods:plan.periods,entries:state.entries,read:()=>page('read'),download:async report=>(await page('download',report)).text,save:(report,text)=>savePayPalCSV(state.folder,report,text,state.dateOrder),persist,verifySaved:entry=>verifyPayPalFile(state.folder,entry),current:()=>generation===runId,progress,request:async report=>{if(generation!==runId)return {notSubmitted:true,message:'Stopped before creating a report.'};const result=await page('create',report);if(result.notSubmitted)return result;for(let i=0;i<20&&generation===runId;i++){await new Promise(r=>setTimeout(r,1000));progress(report,'Waiting for PayPal to prepare the report');const info=await page(i%5===4?'refresh':'read');if(info.reports.some(r=>paypalReportKey(r)===paypalReportKey(report)&&r.ready))break;}return result;}});
 $('status').textContent=result.stopped?'Stopped. Saved files are checkpointed; Resume continues.':result.waiting?(result.uncertain?'Interrupted request is unconfirmed. Check PayPal’s report list; no duplicate was requested.':'PayPal is preparing '+result.waiting.start+' to '+result.waiting.end+'. Click Resume when its Download button appears.'):'Annual collection finished. Refresh your source-data folder in the solver.';if(!result.stopped&&!result.waiting)$('progress').value=plan.periods.length;
 }catch(e){$('status').textContent='Stopped: '+e.message;}finally{busy=false;task.finish();paint();}};
$('stop').onclick=()=>{generation++;$('status').textContent='Stopping after the current download; saved files remain available.';};
try{const saved=await loadLocalFeature('paypal:downloader');if(saved?.version===1&&saved.entries&&['mdy','dmy'].includes(saved.dateOrder))state=saved;}catch(e){$('status').textContent='Local setup could not be restored: '+e.message;}
$('year').value=state.fromYear;$('dateOrder').value=state.dateOrder;await refreshTabs();paint();
