import {helperTabs} from './helper-tabs.js';
import {paypalCSVDownload,paypalDownloadRecovery} from './paypal-download.js';
import {observeNativeDownload} from './download-files.js';
import {helperCall} from './helper-bridge.js';
import {paypalOrigins,paypalReportURL,paypalPeriods,paypalReportKey,savePayPalCSV,verifyPayPalFile,collectPayPalReports} from './paypal.js';
import {paypalPage} from './paypal-page.js';
import {loadLocalFeature,saveLocalFeature,projectDataFolder,rememberDataFolder} from './session.js';
import {activity,paintActivity} from './activity.js';
const $=id=>document.getElementById(id),real=typeof chrome!=='undefined'&&!!chrome.runtime?.id;
let state={version:1,folder:null,entries:{},fromYear:2019,dateOrder:'mdy'},connected=false,busy=false,generation=0,diagnostics=null;
const working=real?helperTabs(chrome.tabs):null;let workingTab=null;
const today=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');};
const save=()=>saveLocalFeature('paypal:downloader',state);
function paint(){for(const id of ['connect','open','folder','tabs','refreshTabs','year','dateOrder','clearRequest'])$(id).disabled=busy;for(const id of ['read','readDownload'])$(id).disabled=!real||!connected;$('copy').disabled=!diagnostics;$('stop').disabled=!busy;$('run').disabled=busy||!real||!connected||!state.folder;$('setup').textContent=!real?'Open this helper from the installed extension.':!connected?'Connect PayPal, then choose your project data folder.':!state.folder?'Choose your project data folder; CSVs are sorted into data/paypal.':'Ready · Folder: '+state.folder.name;try{const plan=paypalPeriods(Number($('year').value),today(),state.availableThrough||today());$('limits').textContent='New requests: '+plan.periods[0].start+' through '+plan.through+'. '+(plan.limited?'PayPal keeps seven years. First report: '+plan.periods[0].start+' to '+plan.periods[0].end+(plan.periods[0].partial?' (partial year).':' (full year).')+' Later completed years use Jan 1 to Dec 31. Older available CSVs are collected after requested years.':'Current year ends at PayPal’s latest available data date.');}catch(e){$('limits').textContent=e.message;}
 const entries=Object.values(state.entries),files=entries.filter(e=>e.hash);$('coverage').textContent=files.length+' saved CSVs · '+entries.filter(e=>['requesting','requested'].includes(e.status)).length+' request checkpoints (verified against PayPal on Resume). Saved report ranges are not proof of complete historical coverage.';$('files').replaceChildren();for(const entry of files.slice(-8).reverse()){const p=document.createElement('p');p.textContent=entry.name+' · '+entry.count+' activity rows';$('files').append(p);}}
async function refreshTabs(){if(!real)return;connected=await chrome.permissions.contains({permissions:['downloads'],origins:paypalOrigins});const selected=$('tabs').value;$('tabs').replaceChildren();if(!connected)return;const tabs=await chrome.tabs.query({url:paypalOrigins});for(const tab of tabs){try{const u=new URL(tab.url);if(u.origin!=='https://www.paypal.com'||!/^\/reports\/dlog\/?$/.test(u.pathname))continue;const o=document.createElement('option');o.value=tab.id;o.textContent=tab.title||'PayPal Activity download';$('tabs').append(o);}catch{}}if([...$('tabs').options].some(o=>o.value===selected))$('tabs').value=selected;}
async function page(action,request={}){const tabId=workingTab||Number($('tabs').value);if(!tabId)throw Error('Open PayPal reports and refresh the tab list.');const tab=await chrome.tabs.get(tabId),url=new URL(tab.url);if(url.origin!=='https://www.paypal.com'||!/^\/reports\/dlog\/?$/.test(url.pathname))throw Error('The selected tab left PayPal reports. Log in, reopen the report page, then Resume.');const token=generation;return helperCall({current:()=>generation===token,request:{dateOrder:state.dateOrder,...request,action},onWait:message=>{$('status').textContent=message;},execute:args=>chrome.scripting.executeScript({target:{tabId},world:['prepare','create','download'].includes(action)?'MAIN':'ISOLATED',func:paypalPage,args:[args]})});}

const guarded=fn=>async()=>{if(busy)return;busy=true;paint();const task=activity.begin('Preparing PayPal downloads');try{await fn();}catch(e){$('status').textContent=e.message;}finally{busy=false;task.finish();paint();}};
$('connect').onclick=guarded(async()=>{if(!real)throw Error('Use the installed extension.');if(!await chrome.permissions.request({permissions:['downloads'],origins:paypalOrigins}))throw Error('PayPal report access was not granted.');await refreshTabs();if($('setupPanel')&&state.folder)$('setupPanel').open=false;$('status').textContent='PayPal connected. Open its Activity download page and choose the destination.';});
$('open').onclick=guarded(async()=>{if(!real)throw Error('Use the installed extension.');workingTab=await working.open('paypal',paypalReportURL,true);await refreshTabs();$('tabs').value=String(workingTab);$('status').textContent='Sign in if needed. After setup, Collect all reports opens its working tab automatically.';});
$('refreshTabs').onclick=guarded(refreshTabs);
$('folder').onclick=guarded(async()=>{if(typeof showDirectoryPicker!=='function')throw Error('Folder access requires the extension in Chrome.');const root=await showDirectoryPicker({id:'wave-data-downloads',mode:'readwrite',startIn:'desktop'});await rememberDataFolder(root);state.folder=await root.getDirectoryHandle('paypal',{create:true});await save();if($('setupPanel')&&connected)$('setupPanel').open=false;$('status').textContent='Shared project data folder saved. PayPal reports go into data/paypal.';});
$('year').onchange=$('dateOrder').onchange=()=>paint();$('tabs').onchange=()=>paint();
const inspect=fn=>async()=>{try{await fn();}catch(e){$('diagnostics').textContent=e.message;}finally{paint();}};
$('read').onclick=inspect(async()=>{diagnostics=await page('read');$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);if(!busy)$('status').textContent=diagnostics.reports.length+' recognizable reports found.';});
if($('readDownload'))$('readDownload').onclick=inspect(async()=>{const pending=state.download,item=pending?.downloadId===undefined?null:(await chrome.downloads.search({id:pending.downloadId}))[0];diagnostics={format:'wave-solver-paypal-download-status',version:1,recordedDownload:!!pending,downloadId:pending?.downloadId??null,state:item?.state||'not found',csvRecognized:item?paypalCSVDownload(item):false,exists:item?.exists??null};$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);});
$('copy').onclick=inspect(async()=>{if(!diagnostics)throw Error('Read report controls first.');await navigator.clipboard.writeText(JSON.stringify(diagnostics,null,2));if(!busy)$('status').textContent='Report controls copied.';});
$('clearRequest').onclick=guarded(async()=>{const info=await page('read'),entries={...state.entries};let cleared=0;for(const [key,entry] of Object.entries(entries)){if(['requesting','requested'].includes(entry.status)&&!(info.reports||[]).some(r=>paypalReportKey(r)===key)){delete entries[key];cleared++;}}state.entries=entries;await save();$('status').textContent=cleared+' absent request checkpoints cleared. Visible waiting reports remain protected.';});
async function downloadCSV(report,current,onProgress){
 const root=await projectDataFolder();if(!root)throw Error('Choose the shared project data folder so browser CSV downloads can be collected.');
 for(let attempt=0;attempt<2;attempt++){
  const pending=state.download&&paypalReportKey(state.download)===paypalReportKey(report)?state.download:null,recovery=await paypalDownloadRecovery(chrome.downloads,pending);
  if(recovery.stale){delete state.download;await save();}
  const result=await observeNativeDownload({downloads:chrome.downloads,inbox:root,current,timeoutMs:120000,startTimeoutMs:15000,accept:paypalCSVDownload,resumeId:recovery.resumeId??null,checkpoint:async value=>{state.download={type:report.type,start:report.start,end:report.end,format:report.format,...value};await save();},onProgress,trigger:recovery.retry?async()=>{
   const info=await page('read'),ready=info.reports.find(r=>r.ready&&paypalReportKey(r)===paypalReportKey(report));if(!ready)throw Error('The selected report is no longer ready. Resume refreshes its status; report submissions stay saved.');
   try{const response=await page('download',ready);if(response.text!==undefined)return {file:new File([response.text],'paypal-report.csv')};}
   catch(error){if(!error.downloadStarted&&!error.retryable)throw error;}
   onProgress('Collecting the selected CSV into the project data folder...');
  }:null});
  if(!result.waiting)return result.file.text();
  if(result.notStarted&&attempt===0){onProgress('No CSV download started; retrying this exact report once...');continue;}
  if(result.notStarted)throw Error('PayPal did not start this CSV download: '+report.start+' to '+report.end+'. No download is in progress. Existing reports remain in PayPal; Resume retries this exact download.');
  if(state.download?.downloadId!==undefined&&paypalReportKey(state.download)===paypalReportKey(report))throw Error('The recorded PayPal CSV is still downloading. Resume continues that download; report submissions stay saved.');
 }
 throw Error('PayPal did not produce a recognizable CSV after two download attempts. No new report was created. Read download status in Advanced.');
}
async function persist(entries){state.entries=entries;await save();const file=await state.folder.getFileHandle('paypal-manifest.local.json',{create:true}),stream=await file.createWritable();try{await stream.write(JSON.stringify({format:'wave-solver-paypal-downloads',version:1,dateOrder:state.dateOrder,entries},null,2));await stream.close();}catch(e){await stream.abort?.();throw e;}paint();}
$('run').onclick=async()=>{if(busy)return;const runId=++generation;busy=true;paint();const task=activity.begin('Collecting PayPal activity CSVs');try{if(!real||!connected||!state.folder)throw Error('Finish Connect and destination setup first.');workingTab=await working.open('paypal',paypalReportURL);await refreshTabs();$('tabs').value=String(workingTab);const root=await projectDataFolder();if(root){if(await root.requestPermission({mode:'readwrite'})!=='granted')throw Error('Allow access to the shared data folder.');state.folder=await root.getDirectoryHandle('paypal',{create:true});}if(await state.folder.requestPermission({mode:'readwrite'})!=='granted')throw Error('Allow access to the selected paypal folder to resume.');state.fromYear=Number($('year').value);state.dateOrder=$('dateOrder').value;const provider=await page('read');state.availableThrough=provider.availableThrough||null;const plan=paypalPeriods(state.fromYear,today(),state.availableThrough||today());await save();await paintActivity();let downloadStage='';const progress=(report,message,meta={})=>{downloadStage=message;const done=Math.min(plan.periods.length,meta.completed||0);$('progress').max=plan.periods.length;$('progress').value=done;$('status').textContent=message+(meta.phase==='waiting'?'':' - '+report.start+' to '+report.end);task.update({detail:$('status').textContent,completed:done,total:plan.periods.length});};const result=await collectPayPalReports({periods:plan.periods,entries:state.entries,read:()=>page('read'),download:report=>downloadCSV(report,()=>generation===runId,message=>{$('status').textContent=downloadStage+' - '+report.start+' to '+report.end+' · '+message;task.update({detail:$('status').textContent});}),save:async(report,text)=>{const saved=await savePayPalCSV(state.folder,report,text,state.dateOrder);if(state.download&&paypalReportKey(state.download)===paypalReportKey(report)){delete state.download;await save();}return saved;},persist,verifySaved:entry=>verifyPayPalFile(state.folder,entry),current:()=>generation===runId,progress,refresh:()=>page('refresh'),prepare:report=>page('prepare',report),request:async report=>{if(generation!==runId)return {notSubmitted:true,message:'Stopped before creating a report.'};return page('create',report);}});
 $('status').textContent=result.stopped?'Stopped. Saved files are checkpointed; Resume continues.':result.unconfirmed?'Report not found in PayPal: '+result.unconfirmed.start+' to '+result.unconfirmed.end+'. Not waiting for a download. Resume checks the refreshed report list and retries a confirmed absent request.':result.waiting?'PayPal is still preparing '+result.pending.length+' confirmed reports after ten minutes. Resume keeps their submissions and continues collecting.':result.archiveIssues?.length?'Requested yearly reports are saved. '+result.archiveIssues.length+' older exports could not be saved; details are in Advanced. Resume retries available older exports. Refresh your data folder in the Command center.':'Annual collection finished. Refresh your source-data folder in the solver.';if(result.archiveIssues?.length){diagnostics={format:'wave-solver-paypal-archive-issues',version:1,reports:result.archiveIssues};$('diagnostics').textContent=JSON.stringify(diagnostics,null,2);}if(!result.stopped&&!result.waiting&&!result.unconfirmed&&!result.archiveIssues?.length){$('progress').value=plan.periods.length;await working.finish();workingTab=null;await refreshTabs();}
 }catch(e){$('status').textContent='Stopped: '+e.message;}finally{busy=false;task.finish();paint();}};
$('stop').onclick=()=>{generation++;$('status').textContent='Stopping after the current download; saved files remain available.';};
try{const saved=await loadLocalFeature('paypal:downloader');if(saved?.version===1&&saved.entries&&['mdy','dmy'].includes(saved.dateOrder))state=saved;const root=await projectDataFolder();if(root)state.folder=await root.getDirectoryHandle('paypal',{create:true});}catch(e){$('status').textContent='Local setup could not be restored: '+e.message;}
$('year').value=state.fromYear;$('dateOrder').value=state.dateOrder;await refreshTabs();if($('setupPanel'))$('setupPanel').open=!connected||!state.folder;paint();
