import {merchantText,normalize,matchingRules,nonPurchaseReason,validateRule} from './rules.js';
const services=[['venmo','Venmo',/\bvenmo\b/i,'Open Venmo to identify the recipient and payment purpose.'],['paypal','PayPal',/\bpaypal\b/i,'Check PayPal activity or receipts; payments can have different purposes.'],['zelle','Zelle',/\bzelle\b/i,'Check the recipient and payment purpose.'],['cash-app','Cash App',/\bcash\s*app\b/i,'Check Cash App activity and the recipient.'],['square','Square',/^(?:sq\s*\*|square\b)/i,'Square is a processor. Review each underlying merchant separately.'],['amazon','Amazon',/\b(?:amazon|amzn)\b/i,'Use the Amazon purchase solver in Step 3 to identify the items.']];
export function remainingGroupIdentity(t,rules=[],business=null){
 const text=merchantText(t.description);const service=services.find(([, ,pattern])=>pattern.test(text));if(service)return {key:'service:'+service[0],name:service[1],type:'service',hint:service[3]};
 const names=[...new Set(matchingRules(t.description,rules,t,business).map(r=>r.name))];if(names.length===1)return {key:'rule:'+normalize(names[0]),name:names[0],type:'merchant',hint:'Grouped by your saved merchant aliases. Review each purchase purpose.'};
 const name=text.replace(/\s+(?:#|store\s*#?\s*)\d{1,6}\s*$/i,'').trim(),key=normalize(name);return {key:key&&/[a-z]/.test(key)?'merchant:'+key:'record:'+t.id,name:name||'Unidentified transaction',type:'merchant',hint:'Similar descriptive wording; original bank descriptions remain below.'};
}
export function remainingGroups(transactions,rules=[],business=null){
 const groups=new Map(),seen=new Set();for(const t of transactions){if(!t.id||seen.has(t.id))continue;seen.add(t.id);const identity=remainingGroupIdentity(t,rules,business);if(!groups.has(identity.key))groups.set(identity.key,{...identity,records:[],outgoingCents:0,incomingCents:0,unknownAmounts:0,accounts:new Set(),categories:new Map()});const g=groups.get(identity.key);g.records.push(t);if(Number.isSafeInteger(t.amount)){if(t.direction==='out')g.outgoingCents+=t.amount;else if(t.direction==='in')g.incomingCents+=t.amount;else g.unknownAmounts++;}else g.unknownAmounts++;if(t.primary?.account)g.accounts.add(t.primary.account);for(const c of t.categories||[])g.categories.set(c,(g.categories.get(c)||0)+1);}
 return [...groups.values()].map(g=>({...g,records:g.records.sort((a,b)=>(a.date||'').localeCompare(b.date||'')||a.id.localeCompare(b.id)),accounts:[...g.accounts].sort(),categories:[...g.categories].map(([name,count])=>({name,count})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name))}));
}
export function merchantRuleForGroup(group,category,{categories=[],business}={}){
 if(group?.type!=='merchant'||!/[a-z]/i.test(group.name||''))throw Error('Payment services need recipient or receipt evidence, not one blanket rule.');
 if(!categories.includes(category)||/Uncategorized|Needs Review/i.test(category))throw Error('Choose an exact spending category.');
 const eligible=group.records.filter(t=>t.direction==='out'&&t.primary&&t.postings?.length===2&&t.categories?.length===1&&(!t.kind||['Unclassified','Merchant rule','Conflicting merchant rules'].includes(t.kind))&&!nonPurchaseReason(t));if(!eligible.length)throw Error('No ordinary purchases in this group can use a merchant rule.');
 return validateRule({name:group.name,aliases:[group.name],category,business,matchMode:'words',accountNames:[...new Set(eligible.map(t=>t.primary.account))],onlyCategories:[...new Set(['Uncategorized Expense',category,...eligible.flatMap(t=>t.categories).filter(c=>/Uncategorized|Needs Review/i.test(c))])],direction:'out'});
}
