import {parseCSV} from './csv.js';
export const venmoOrigins=['https://account.venmo.com/*','https://venmo.com/*'];
const iso=s=>/^\d{4}-\d{2}-\d{2}$/.test(s)&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;
export function venmoTemplate(value){const url=new URL(value);if(url.protocol!=='https:'||url.hostname!=='account.venmo.com'||url.username||url.password||!/\bstatements?\b/i.test(url.pathname)||!/download/i.test(url.pathname)||url.searchParams.get('csv')!=='true')throw Error('Use the actual CSV download from Venmo Statements. No guessed or non-statement URL is accepted.');const start=url.searchParams.get('startDate'),end=url.searchParams.get('endDate');if(!start||!end||!iso(start)||!iso(end)||!start.endsWith('-01')||end<start)throw Error('The observed statement must have a readable monthly startDate and endDate.');const next=new Date(start+'T00:00:00Z');next.setUTCMonth(next.getUTCMonth()+1);const exclusive=end===next.toISOString().slice(0,10);if(!exclusive&&end.slice(0,7)!==start.slice(0,7))throw Error('Capture one monthly statement to learn its date format.');return {url:url.href,start,end,exclusive};}
export function venmoPeriods(fromYear=2019,today){if(!Number.isInteger(fromYear)||fromYear<2019||fromYear>Number(today.slice(0,4))||!iso(today))throw Error('Choose a year from 2019 through today.');const result=[];for(let year=fromYear;year<=Number(today.slice(0,4));year++)for(let month=1;month<=12;month++){const start=year+'-'+String(month).padStart(2,'0')+'-01';if(start>today)continue;const next=new Date(Date.UTC(year,month,1)),last=new Date(next.getTime()-86400000).toISOString().slice(0,10);result.push({month:start.slice(0,7),start,end:last<today?last:today,exclusiveEnd:next.toISOString().slice(0,10),partial:last>today});}return result;}
export function venmoRequest(template,period){const validated=venmoTemplate(template.url),url=new URL(validated.url);url.searchParams.set('startDate',period.start);url.searchParams.set('endDate',validated.exclusive?period.exclusiveEnd:period.end);return url.href;}
export function validateVenmoCSV(text,period){if(typeof text!=='string'||text.length>25*1024*1024||/^\s*[<{]/.test(text))throw Error('Venmo returned a login/error page or an oversized response, not a statement CSV.');const rows=parseCSV(text),norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]/g,'');const index=rows.findIndex(r=>r.some(c=>norm(c)==='id')&&r.some(c=>['datetime','date'].includes(norm(c)))&&r.some(c=>norm(c)==='type')&&r.some(c=>/^amount/.test(norm(c))));if(index<0)throw Error('The response has no recognizable Venmo statement header. Nothing saved.');const header=rows[index],dateIndex=header.findIndex(c=>['datetime','date'].includes(norm(c))),idIndex=header.findIndex(c=>norm(c)==='id');let count=0;for(const row of rows.slice(index+1)){if(!row[idIndex]?.trim())continue;const value=row[dateIndex]?.trim()||'',match=value.match(/^(\d{4}-\d{2}-\d{2})/)||value.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/);const date=match?(match.length===2?match[1]:match[3]+'-'+match[1].padStart(2,'0')+'-'+match[2].padStart(2,'0')):'';if(!date||!iso(date)||date<period.start||date>period.end)throw Error('Statement transaction dates do not match the requested month. Nothing saved.');count++;}return {count,empty:count===0};}
export async function venmoDigest(text){const bytes=new TextEncoder().encode(text),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function saveVenmoCSV(root,profile,period,text){if(!['personal','business'].includes(profile))throw Error('Unknown Venmo profile.');const verified=validateVenmoCSV(text,period),hash=await venmoDigest(text),dir=await root.getDirectoryHandle(profile,{create:true}),year=await dir.getDirectoryHandle(period.start.slice(0,4),{create:true});const base='venmo-'+profile+'-'+period.month;let name=base+'.csv';try{const existing=await year.getFileHandle(name);if(await venmoDigest(await (await existing.getFile()).text())===hash)return {name:profile+'/'+period.start.slice(0,4)+'/'+name,hash,...verified,reused:true};name=base+'-'+hash.slice(0,16)+'.csv';try{const hashed=await year.getFileHandle(name);if(await venmoDigest(await(await hashed.getFile()).text())!==hash)throw Error('A conflicting statement filename already exists; no file overwritten.');return {name:profile+'/'+period.start.slice(0,4)+'/'+name,hash,...verified,reused:true};}catch(e){if(e.name!=='NotFoundError')throw e;}}catch(e){if(e.name!=='NotFoundError')throw e;}const handle=await year.getFileHandle(name,{create:true});const stream=await handle.createWritable();try{await stream.write(text);await stream.close();}catch(e){await stream.abort?.();throw e;}return {name:profile+'/'+period.start.slice(0,4)+'/'+name,hash,...verified,reused:false};}
export async function collectVenmoProfile({source,profile,periods,entries={},read,save,persist,current=()=>true,progress=()=>{},verifySaved=async()=>false}){const next={...entries};for(let index=0;index<periods.length;index++){if(!current())return {entries:next,stopped:true};const period=periods[index],key=profile+':'+period.start+':'+period.end;progress(index,periods.length,period);if(next[key]?.hash&&next[key]?.name&&!period.partial&&await verifySaved(next[key]))continue;const text=await read(venmoRequest(source,period),period);if(!current())return {entries:next,stopped:true};if(text?.unavailable&&[204,404,410].includes(text.httpStatus)){next[key]={status:'unavailable',httpStatus:text.httpStatus,profile,month:period.month,start:period.start,end:period.end,checkedAt:new Date().toISOString()};await persist(next);continue;}validateVenmoCSV(text,period);const result=await save(profile,period,text);next[key]={...result,profile,month:period.month,start:period.start,end:period.end,savedAt:new Date().toISOString()};await persist(next);if(!current())return {entries:next,stopped:true};}progress(periods.length,periods.length);return {entries:next,stopped:false};}

// Completed recent months come first; the current partial month is attempted last.
export function venmoCollectionPeriods(fromYear,today,fromMonth=1){if(!Number.isInteger(fromMonth)||fromMonth<1||fromMonth>12)throw Error('Choose a valid starting month.');const start=fromYear+'-'+String(fromMonth).padStart(2,'0');const periods=venmoPeriods(fromYear,today).filter(p=>p.month>=start);if(!periods.length)throw Error('The starting month must not be after today.');return periods.filter(p=>!p.partial).reverse().concat(periods.filter(p=>p.partial));}
export function venmoStatementPage(today){if(!iso(today))throw Error('Choose a valid statement date.');const date=new Date(today+'T00:00:00Z');date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()-1);const url=new URL('https://account.venmo.com/statement');url.searchParams.set('month',String(date.getUTCMonth()+1));url.searchParams.set('profileId','all-profiles-id');url.searchParams.set('year',String(date.getUTCFullYear()));return url.href;}
export async function waitForVenmoControls(read,{attempts=20,pause=()=>new Promise(resolve=>setTimeout(resolve,300))}={}){let info;for(let i=0;i<attempts;i++){info=await read();if(info?.downloads?.some(d=>!d.tax)||info?.links?.length)return info;if(i+1<attempts)await pause();}let month='this month';try{const url=new URL(info.pageURL);if(url.searchParams.get('year')&&url.searchParams.get('month'))month=url.searchParams.get('year')+'-'+url.searchParams.get('month').padStart(2,'0');}catch{}throw Error('Venmo shows no transaction Download CSV buttons for '+month+'. The month may be unavailable or the page may still be loading. Choose a completed month with Download CSV buttons, then capture both sources. No collection has started.');}

export function venmoReadiness({real=true,connected=false,folder=null,sources={},busy=false,captureProblem=false}={}){const missing=[];if(!real)missing.push({action:null,text:'Open this page from the installed Chrome extension.'});if(!connected)missing.push({action:'connect',text:'Connect Venmo to allow statement access.'});if(!folder)missing.push({action:'folder',text:'Choose your data/venmo destination folder.'});for(const profile of ['personal','business'])if(!sources[profile])missing.push({action:profile,text:'Capture the '+profile+' statement source.'});if(captureProblem)missing.push({action:'both',text:'Choose a completed month with Download CSV buttons and capture again.'});return {ready:!busy&&!missing.length,busy,missing};}
