// Injected read-only statement access. Uses an observed Venmo CSV URL, never payment actions.
export async function venmoPage(request){
 const evidence=()=>{const parts=[...document.querySelectorAll('nav,[role=navigation],header')].map(e=>e.innerText?.trim()).filter(Boolean);return (parts.join(' | ')||document.body?.innerText?.slice(0,2000)||'').replace(/\s+/g,' ').trim().slice(0,3000);};
 const context=()=>({origin:location.origin,path:location.pathname,pageURL:location.href,evidence:evidence(),statementPage:/statements?/i.test(document.body?.innerText||'')});const before=context();
 if(!['https://account.venmo.com','https://venmo.com'].includes(before.origin))throw Error('Open the signed-in Venmo Statements page.');
 if(request.action==='read')return {...before,links:[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>{try{const u=new URL(h);return u.hostname==='account.venmo.com'&&/statements?.*download/i.test(u.pathname)&&u.searchParams.get('csv')==='true';}catch{return false;}}),controls:[...document.querySelectorAll('button,[role=button]')].map(e=>({text:(e.innerText||e.getAttribute('aria-label')||'').trim().slice(0,150),html:e.outerHTML.slice(0,1800)})).filter(e=>/profile|statement|download|personal|business/i.test(e.text)).slice(0,25)};
 if(request.action==='sample'){const targets=[...document.querySelectorAll('a,button,[role=button]')].filter(e=>e.getClientRects().length&&(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()==='download csv');if(targets.length!==1)throw Error('Cannot identify one visible Download CSV control. Copy the statement controls.');targets[0].click();return {clicked:true};}
 if(request.action==='switch'){const target=request.profile==='business'?'Switch to business profile':'Switch to personal profile';const buttons=[...document.querySelectorAll('button,[role=button]')].filter(e=>(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()===target.toLowerCase());if(buttons.length!==1)return {switched:false};buttons[0].click();return {switched:true};}
 if(request.action!=='download')throw Error('Unsupported statement action.');const url=new URL(request.url);if(url.protocol!=='https:'||url.hostname!=='account.venmo.com'||url.username||url.password||!/statements?.*download/i.test(url.pathname)||url.searchParams.get('csv')!=='true')throw Error('Only the observed Venmo statement download endpoint is allowed.');if(!before.statementPage||!before.evidence||before.evidence!==request.evidence||before.origin!==request.origin||before.path!==request.path||before.pageURL!==request.pageURL)throw Error('The selected profile/page changed. Switch back to the captured profile or capture it again.');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url.href,{credentials:'include',redirect:'error',signal:controller.signal});if([204,404,410].includes(response.status)){if(evidence()!==before.evidence||location.href!==before.pageURL)throw Error('Profile changed during availability check.');return {unavailable:true,httpStatus:response.status};}if(!response.ok)throw Error('Venmo statement request returned HTTP '+response.status+'. Sign in again or check availability; no file saved.');if(Number(response.headers.get('content-length'))>25*1024*1024)throw Error('Statement exceeds 25 MB.');let length=0;const reader=response.body.getReader(),decoder=new TextDecoder(),chunks=[];while(true){const {value,done}=await reader.read();if(done)break;length+=value.byteLength;if(length>25*1024*1024){await reader.cancel();throw Error('Statement exceeds 25 MB.');}chunks.push(decoder.decode(value,{stream:true}));}chunks.push(decoder.decode());if(evidence()!==before.evidence||location.pathname!==before.path||location.href!==before.pageURL)throw Error('Profile changed during the request; nothing saved.');return {text:chunks.join('')};}finally{clearTimeout(timeout);}
}
