// Injected read-only statement access. Uses an observed Venmo CSV URL, never payment actions.
export async function venmoPage(request){
 const csvControls=()=>[...document.querySelectorAll('a,button,[role=button]')].filter(e=>e.getClientRects().length&&(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()==='download csv');
 const inventory=()=>{const controls=csvControls();return controls.map((e,index)=>{let node=e.parentElement,section='';for(let depth=0;node&&depth<10;depth++,node=node.parentElement){const text=(node.innerText||'').replace(/\s+/g,' ').trim(),count=controls.filter(c=>node.contains(c)).length;if(count>1)break;section=text;if(/@[a-z0-9_]+|sales tax collected/i.test(text))break;}return {index,section:section.slice(0,1800),handles:[...new Set(section.match(/@[a-z0-9_]+/gi)||[])],tax:/sales tax collected/i.test(section)};});};
 const allProfiles=()=>/all profiles/i.test(document.body?.innerText||'');
 const profileControl=profile=>{const rows=inventory().filter(r=>!r.tax);if(!allProfiles()||rows.length!==2||rows.some(r=>r.handles.length!==1)||rows[0].handles[0].toLowerCase()===rows[1].handles[0].toLowerCase())throw Error('Cannot distinguish two profile transaction downloads. Read statement controls; sales-tax downloads are excluded.');return rows[profile==='personal'?0:1];};
 const evidence=()=>{const parts=[...document.querySelectorAll('nav,[role=navigation],header')].map(e=>e.innerText?.trim()).filter(Boolean);return (parts.join(' | ')||document.body?.innerText?.slice(0,2000)||'').replace(/\s+/g,' ').trim().slice(0,3000);};
 const context=()=>({allProfiles:allProfiles(),downloads:inventory(),origin:location.origin,path:location.pathname,pageURL:location.href,evidence:evidence(),statementPage:/statements?/i.test(document.body?.innerText||'')});const before=context();
 if(!['https://account.venmo.com','https://venmo.com'].includes(before.origin))throw Error('Open the signed-in Venmo Statements page.');
 if(request.action==='read')return {...before,links:[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(h=>{try{const u=new URL(h);return u.hostname==='account.venmo.com'&&/statements?.*download/i.test(u.pathname)&&u.searchParams.get('csv')==='true';}catch{return false;}}),controls:[...document.querySelectorAll('button,[role=button]')].map(e=>({text:(e.innerText||e.getAttribute('aria-label')||'').trim().slice(0,150),html:e.outerHTML.slice(0,1800)})).filter(e=>/profile|statement|download|personal|business/i.test(e.text)).slice(0,25)};
 if(request.action==='sample'&&allProfiles()){if(!['personal','business'].includes(request.profile))throw Error('Choose Personal or Business for the All profiles download.');const chosen=profileControl(request.profile);csvControls()[chosen.index].click();return {clicked:true,profile:request.profile,handle:chosen.handles[0]};}
 if(request.action==='sample'){const targets=[...document.querySelectorAll('a,button,[role=button]')].filter(e=>e.getClientRects().length&&(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()==='download csv');if(targets.length!==1)throw Error('Cannot identify one visible Download CSV control. Copy the statement controls.');targets[0].click();return {clicked:true};}
 if(request.action==='switch'){const target=request.profile==='business'?'Switch to business profile':'Switch to personal profile';const buttons=[...document.querySelectorAll('button,[role=button]')].filter(e=>(e.innerText||e.getAttribute('aria-label')||'').trim().toLowerCase()===target.toLowerCase());if(buttons.length!==1)return {switched:false};buttons[0].click();return {switched:true};}
 if(request.action==='nativeCSV'){
  const route=new URL(location.href),month=route.searchParams.get('year')+'-'+String(route.searchParams.get('month')).padStart(2,'0');if(route.origin!=='https://account.venmo.com'||route.pathname!=='/statement'||route.searchParams.get('profileId')!=='all-profiles-id'||month!==request.month)throw Error('The selected statement month changed. Nothing saved.');const chosen=profileControl(request.profile);if(chosen.handles[0].toLowerCase()!==String(request.handle).toLowerCase())throw Error('The statement profile changed. Nothing saved.');const control=csvControls()[chosen.index];if(control.disabled||control.getAttribute('aria-disabled')==='true')throw Error('The transaction CSV control is disabled.');
  const original=URL.createObjectURL,found=[],capturedURLs=new Set(),anchorPrototype=typeof HTMLAnchorElement==='undefined'?null:HTMLAnchorElement.prototype,originalClick=anchorPrototype?.click;let error=null;if(anchorPrototype)anchorPrototype.click=function(){if((this.hasAttribute?.('download')||this.download)&&capturedURLs.has(this.href))return;return originalClick.call(this);};URL.createObjectURL=function(blob){const url=original.call(this,blob);if(blob instanceof Blob&&(!blob.type||/csv|text\/plain|octet-stream/i.test(blob.type))){capturedURLs.add(url);if(blob.size>25*1024*1024)error=Error('Statement exceeds 25 MB.');else blob.text().then(text=>{if(/\bID\b/i.test(text)&&/\b(?:Datetime|Date)\b/i.test(text)&&/\bType\b/i.test(text)&&/\bAmount/i.test(text))found.push(text);}).catch(e=>error=e);}return url;};try{control.click();for(let i=0;i<100&&!found.length&&!error;i++)await new Promise(r=>setTimeout(r,200));if(error)throw error;if(!found.length)throw Error('Venmo did not expose a recognizable CSV file from this download. Nothing saved to the project; copy statement diagnostics.');await new Promise(r=>setTimeout(r,200));if(found.length!==1)throw Error('Multiple CSV files appeared from one profile download. Nothing saved.');if(location.href!==before.pageURL||profileControl(request.profile).handles[0].toLowerCase()!==String(request.handle).toLowerCase())throw Error('Statement page changed during download. Nothing saved.');return {text:found[0]};}finally{URL.createObjectURL=original;if(anchorPrototype)anchorPrototype.click=originalClick;}
 }
 if(request.action!=='download')throw Error('Unsupported statement action.');const url=new URL(request.url);if(url.protocol!=='https:'||url.hostname!=='account.venmo.com'||url.username||url.password||!/statements?.*download/i.test(url.pathname)||url.searchParams.get('csv')!=='true')throw Error('Only the observed Venmo statement download endpoint is allowed.');if(!before.statementPage||!before.evidence||before.evidence!==request.evidence||before.origin!==request.origin||before.path!==request.path||before.pageURL!==request.pageURL)throw Error('The selected profile/page changed. Switch back to the captured profile or capture it again.');
 if(request.allProfiles&&(!allProfiles()||JSON.stringify(inventory())!==JSON.stringify(request.downloads)))throw Error('The All profiles statement controls changed; capture both sources again.');
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(url.href,{credentials:'include',redirect:'error',signal:controller.signal});if([204,404,410].includes(response.status)){if(evidence()!==before.evidence||location.href!==before.pageURL||(request.allProfiles&&JSON.stringify(inventory())!==JSON.stringify(request.downloads)))throw Error('Profile changed during availability check.');return {unavailable:true,httpStatus:response.status};}if(!response.ok)throw Error('Venmo statement request returned HTTP '+response.status+'. Sign in again or check availability; no file saved.');if(Number(response.headers.get('content-length'))>25*1024*1024)throw Error('Statement exceeds 25 MB.');let length=0;const reader=response.body.getReader(),decoder=new TextDecoder(),chunks=[];while(true){const {value,done}=await reader.read();if(done)break;length+=value.byteLength;if(length>25*1024*1024){await reader.cancel();throw Error('Statement exceeds 25 MB.');}chunks.push(decoder.decode(value,{stream:true}));}chunks.push(decoder.decode());if(evidence()!==before.evidence||location.pathname!==before.path||location.href!==before.pageURL||(request.allProfiles&&JSON.stringify(inventory())!==JSON.stringify(request.downloads)))throw Error('Profile changed during the request; nothing saved.');return {text:chunks.join('')};}finally{clearTimeout(timeout);}
}
