const make=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
function debugRoot(){let root=document.getElementById('debugWorkspace');if(!root){root=make('div');root.id='debugWorkspace';root.hidden=true;root.setAttribute('role','tabpanel');root.setAttribute('aria-label','Debug tools');root.append(make('h2','Debug tools'),make('p','Diagnostics and manual troubleshooting tools. Reports stay local and may contain accounting details.'));const footer=document.querySelector('main footer');if(footer)footer.before(root);else document.querySelector('main').append(root);}return root;}
export function debugSlot(id,title){let body=document.getElementById(id);if(!body){const card=make('details');card.className='debug-card';const summary=make('summary',title);body=make('div');body.id=id;body.className='debug-body';card.append(summary,body);debugRoot().append(card);}return body;}
export function showWorkspace(name='usage'){const usage=document.getElementById('usageWorkspace'),debug=debugRoot();if(usage)usage.hidden=name!=='usage';debug.hidden=name!=='debug';for(const button of document.querySelectorAll('[data-workspace]')){const selected=button.dataset.workspace===name;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;}}
export function showDebug(id){showWorkspace('debug');const slot=document.getElementById(id);if(slot){slot.parentElement.open=true;slot.parentElement.scrollIntoView({block:'start'});slot.parentElement.querySelector('summary').tabIndex=-1;slot.parentElement.querySelector('summary').focus({preventScroll:true});}}
export function debugLink(id,label='View diagnostics'){const button=make('button',label);button.type='button';button.className='secondary';button.onclick=()=>showDebug(id);return button;}
export function installWorkspace(){
 const main=document.querySelector('main'),usage=make('div');const notice=[...main.children].find(node=>node.classList.contains('notice'));if(notice)notice.textContent='Work from a fresh export. Collect your live backlog, prepare approved matches, and run only the transactions you select. Your session stays saved locally.';const badge=main.querySelector('header .badge');if(badge)badge.textContent='WAVE COMPANION';usage.id='usageWorkspace';usage.setAttribute('role','tabpanel');usage.setAttribute('aria-label','Usage');
 const sections=[...main.children].filter(n=>n.tagName==='SECTION');const footer=main.querySelector('footer');if(footer)footer.before(usage);else main.append(usage);
 const nav=make('nav');nav.className='workspace-nav';nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Solver workspace');
 for(const [name,label] of [['usage','Usage'],['debug','Debug tools']]){const button=make('button',label);button.type='button';button.dataset.workspace=name;button.setAttribute('role','tab');button.id=name+'-tab';button.setAttribute('aria-controls',name==='usage'?'usageWorkspace':'debugWorkspace');button.onclick=()=>showWorkspace(name);button.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?'usage':event.key==='End'?'debug':name==='usage'?'debug':'usage';showWorkspace(next);document.getElementById(next+'-tab').focus();}};nav.append(button);}
 document.getElementById('sessionStatus').after(nav);usage.setAttribute('aria-labelledby','usage-tab');debugRoot().setAttribute('aria-labelledby','debug-tab');
 const assigned=new Set();
 for(const [id,title,description,keys] of [
  ['setup','Set up your session','Choose a business, import your export, and load category names.',['fold-setup','fold-import','fold-chart']],
  ['transactions','Work through transactions','Collect the live backlog, prepare known expenses, or process matching transfers.',['liveList','waveSuggestions','expenseBatch','fold-transfers','fold-live']],
  ['rules','Manage merchant rules','Keep approved rules current and review new proposals.',['fold-merchant','fold-proposals','fold-history']],
  ['planning','Inspect and plan','Review individual proposals and keep a draft for later.',['fold-queue','fold-plan']]]){
  const group=make('div');group.className='workflow-group';group.id='usage-'+id;const heading=make('h2',title);heading.className='group-title';group.append(heading,make('p',description));
  for(const key of keys){const panel=document.getElementById(key)?.closest('section');if(panel){group.append(panel);assigned.add(panel);}}usage.append(group);
 }
 for(const section of sections)if(!assigned.has(section))usage.append(section);
 for(const summary of usage.querySelectorAll('.step>summary[role=heading]')){const text=summary.textContent;summary.removeAttribute('role');summary.removeAttribute('aria-level');const arrow=make('span','▸');arrow.className='step-arrow';arrow.setAttribute('aria-hidden','true');const title=make('span',text);title.className='step-title';title.setAttribute('role','heading');title.setAttribute('aria-level','2');summary.replaceChildren(arrow,title);}
 for(const heading of usage.querySelectorAll('.step-title'))heading.textContent=heading.textContent.replace(/^\d+\.\s*/, '');
 const liveTitle=usage.querySelector('#fold-live .step-title');if(liveTitle)liveTitle.textContent='Live transaction check';if(footer)footer.textContent='Export → collect → prepare → run → verify.';
 const chart=debugSlot('chartTools','Chart of Accounts diagnostics');chart.append(make('p','Collect category names in Usage to populate the chart report.'),document.getElementById('chartDebug'));document.getElementById('readChart').parentElement.append(debugLink('chartTools','View chart diagnostics'));
 const live=debugSlot('liveTools','Live transaction diagnostics'),pre=document.getElementById('diagnostics'),buttons=document.getElementById('diagnosticToggle').closest('.bar');live.append(make('p','Inspect a transaction in Usage, then read its live details to populate these diagnostics.'),buttons,pre);document.getElementById('read').parentElement.append(debugLink('liveTools','View live diagnostics'));
 const sample=document.getElementById('sample');if(sample)debugSlot('sampleTools','Fictional sample').append(make('p','Load fictional data to explore the interface. Sample records cannot edit Wave.'),sample);
 showWorkspace('usage');
}
