import {loadSession} from './session.js';
const delay=()=>new Promise(resolve=>setTimeout(resolve,100));
document.getElementById('run').onclick=async()=>{
 if(!(await loadSession())?.csvText){document.getElementById('result').textContent='Seed the fictional integration session in proposal-fixture.html first, then run these checks.';return;}
 const output=document.getElementById('checks');output.replaceChildren();const mount=document.getElementById('preview');mount.replaceChildren();let passed=0,failed=0;
 const frame=document.createElement('iframe');frame.title='Fictional solver workspace';frame.style.cssText='width:960px;height:800px;max-width:none;border:1px solid #4a5870';frame.src='integration-fixture.html';mount.append(frame);
 async function check(name,task){try{await task();passed++;const li=document.createElement('li');li.textContent='PASS '+name;output.append(li);}catch(e){failed++;const li=document.createElement('li');li.textContent='FAIL '+name+': '+e.message;output.append(li);}}
 for(let i=0;i<50 && !frame.contentDocument?.getElementById('sessionStatus')?.textContent.includes('Previous session restored');i++)await delay();const doc=frame.contentDocument,win=frame.contentWindow;
 const assert=(value,message)=>{if(!value)throw Error(message);};
 await check('Usage starts selected, with five stages and only one visible',()=>{assert(!doc.querySelector('#usageWorkspace').hidden,'Usage is hidden');assert(doc.querySelector('#debugWorkspace').hidden,'Debug starts visible');assert(doc.querySelectorAll('.workflow-group').length===5,'Missing stages');assert([...doc.querySelectorAll('.workflow-group')].filter(g=>!g.hidden).length===1,'More than one stage visible');assert(doc.querySelectorAll('.usage-step').length===5,'Missing navigation');});
 await check('Diagnostic controls stay in Debug and IDs remain unique',()=>{const debug=doc.querySelector('#debugWorkspace');for(const id of ['chartDebug','diagnostics','copyDiagnostics'])assert(debug.contains(doc.getElementById(id)),id+' is outside Debug');const ids=[...doc.querySelectorAll('[id]')].map(n=>n.id);assert(new Set(ids).size===ids.length,'Duplicate DOM IDs');assert(![...doc.querySelectorAll('#usageWorkspace button')].some(b=>/^Copy .*diagnostics$/.test(b.textContent)),'Copy tools remain in Usage');});
 await check('Debug navigation preserves the loaded session and returns with keyboard arrows',()=>{const before=doc.getElementById('importStatus').textContent,debug=doc.getElementById('debug-tab');debug.click();assert(doc.querySelector('#usageWorkspace').hidden,'Usage did not hide');assert(!doc.querySelector('#debugWorkspace').hidden,'Debug did not open');assert(doc.getElementById('importStatus').textContent===before,'Session changed');debug.dispatchEvent(new win.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));assert(!doc.querySelector('#usageWorkspace').hidden,'ArrowLeft did not return to Usage');assert(doc.getElementById('usage-tab').getAttribute('aria-selected')==='true','Usage tab not selected');});
 await check('Usage checkboxes keep an inline consistent layout',()=>{doc.querySelector('.usage-step[data-stage=transactions]').click();doc.getElementById('expenseBatch').open=true;assert(doc.querySelectorAll('#expenseBatch label:has(input[type=checkbox])').length>0,'Seed approved fictional rules first to populate expense controls');for(const label of doc.querySelectorAll('#expenseBatch label:has(input[type=checkbox])')){assert(win.getComputedStyle(label).display==='flex','Checkbox label stacks');assert(parseFloat(win.getComputedStyle(label.querySelector('input')).width)===17,'Checkbox width changed');}});
 await check('Next and Previous switch stages without scanning or running transactions',()=>{doc.querySelector('.usage-step[data-stage=rules]').click();doc.querySelector('.usage-controls button:last-child').click();assert(!doc.getElementById('usage-transactions').hidden,'Next did not open approved work');doc.querySelector('.usage-controls button:first-child').click();assert(!doc.getElementById('usage-rules').hidden,'Previous did not restore rules');assert(!doc.querySelector('.transfer-run-progress'),'Navigation began a run');});
 await check('Inspect opens the individual check stage and Prepare rules opens the custom editor',()=>{doc.querySelector('.usage-step[data-stage=planning]').click();doc.getElementById('fold-queue').open=true;const inspect=[...doc.querySelectorAll('#rows button')].find(b=>b.textContent==='Inspect');assert(inspect,'No inspect control');inspect.click();assert(!doc.getElementById('usage-planning').hidden && doc.getElementById('fold-live').open,'Live stage not revealed');doc.querySelector('.usage-step[data-stage=rules]').click();doc.getElementById('fold-history').open=true;const prepare=[...doc.querySelectorAll('#historyRows button')].find(b=>b.textContent==='Prepare individually');if(prepare){prepare.click();assert(doc.getElementById('customRule').open,'Custom editor stayed collapsed');assert(doc.getElementById('fold-merchant').open,'Current rules stayed collapsed');}});
 for(const width of [960,390,320])await check('No document overflow at '+width+'px in Usage and Debug',async()=>{frame.style.width=width+'px';for(const d of doc.querySelectorAll('details'))d.open=true;await delay();for(const button of doc.querySelectorAll('.usage-step')){button.click();await delay();assert(doc.documentElement.scrollWidth<=doc.documentElement.clientWidth+1,'Usage overflow at '+width+' in '+button.dataset.stage);}doc.getElementById('debug-tab').click();await delay();assert(doc.documentElement.scrollWidth<=doc.documentElement.clientWidth+1,'Debug overflow at '+width);doc.getElementById('usage-tab').click();});
 document.getElementById('result').textContent=passed+' passed, '+failed+' failed';
};