import {usageStages,usageReadiness,initialUsageStage} from './usage-flow.js';
let usageController=null;
const make=(tag,text)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;return node;};
function debugRoot(){let root=document.getElementById('debugWorkspace');if(!root){root=make('div');root.id='debugWorkspace';root.hidden=true;root.setAttribute('role','tabpanel');root.setAttribute('aria-label','Debug tools');root.append(make('h2','Advanced tools'),make('p','Diagnostics, manual troubleshooting and optional draft exports. The draft is a shortlist, not a batch executor. Reports stay local.'));const footer=document.querySelector('main footer');if(footer)footer.before(root);else document.querySelector('main').append(root);}return root;}
export function debugSlot(id,title){let body=document.getElementById(id);if(!body){const card=make('details');card.className='debug-card';const summary=make('summary',title);body=make('div');body.id=id;body.className='debug-body';card.append(summary,body);debugRoot().append(card);}return body;}
export function showWorkspace(name='usage'){const usage=document.getElementById('usageWorkspace'),debug=debugRoot();if(usage)usage.hidden=name!=='usage';debug.hidden=name!=='debug';for(const button of document.querySelectorAll('[data-workspace]')){const selected=button.dataset.workspace===name;button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;}}
export function showDebug(id){showWorkspace('debug');const slot=document.getElementById(id);if(slot){slot.parentElement.open=true;slot.parentElement.scrollIntoView({block:'start'});slot.parentElement.querySelector('summary').tabIndex=-1;slot.parentElement.querySelector('summary').focus({preventScroll:true});}}
export function debugLink(id,label='View diagnostics'){const button=make('button',label);button.type='button';button.className='secondary';button.onclick=()=>showDebug(id);return button;}
export function showUsageSection(id){showWorkspace('usage');const target=document.getElementById(id),group=target?.closest('.workflow-group');if(group)usageController?.open(group.dataset.stage,{panel:target?.tagName==='DETAILS'?id:undefined});if(target?.tagName==='DETAILS')target.open=true;}
export function installWorkspace({getState=()=>({}),onStageChange=()=>{}}={}){
 const main=document.querySelector('main'),usage=make('div');const notice=[...main.children].find(node=>node.classList.contains('notice'));if(notice)notice.textContent='Select the work you recognize. The solver checks each record in Wave, saves the selected change, and verifies the result.';const badge=main.querySelector('header .badge');if(badge)badge.textContent='WAVE COMPANION';usage.id='usageWorkspace';usage.setAttribute('role','tabpanel');usage.setAttribute('aria-label','Usage');
 const draftSection=document.getElementById('fold-plan')?.closest('section');if(draftSection)debugSlot('draftTools','Optional draft shortlist and export').append(draftSection);
 const queueTitle=document.querySelector('#fold-queue .step-title');if(queueTitle)queueTitle.textContent='Remaining transactions';
 const sections=[...main.children].filter(n=>n.tagName==='SECTION');const footer=main.querySelector('footer');if(footer)footer.before(usage);else main.append(usage);
 const nav=make('nav');nav.className='workspace-nav';nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Solver workspace');
 for(const [name,label] of [['usage','Bookkeeping'],['debug','Advanced tools']]){const button=make('button',label);button.type='button';button.dataset.workspace=name;button.setAttribute('role','tab');button.id=name+'-tab';button.setAttribute('aria-controls',name==='usage'?'usageWorkspace':'debugWorkspace');button.onclick=()=>showWorkspace(name);button.onkeydown=event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const next=event.key==='Home'?'usage':event.key==='End'?'debug':name==='usage'?'debug':'usage';showWorkspace(next);document.getElementById(next+'-tab').focus();}};nav.append(button);}
 document.getElementById('sessionStatus').after(nav);usage.setAttribute('aria-labelledby','usage-tab');debugRoot().setAttribute('aria-labelledby','debug-tab');
 const assigned=new Set(),groups=new Map(),stageButtons=new Map();
 const steps=make('nav');steps.className='usage-steps';steps.setAttribute('aria-label','Bookkeeping steps');usage.append(steps);
 const guidance=make('div');guidance.className='usage-guidance';const eyebrow=make('strong','Your next move');eyebrow.className='guidance-label';guidance.append(eyebrow);const instruction=make('p'),nextTop=make('button');guidance.append(instruction,nextTop);usage.append(guidance);const overview=make('div');overview.className='workflow-overview';overview.setAttribute('aria-label','Live session overview');usage.append(overview);
 for(const [index,stage] of usageStages.entries()){
  const button=make('button');button.type='button';button.className='usage-step';button.dataset.stage=stage.id;const number=make('span',String(index+1));number.className='usage-number';const text=make('span'),label=make('strong',stage.label),status=make('small');status.id='usage-status-'+stage.id;text.append(label,status);button.append(number,text);button.onclick=()=>usageController.open(stage.id,{focus:true});steps.append(button);stageButtons.set(stage.id,button);
  const group=make('div');group.className='workflow-group';group.id='usage-'+stage.id;group.dataset.stage=stage.id;const heading=make('h2',stage.title);heading.className='group-title';heading.tabIndex=-1;group.append(heading);
  for(const key of stage.panels){const panel=document.getElementById(key)?.closest('section');if(panel){group.append(panel);assigned.add(panel);}}usage.append(group);groups.set(stage.id,group);
 }
 const controls=make('div');controls.className='usage-controls bar';const previous=make('button','Previous step'),nextBottom=make('button');previous.className='secondary';controls.append(previous,nextBottom);usage.append(controls);
 let active='setup',seenBusiness=getState().business,setupRequirement=null;
 function refresh(){const state=getState(),readiness=usageReadiness(state),index=usageStages.findIndex(s=>s.id===active),stage=usageStages[index];
  if(seenBusiness!==state.business){seenBusiness=state.business;active='setup';return refresh();}
  for(const s of usageStages){const selected=s.id===active;groups.get(s.id).hidden=!selected;stageButtons.get(s.id).setAttribute('aria-current',selected?'step':'false');stageButtons.get(s.id).classList.toggle('is-current',selected);stageButtons.get(s.id).classList.toggle('is-done',(s.id==='setup'||s.id==='collection')&&readiness[s.id].ready);const badge=document.getElementById('usage-status-'+s.id);badge.textContent=readiness[s.id].text;badge.classList.toggle('complete',(s.id==='setup'||s.id==='collection')&&readiness[s.id].ready);}
  const requirement=active==='setup' && !readiness.setup.ready?(!state.business?'fold-setup':'fold-import'):null;if(requirement && requirement!==setupRequirement){for(const key of usageStages[0].panels){const fold=document.getElementById(key);if(fold)fold.open=key===requirement;}}setupRequirement=requirement;
  const stateReport=state.report,liveRows=(stateReport?.records || []).filter(r=>r.date>=(state.workFrom || '2025-01-01') && r.reviewed!=='Reviewed');overview.replaceChildren();for(const [value,label] of [[stateReport?liveRows.length:'—','Records in last collection'],[state.expenseMatches ?? 0,'Approved expense matches'],[state.transferMatches ?? 0,'Transfer candidates']]){const item=make('div');item.append(make('strong',String(value)),make('span',label));overview.append(item);}const note=make('p',stateReport?'Last live collection: '+new Date(stateReport.capturedAt).toLocaleString()+'. Rescan after running work.':'Start with a live collection. CSV counts are history, not unfinished tasks.');overview.append(note);
  instruction.textContent=stage.description+(active==='setup' && !readiness.setup.ready?' Select a business and import the CSV to continue.':'');previous.disabled=index===0;nextTop.textContent=nextBottom.textContent=stage.next;nextTop.disabled=nextBottom.disabled=(active!=='planning' && !readiness.setup.ready)||(active==='collection' && !readiness.collection.ready)||!!state.busy;
  if(active!=='setup' && !readiness.setup.ready)instruction.textContent+=' Complete Set up before continuing.';
  if(active==='collection' && !readiness.collection.ready)instruction.textContent+=' Click Collect Not Reviewed transactions below. You can revisit any step using the bar.';
 }
 function open(id,{focus=false,save=true,panel,preservePanel=false}={}){if(!groups.has(id))return;const changed=active!==id;active=id;refresh();const state=getState(),stage=usageStages.find(s=>s.id===id),prior=preservePanel?stage.panels.find(key=>document.getElementById(key)?.open):null;const leadId=panel || prior || (id==='setup'?(!state.business?'fold-setup':!state.dataset?'fold-import':null):id==='transactions' && !state.transferMatches && state.expenseMatches?'expenseBatch':stage.panels[0]);for(const key of stage.panels){const fold=document.getElementById(key);if(fold)fold.open=key===leadId;}if(focus){const heading=groups.get(active).querySelector('h2');heading.scrollIntoView({block:'start',behavior:'smooth'});heading.focus({preventScroll:true});}if(changed&&save)onStageChange(active);}
 const advance=()=>open(usageStages[(usageStages.findIndex(s=>s.id===active)+1)%usageStages.length].id,{focus:true});nextTop.onclick=nextBottom.onclick=advance;previous.onclick=()=>open(usageStages[Math.max(0,usageStages.findIndex(s=>s.id===active)-1)].id,{focus:true});
 usageController={open,refresh,current:()=>active,restore:saved=>open(initialUsageStage(getState(),saved),{save:false,preservePanel:usageStages.some(s=>s.id===saved)})};
 for(const section of sections)if(!assigned.has(section))usage.append(section);
 for(const summary of usage.querySelectorAll('.step>summary[role=heading]')){const text=summary.textContent;summary.removeAttribute('role');summary.removeAttribute('aria-level');const arrow=make('span','▸');arrow.className='step-arrow';arrow.setAttribute('aria-hidden','true');const title=make('span',text);title.className='step-title';title.setAttribute('role','heading');title.setAttribute('aria-level','2');summary.replaceChildren(arrow,title);}
 for(const heading of usage.querySelectorAll('.step-title'))heading.textContent=heading.textContent.replace(/^\d+\.\s*/, '');
 const liveTitle=usage.querySelector('#fold-live .step-title');if(liveTitle)liveTitle.textContent='Live transaction check';if(footer)footer.textContent='Import → collect and inspect → approve rules → run selected work → resolve and rescan.';
 const chart=debugSlot('chartTools','Chart of Accounts diagnostics');chart.append(make('p','Collect category names in Usage to populate the chart report.'),document.getElementById('chartDebug'));document.getElementById('readChart').parentElement.append(debugLink('chartTools','View chart diagnostics'));
 const live=debugSlot('liveTools','Live transaction diagnostics'),pre=document.getElementById('diagnostics'),buttons=document.getElementById('diagnosticToggle').closest('.bar');live.append(make('p','Inspect a transaction in Usage, then read its live details to populate these diagnostics.'),buttons,pre);document.getElementById('read').parentElement.append(debugLink('liveTools','View live diagnostics'));
 const advanced=make('details');advanced.className='setup-options';advanced.append(make('summary','Session options'));const clear=document.getElementById('clear'),period=document.getElementById('workFrom')?.closest('label');if(period)advanced.append(period);if(clear)advanced.append(clear);document.querySelector('#fold-import .step-body')?.append(advanced);
 const form=document.getElementById('ruleForm');if(form){const custom=make('details');custom.className='custom-rule';custom.id='customRule';custom.append(make('summary','Add or edit a custom rule'),form);document.getElementById('categories').before(custom);}
 const optionalPlan=document.querySelector('#fold-plan .step-title');if(optionalPlan)optionalPlan.textContent='Optional draft plan';
 const sample=document.getElementById('sample');if(sample)debugSlot('sampleTools','Fictional sample').append(make('p','Load fictional data to explore the interface. Sample records cannot edit Wave.'),sample);
 for(const group of groups.values())for(const panel of group.querySelectorAll('section>.step'))panel.addEventListener('toggle',()=>{if(!panel.open)return;for(const other of group.querySelectorAll('section>.step'))if(other!==panel)other.open=false;});
 showWorkspace('usage');open('setup',{save:false});return usageController;
}
