import test from 'node:test';import assert from 'node:assert/strict';import {allCollectionSummary,collectionYears,combineCollectionYears} from '../extension/all-collection.js';import {scopedListIds} from '../extension/list-view.js';import {remainingWork,liveRunQueue,compareCollectedRows} from '../extension/inspection.js';import {waveListScan} from '../extension/list-scan.js';
const business='11111111-1111-4111-8111-111111111111';
test('full history retains reviewed, unreviewed, unknown, unresolved and missing export counts',()=>{const report={filter:'ALL',records:[{id:'1',reviewed:'Reviewed'},{id:'2',reviewed:'Not reviewed'},{id:'3',reviewed:'Unknown'},{id:null,reviewed:'Unknown'}]};assert.deepEqual(allCollectionSummary(report,[{id:'1'},{id:'2'}]),{total:4,reviewed:1,notReviewed:1,unknown:2,unresolved:1,missingExport:1});});
test('full collection cannot populate bookkeeping scope or remaining work',()=>{const t={id:'1',date:'2026-01-01'},report={business,filter:'ALL',completeness:'count-confirmed',records:[{...t,identity:'Wave transaction ID',reviewed:'Not reviewed'}]};assert.equal(scopedListIds(report).size,0);assert.deepEqual(liveRunQueue([t],report,business),[]);assert.deepEqual(remainingWork([t],report,{business}),[]);});
test('completed-year inspection is opt-in and remains a comparison',()=>{const t={id:'1',date:'2024-01-01',description:'Fictional Cloud',primary:{account:'Fictional Bank'},categories:['Software'],amount:1000};const report={business,filter:'ALL',records:[{...t,account:'Fictional Bank',category:'Software',amountCents:1000,identity:'Wave transaction ID',reviewed:'Reviewed'}]};assert.equal(compareCollectedRows(report,[t],{business})[0].state,'before-period');assert.equal(compareCollectedRows(report,[t],{business,from:'0000-01-01'})[0].state,'list-match');});
test('full collector rejects URL filters before reading rows',()=>{const context={document:{},window:{},getComputedStyle:()=>({}),location:{href:'https://next.waveapps.com/'+business+'/transactions?status=NOT_VERIFIED'}};assert.throws(()=>waveListScan({action:'start',mode:'ALL',business},context),/no URL filters/);context.location.href='https://next.waveapps.com/'+business+'/transactions?account=fictional';assert.throws(()=>waveListScan({action:'start',mode:'ALL',business},context),/no URL filters/);});

test('calendar partitions include every year from the oldest through today',()=>{assert.deepEqual(collectionYears(2019,2026),[2019,2020,2021,2022,2023,2024,2025,2026]);assert.throws(()=>collectionYears(2026,2019));});
const batch=(year,records=[])=>({business,year,filter:'ALL',records,expectedTotal:records.length,completeness:'count-confirmed',loadMoreClicks:2});
test('combined year reports require every year including empty years',()=>{const years=[2024,2025,2026],batches={2024:batch(2024,[{id:'1',date:'2024-09-01',reviewed:'Reviewed'}]),2025:batch(2025),2026:batch(2026,[{id:'2',date:'2026-01-01',reviewed:'Not reviewed'}])};const all=combineCollectionYears(business,years,batches);assert.equal(all.records.length,2);assert.equal(all.expectedTotal,2);assert.equal(all.completeness,'count-confirmed');assert.equal(all.loadMoreClicks,6);delete batches[2025];assert.equal(combineCollectionYears(business,years,batches).completeness,'unconfirmed');});
test('partial, conflicting and out-of-year records cannot claim full coverage',()=>{const batches={2025:batch(2025,[{id:'1',date:'2025-01-01'}]),2026:batch(2026,[{id:'1',date:'2026-01-01'}])};assert.equal(combineCollectionYears(business,[2025,2026],batches).completeness,'unconfirmed');batches[2026]=batch(2026,[{id:'2',date:'2025-01-01'}]);assert.equal(combineCollectionYears(business,[2025,2026],batches).records.length,1);batches[2026]=batch(2026);batches[2026].running=true;assert.equal(combineCollectionYears(business,[2025,2026],batches).completeness,'unconfirmed');assert.throws(()=>combineCollectionYears(business,[2026],{2026:{...batch(2026),business:'other'}}));});
