import test from 'node:test';import assert from 'node:assert/strict';import {parseCSV} from '../extension/csv.js';import {importAmazon,groupAmazon,suggestAmazonItem,matchAmazonPayments,amazonActions,amazonInstrumentKey} from '../extension/amazon.js';
const categories=['Equipment & Tools — Tool Purchases, Accessories','Parts & Materials — Lumber, Concrete, Plumbing, Electrical','Personal Pets — Vet, Pet Food, Supplies','Personal Miscellaneous — Expenses','Computer Hardware — Laptop, Monitor, Accessories'];
const row=(extra={})=>({orderId:'Fictional-order-01',date:'2026-10-01',currency:'USD',net:1000,status:'Closed',asin:'SYNTH001',title:'Hammer drill',productCategory:'Home Improvement',lineId:'',quantity:1,itemNet:1000,itemSubtotal:900,itemTax:100,itemShipping:0,itemPromotion:0,paymentRef:'fictional-payment-01',paymentDate:'2026-10-02',paymentAmount:1000,instrument:'Visa',identifier:'Visa ending 1111',...extra});
const transaction=(extra={})=>({id:'1000000000000000001',date:'2026-10-03',description:'AMZN Mktp fictional',primary:{account:'Fictional Visa (1111)',type:'Credit Card'},postings:[{},{}],categories:['Uncategorized Expense'],direction:'out',amount:1000,...extra});
test('Amazon Excel text cells preserve leading zeros without executing formulas or changing normal CSV',()=>{assert.deepEqual(parseCSV('ID,Code\n=\"00123\",\"literal =\"\"x\"\"\"',{excelText:true}),[['ID','Code'],['00123','literal ="x"']]);assert.throws(()=>parseCSV('=\"123\"'),/Invalid quote/);});
test('Amazon import validates dates and amounts, excludes contact fields and keeps order IDs as text',()=>{const header=['Order Date','Order ID','Currency','Order Net Total','Order Status','ASIN','Title','Item Quantity','Item Net Total','Payment Reference ID','Payment Date','Payment Amount','Payment Instrument Type','Payment Identifier','Account User Email'];const values=['10/01/2026','Fictional-order-01','USD','10.00','Closed','SYNTH001','Hammer drill','1','10.00','reference-1','10/02/2026','10.00','Visa','1111','fictional@example.invalid'];const source=header.join(',')+'\n'+values.join(',');const [record]=importAmazon(source);assert.equal(record.date,'2026-10-01');assert.equal(record.itemNet,1000);assert.equal(record.orderId,'Fictional-order-01');assert.ok(!JSON.stringify(record).includes('@'));assert.throws(()=>importAmazon(source.replace('10/01/2026','02/30/2026')),/Invalid Amazon date/);});
test('Repeated item/payment rows and overlapping reports do not multiply spending',()=>{const first=row({paymentAmount:700}),reward=row({paymentRef:'reward-01',paymentAmount:300,instrument:'Rewards Account',identifier:''});const [order]=groupAmazon([first,reward,first,reward]);assert.equal(order.items.length,1);assert.equal(order.itemTotal,1000);assert.equal(order.payments.length,2);assert.deepEqual(order.issues,[]);assert.equal(order.payments.reduce((n,p)=>n+p.amount,0),1000);});
test('Identical unnumbered items that no longer reconcile are held for review',()=>{const [order]=groupAmazon([row({net:2000,paymentAmount:2000})]);assert.ok(order.issues.some(i=>i.includes('Item totals')));});
test('Shared payment references and conflicting source totals prevent order actions',()=>{const orders=groupAmazon([row(),row({orderId:'Fictional-order-02'})]);assert.ok(orders.every(o=>o.issues.some(i=>i.includes('multiple orders'))));const [bad]=groupAmazon([row(),row({net:2000})]);assert.ok(bad.issues.some(i=>i.includes('conflicting')));});
test('Signals suggest exact existing categories and leave generic equipment purpose open',()=>{assert.equal(suggestAmazonItem(row(),categories).purpose,'Likely business');assert.equal(suggestAmazonItem(row({title:'Dog food',productCategory:'Pet Products'}),categories).category,categories[2]);assert.equal(suggestAmazonItem(row({title:'Laptop',productCategory:'Personal Computer'}),categories).purpose,'Needs judgment');assert.equal(suggestAmazonItem(row(),[]).category,'');});
test('Matching uses cents, payment date, Amazon wording and a unique credit-card ending',()=>{const orders=groupAmazon([row()]);const [m]=matchAmazonPayments(orders,[transaction()]);assert.equal(m.state,'Candidate');assert.deepEqual(m.candidates,['1000000000000000001']);for(const change of [{amount:1001},{direction:'in'},{date:'2026-10-15'},{description:'Unrelated merchant'},{existingTransfer:true}])assert.notEqual(matchAmazonPayments(orders,[transaction(change)])[0].state,'Candidate');});
test('Rewards, unknown cards, reference-code digits and shared candidates never become unique bank matches',()=>{assert.equal(matchAmazonPayments(groupAmazon([row({instrument:'Rewards Account'})]),[transaction()])[0].state,'Rewards / gift credit');assert.equal(matchAmazonPayments(groupAmazon([row()]),[transaction({primary:{account:'Reference 911110',type:'Credit Card'}})])[0].state,'Needs payment details');assert.equal(matchAmazonPayments(groupAmazon([row()]),[transaction({primary:{account:'Checking (1111)',type:'Cash and Bank'}})])[0].state,'Needs payment details');const orders=groupAmazon([row(),row({orderId:'Fictional-order-02',paymentRef:'payment-two'})]);assert.ok(matchAmazonPayments(orders,[transaction()]).every(m=>m.state==='Ambiguous match'));assert.equal(matchAmazonPayments(groupAmazon([row()]),[transaction(),transaction({id:'1000000000000000002'})])[0].state,'Ambiguous match');});
test('An explicit account mapping can resolve a missing card identifier',()=>{const orders=groupAmazon([row({identifier:''})]),p=orders[0].payments[0];assert.equal(matchAmazonPayments(orders,[transaction()],{[amazonInstrumentKey(p)]:'Fictional Visa (1111)'})[0].state,'Candidate');});
test('Only all-approved, reconciled, single-category, current-period purchases can be prepared',()=>{const orders=groupAmazon([row()]),matches=matchAmazonPayments(orders,[transaction()]),decisions={[orders[0].items[0].key]:{purpose:'Business',category:categories[0]}};assert.equal(amazonActions(orders,matches,{},categories).length,0);assert.equal(amazonActions(orders,matches,decisions,categories).length,1);assert.equal(amazonActions(orders,matches,decisions,categories,'2027-01-01').length,0);assert.equal(amazonActions(orders,matches,decisions,[]).length,0);for(const extra of [{status:'Cancelled'},{net:-1000,itemNet:-1000,paymentAmount:-1000},{paymentAmount:999}]){const bad=groupAmazon([row(extra)]);assert.equal(amazonActions(bad,matches,decisions,categories).length,0);}});
test('Mixed business and personal orders stay out of single-category actions',()=>{const orders=groupAmazon([row({net:1500,paymentAmount:1500}),row({net:1500,paymentAmount:1500,asin:'SYNTH002',title:'Dog treats',itemNet:500})]);const matches=matchAmazonPayments(orders,[transaction({amount:1500})]);const decisions=Object.fromEntries(orders[0].items.map((i,n)=>[i.key,{purpose:n?'Personal':'Business',category:categories[n?2:0]}]));assert.equal(amazonActions(orders,matches,decisions,categories).length,0);});

test('Missing payment amounts and contradictory purpose/category approvals remain held',()=>{const bad=groupAmazon([row(),row({paymentRef:'unknown-payment',paymentAmount:null})]);assert.ok(bad[0].issues.some(i=>i.includes('payment amount is missing')));const orders=groupAmazon([row()]),matches=matchAmazonPayments(orders,[transaction()]);assert.equal(amazonActions(orders,matches,{[orders[0].items[0].key]:{purpose:'Personal',category:categories[0]}},categories).length,0);assert.notEqual(matchAmazonPayments(orders,[transaction({categories:['Tools','Materials']})])[0].state,'Candidate');});
