import test from 'node:test';import assert from 'node:assert/strict';
import {prepareCommandModel,approvedCommandItems,commandPreparationSummary,stageCommandItem,validateCommandDecision,createCommandStore,executeCommandQueue,feeTransferEvidence,rankedCategories,descriptionSuggestion,decisionRecord} from '../extension/command-center.js';
import {prepareExpenseBatch} from '../extension/expense-batch.js';
import {prepareCategoryEdit,verifyCategoryResult} from '../extension/editor.js';
const business='11111111-1111-1111-1111-111111111111',category='Parts & Materials',personal='Personal Miscellaneous',income='Sales';
const t=(id='1000000000000000701',changes={})=>({id,date:'2026-09-01',description:'Fictional Hardware',direction:'out',amount:1100,categories:['Uncategorized Expense'],postings:[{account:'Test bank',group:'Asset',type:'Cash and Bank',debit:0,credit:1100},{account:'Uncategorized Expense',group:'Expense',type:'Expense',debit:1100,credit:0}],primary:{account:'Test bank',type:'Cash and Bank'},kind:'Unclassified',...changes});
const catalog={groups:[{name:'Expenses',accounts:[{name:category}]},{name:'Equity',accounts:[{name:personal}]},{name:'Income',accounts:[{name:income}]}]},report=transactions=>({business,filter:'NOT_VERIFIED',capturedAt:'2026-10-06T00:00:00Z',completeness:'count-confirmed',records:transactions.map(t=>({id:t.id,date:t.date,description:t.description,account:t.primary.account,category:t.categories[0],amountCents:t.amount,reviewed:'Not reviewed',identity:'Wave transaction ID'}))}),build=(transactions=[t()],extra={})=>prepareCommandModel({business,transactions,queue:transactions,catalog,rules:[{name:'Hardware',aliases:['Fictional Hardware'],category}],reports:[report(transactions)],...extra});
const approved=(model=build())=>stageCommandItem(model.items[0],{treatment:'purchase',category},model);
test('Preparation groups similar purchases but separates direction, account, source notes and reviewed records',()=>{const a=t(),b=t('1000000000000000702'),c=t('1000000000000000703',{direction:'in',kind:'Credit / incoming',categories:['Uncategorized Income']}),reviewed=t('1000000000000000704'),old=t('1000000000000000705',{date:'2024-01-01'}),different=t('1000000000000000706',{primary:{account:'Other bank',type:'Cash and Bank'}}),transactions=[a,b,c,reviewed,old,different],r=report(transactions);r.records.find(x=>x.id===reviewed.id).reviewed='Reviewed';const m=build(transactions,{reports:[r]});assert.equal(m.items.length,4);assert.equal(m.groups.find(g=>g.items.some(i=>i.key===a.id)).items.length,2);assert.equal(m.items.find(i=>i.key===c.id).treatment,'');assert.equal(m.items.find(i=>i.key===a.id).provenance,'Approved merchant rule');assert.equal(build(transactions,{reports:[]}).items.length,0);});
test('Category search ranks exact likely categories and respects incoming/refund treatment',()=>{const categories=[{name:'Office supplies',group:'Expenses'},{name:personal,group:'Equity'},{name:category,group:'Expenses'},{name:income,group:'Income'}];assert.equal(rankedCategories(categories,'purchase',[category])[0].name,category);assert.deepEqual(rankedCategories(categories,'income',[category]).map(c=>c.name),[income]);assert.deepEqual(rankedCategories(categories,'refund',[],'personal misc').map(c=>c.name),[personal]);});
test('Source descriptions preserve bank identifiers and use product classifications without oversized additions',()=>{const source={provider:'amazon',items:[{title:'Long detailed title',productCategory:'Therapeutic massage equipment'}]},bank=t('1000000000000000707',{description:'Amazon Mktpl*SYNTHETIC'}),description=descriptionSuggestion(bank,source);assert.equal(description,'Amazon Mktpl*SYNTHETIC — Therapeutic massage equipment');assert.equal(descriptionSuggestion(bank,{provider:'venmo',merchant:'Fictional friend',note:'x'.repeat(400)}).length,255);});
test('Incoming choices require an explicit proper treatment and never become outgoing rules',()=>{const bank=t('1000000000000000708',{description:'Fictional Apparel',direction:'in',kind:'Credit / incoming',categories:['Uncategorized Income']}),m=build([bank]),item=m.items[0];assert.throws(()=>stageCommandItem(item,{category:personal},m),/Choose purchase/);assert.throws(()=>stageCommandItem(item,{treatment:'income',category:personal},m),/exact category/);const refund=stageCommandItem(item,{treatment:'refund',category:personal},m);assert.equal(refund.treatment,'refund');assert.equal(refund.expected[0].direction,'in');assert.equal(refund.ids.length,1);});
test('100 local confirmations coalesce into one write, perform no browser work, and survive reload with undo',async()=>{let writes=0,durable,network=0;const store=createCommandStore({business,persist:async s=>{writes++;durable=s;},delay:10000});const m=build(),d=approved(m);for(let i=0;i<100;i++)store.stage([{...d,key:'local:'+i,ids:['100000000000000'+String(9000+i)]}]);assert.equal(Object.keys(store.get().decisions).length,100);assert.equal(writes,0);assert.equal(network,0);await store.flush();assert.equal(writes,1);const restored=createCommandStore({business,initial:durable,persist:async()=>{},delay:10000});restored.undo('local:0');await restored.flush();assert.equal(Object.keys(restored.get().decisions).length,99);});
test('Prepared decisions invalidate changed export/source/category/business snapshots before any execution',()=>{const m=build(),d=approved(m);assert.equal(validateCommandDecision(d,m),null);assert.match(validateCommandDecision(d,{...m,transactions:[t(d.ids[0],{amount:1200})]}),/Export snapshot/);assert.match(validateCommandDecision(d,{...m,business:'other'}),/business/);assert.match(validateCommandDecision(d,{...m,categories:[]}),/category/);assert.match(validateCommandDecision({...d,sources:[{key:'missing',expected:{}}]},m),/Source evidence/);});
test('Batch executes all queued decisions then collects once; safe preflight exceptions do not block later records',async()=>{const m=build([t(),t('1000000000000000702')]),ds=m.items.map(i=>stageCommandItem(i,{treatment:'purchase',category},m)),events=[],result=await executeCommandQueue({decisions:ds,model:m,checkpoint:async(k,v)=>events.push(v.status),execute:async d=>d.key===ds[0].key?{needsAttention:true,saveAttempted:false,message:'Changed live fields'}:{categoryVerified:true,reviewedVerified:true,descriptionVerified:true},refresh:async()=>events.push('refresh')});assert.equal(result.completed,1);assert.equal(result.attention.length,1);assert.deepEqual(events,['executing','attention','executing','done','refresh']);});
test('Uncertain descriptions/saves stop the batch and remain locked across reload',async()=>{const m=build([t(),t('1000000000000000702')]),ds=m.items.map(i=>stageCommandItem(i,{treatment:'purchase',category},m)),store=createCommandStore({business,persist:async()=>{},delay:10000});store.stage(ds);let calls=0;const result=await executeCommandQueue({decisions:ds,model:m,checkpoint:store.checkpoint,execute:async()=>{calls++;return {saveAttempted:true,categoryVerified:true,reviewedVerified:true,descriptionVerified:false};},refresh:async()=>{}});assert.equal(calls,1);assert.equal(result.uncertain,true);assert.equal(store.get().results[ds[0].key].status,'uncertain');assert.throws(()=>store.undo(ds[0].key),/rechecked/);assert.throws(()=>store.stage([ds[0]]),/restaged/);await store.flush();});
test('Explicit fees support gross/net matching but unequal pairs never enter the ordinary transfer executor',()=>{const source={key:'venmo:TRANSFER',provider:'venmo',kind:'Transfer',sourceId:'TRANSFER',date:'2026-09-01',currency:'USD',amountCents:100000,signedCents:-100000,feeCents:1100,type:'Instant Transfer',accountEnding:'1234',instrumentKey:'venmo:destination'},out=t('1000000000000000791',{amount:100000,primary:{account:'Venmo balance',type:'Cash and Bank'}}),incoming=t('1000000000000000792',{amount:98900,direction:'in',description:'Venmo transfer',primary:{account:'Bank (1234)',type:'Cash and Bank'}}),[f]=feeTransferEvidence([source],[out,incoming]);assert.equal(f.state,'Source-supported fee transfer');assert.equal(f.netCents,98900);assert.equal(f.feeCents,1100);assert.equal(f.executable,false);assert.deepEqual(f.ids,[out.id,incoming.id]);assert.equal(feeTransferEvidence([{...source,feeCents:0}],[out,incoming]).length,0);assert.equal(feeTransferEvidence([{...source,provider:'paypal',type:'Unknown transfer'}],[out,incoming])[0].netCents,null);assert.equal(feeTransferEvidence([source],[out,{...incoming,amount:98500}])[0].ids.length,0);});
test('Queued category and description edits preserve live originals and verify both after save',()=>{const m=build(),d=stageCommandItem(m.items[0],{treatment:'purchase',category,description:'Fictional Hardware — job supplies'},m),record=decisionRecord(t(),d),snapshot={identity:{business,transaction:record.id},fields:{date:record.date,description:record.description,account:record.primary.account,type:'Withdrawal',amount:'11.00',category:'Uncategorized Expense'},reviewed:'Not reviewed',controls:['Mark as reviewed'],problems:[]},options={business,sample:false,categories:[category],categoryGroups:catalog.groups,queue:[],shortlist:new Set()},request=prepareCategoryEdit(record,snapshot,options);assert.equal(request.description,d.description);assert.equal(request.expected.description,t().description);const saved={...snapshot,reviewed:'Reviewed',fields:{...snapshot.fields,category,description:d.description}};assert.equal(verifyCategoryResult(record,saved,business,category).descriptionVerified,true);assert.equal(verifyCategoryResult(record,{...saved,fields:{...saved.fields,description:t().description}},business,category).categoryVerified,false);});

 test('Malformed, duplicated and wrong-direction decisions cannot execute',()=>{const m=build(),d=approved(m);assert.match(validateCommandDecision({...d,expected:null},m),/malformed/);assert.match(validateCommandDecision({...d,ids:[d.ids[0],d.ids[0]],expected:[d.expected[0],d.expected[0]]},m),/malformed/);assert.match(validateCommandDecision({...d,treatment:'refund'},m),/Direction/);assert.match(validateCommandDecision({...d,treatment:'invented'},m),/supported/);assert.match(validateCommandDecision({...d,description:''},m),/Description/);});
 test('Reloaded executing receipts and overlapping decisions cannot be automatically replayed',async()=>{const m=build(),d=approved(m),s=createCommandStore({business,initial:{decisions:{[d.key]:d},results:{[d.key]:{status:'executing'}}},persist:async()=>{},delay:10000});assert.throws(()=>s.stage([d]),/restaged/);assert.throws(()=>s.undo(d.key),/rechecked/);const other=createCommandStore({business,persist:async()=>{},delay:10000});other.stage([d]);assert.throws(()=>other.stage([{...d,key:'other'}]),/already claimed/);await other.flush();});

 test('An already matching category may receive an approved description without weakening other live checks',()=>{const m=build(),d=stageCommandItem(m.items[0],{treatment:'purchase',category,description:'Fictional Hardware — supplies'},m),record=decisionRecord(t(),d),snapshot={identity:{business,transaction:record.id},fields:{date:record.date,description:record.description,account:record.primary.account,type:'Withdrawal',amount:'11.00',category},reviewed:'Not reviewed',controls:['Mark as reviewed'],problems:[]},options={business,sample:false,categories:[category],categoryGroups:catalog.groups};const prepared=prepareExpenseBatch(record,snapshot,options);assert.equal(prepared.request.description,d.description);assert.equal(prepared.request.expected.category,category);assert.throws(()=>prepareExpenseBatch(record,{...snapshot,fields:{...snapshot.fields,amount:'12.00'}},options),/differs/);});
 test('Unfinished live rows missing from the CSV remain visible exceptions without edit eligibility',()=>{const r=report([t(),t('1000000000000000777')]),m=build([t()],{reports:[r]});assert.equal(m.items.length,2);const missing=m.items.find(i=>i.provenance==='Missing from export');assert.equal(missing.editable,false);assert.throws(()=>stageCommandItem(missing,{treatment:'purchase',category},m),/No accounting/);});


 test('A new explicit-fee allocation removes an overlapping ordinary pair and invalidates its queued approval',()=>{const source={key:'venmo:TRANSFER',provider:'venmo',kind:'Transfer',date:'2026-09-01',currency:'USD',amountCents:100000,signedCents:-100000,feeCents:1100,type:'Instant Transfer',accountEnding:'1234'},out=t('1000000000000000791',{amount:100000,kind:'Transfer candidate',partner:{id:'1000000000000000793'},primary:{account:'Venmo balance',type:'Cash and Bank'}}),net=t('1000000000000000792',{amount:98900,direction:'in',description:'Venmo transfer',primary:{account:'Bank (1234)',type:'Cash and Bank'}}),equal=t('1000000000000000793',{amount:100000,direction:'in',kind:'Transfer candidate',partner:{id:out.id},primary:{account:'Other bank',type:'Cash and Bank'}}),original=build([out,net,equal]),pair=original.items.find(i=>i.treatment==='transfer'),d=stageCommandItem(pair,{treatment:'transfer'},original);assert.equal(validateCommandDecision(d,original),null);const revised=build([out,net,equal],{records:[source]});assert.equal(revised.items.filter(i=>i.treatment==='transfer').length,0);assert.equal(revised.items.find(i=>i.treatment==='fee-transfer').state,'Source-supported fee transfer');assert.match(validateCommandDecision(d,revised),/fees/);});

 test('Preparation makes newer known merchants visible as missing export records without queuing live-only guesses',()=>{const old=t(),recent=t('1000000000000000778',{date:'2026-10-07'}),m=build([old],{reports:[report([old,recent])]});assert.deepEqual(commandPreparationSummary(m),{approvedReady:1,missing:1,latestExportDate:old.date,newestMissingDate:recent.date});assert.equal(approvedCommandItems(m).length,1);assert.equal(m.items.find(i=>i.ids.includes(recent.id)).editable,false);const refreshed=build([old,recent]);assert.equal(commandPreparationSummary(refreshed).missing,0);assert.equal(approvedCommandItems(refreshed).length,2);const existing=stageCommandItem(m.items.find(i=>i.key===old.id),{treatment:'purchase',category},m);assert.equal(validateCommandDecision(existing,refreshed),null);assert.equal(commandPreparationSummary(refreshed,{decisions:{[existing.key]:existing}}).approvedReady,1);});
 test('Ready counts exclude queued, deferred and locked decisions while keeping safe preflight corrections available',()=>{const transactions=[t(),t('1000000000000000779'),t('1000000000000000780')],m=build(transactions),first=approved(m),state={decisions:{[first.key]:first},results:{[first.key]:{status:'uncertain'}},deferred:{[transactions[1].id]:true}};assert.equal(commandPreparationSummary(m,state).approvedReady,1);state.results[first.key]={status:'attention'};assert.equal(commandPreparationSummary(m,state).approvedReady,2);});
