import test from 'node:test';import assert from 'node:assert/strict';import {deflateRawSync} from 'node:zlib';
import {validRange,amazonDownloadName,amazonDownloadItem,waveDownloadURL,waveMailSearch,observeNativeDownload,readInboxFile,findAmazonInbox,saveAmazonReport,saveDistinctFile,crc32,unpackWaveZIP,saveWaveArchive,sameWaveHistory,fetchWaveArchive,waitWaveMail} from '../extension/download-files.js';
import {importAccounting} from '../extension/model.js';
const headers=['Transaction ID','Transaction Date','Account Name','Transaction Description','Debit Amount (Two Column Approach)','Credit Amount (Two Column Approach)','Account Group','Account Type'];
const csv=(id='9000000000000000101',amount='10.00')=>[headers,[id,'2026-01-01','Fictional Card','Fictional Shop','',amount,'Liability','Credit Card'],[id,'2026-01-01','Fictional Parts','Fictional Shop',amount,'','Expense','Expense']].map(r=>r.join(',')).join('\n');
const amazon=(date='2026-01-01')=>'Order Date,Order ID,Currency,Order Net Total,Order Status,ASIN,Title,Item Quantity,Item Net Total,Payment Reference ID,Payment Date,Payment Amount,Payment Instrument Type,Payment Identifier\n'+date+',fictional-order-01,USD,10.00,Closed,FAKEASIN,Fictional item,1,10.00,fictional-reference,'+date+',10.00,Visa,1111';
export function zipFiles(files,method=8){const parts=[],central=[];let offset=0;for(const [name,text] of files){const bytes=Buffer.from(text),encoded=Buffer.from(name),data=method===8?deflateRawSync(bytes):bytes,local=Buffer.alloc(30);local.writeUInt32LE(0x04034b50);local.writeUInt16LE(20,4);local.writeUInt16LE(method,8);local.writeUInt32LE(crc32(bytes),14);local.writeUInt32LE(data.length,18);local.writeUInt32LE(bytes.length,22);local.writeUInt16LE(encoded.length,26);const dir=Buffer.alloc(46);dir.writeUInt32LE(0x02014b50);dir.writeUInt16LE(20,4);dir.writeUInt16LE(20,6);dir.writeUInt16LE(method,10);dir.writeUInt32LE(crc32(bytes),16);dir.writeUInt32LE(data.length,20);dir.writeUInt32LE(bytes.length,24);dir.writeUInt16LE(encoded.length,28);dir.writeUInt32LE(offset,42);parts.push(local,encoded,data);central.push(dir,encoded);offset+=local.length+encoded.length+data.length;}const directory=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(files.length,8);end.writeUInt16LE(files.length,10);end.writeUInt32LE(directory.length,12);end.writeUInt32LE(offset,16);return new Uint8Array(Buffer.concat([...parts,directory,end]));}
const files=(accounting=csv())=>[['accounting.csv',accounting],['bill_items.csv','Name,Amount\nFictional,10.00'],['customers.csv','Name\nFictional Customer'],['vendors.csv','Name\nFictional Vendor']];
function folder(name='data'){const dirs=new Map(),store=new Map();return {name,dirs,store,entries:async function*(){for(const [n,d] of dirs)yield [n,{...d,kind:'directory'}];for(const [n,f] of store)yield [n,{kind:'file',getFile:async()=>f}];},getDirectoryHandle:async(n,{create=false}={})=>{if(!dirs.has(n)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});dirs.set(n,folder(n));}return dirs.get(n);},getFileHandle:async(n,{create=false}={})=>{if(!store.has(n)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});store.set(n,new File([],n));}return {getFile:async()=>store.get(n),createWritable:async()=>({write:async value=>store.set(n,new File([value],n)),close:async()=>{},abort:async()=>{}})};}};}
function downloads(){const made=new Set(),changed=new Set(),items=new Map();return {items,made,changed,onCreated:{addListener:f=>made.add(f),removeListener:f=>made.delete(f)},onChanged:{addListener:f=>changed.add(f),removeListener:f=>changed.delete(f)},search:async({id})=>items.has(id)?[items.get(id)]:[],emit:item=>{items.set(item.id,item);for(const f of made)f(item);}};}
test('Amazon range and filename bounds are exact; automatic captures require Amazon origin',()=>{assert.deepEqual(validRange('2019-09-01','2026-10-07'),{start:'2019-09-01',end:'2026-10-07'});assert.throws(()=>validRange('2026-02-30','2026-12-31'));const r={start:'2026-01-01',end:'2026-12-31'},filename='C:\\Downloads\\orders_from_20260101_to_20261231_example (1).csv';assert.equal(amazonDownloadName(filename,r),true);assert.equal(amazonDownloadItem({filename,referrer:'https://www.amazon.com/'},r),true);assert.equal(amazonDownloadItem({filename,url:'https://evil.example/'},r),false);assert.equal(amazonDownloadName(filename,{...r,end:'2026-12-30'}),false);});
test('Wave URLs accept only the accounting export bucket and observed tracking wrapper',()=>{const direct='https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/fictional-export.zip?Expires=1999999999';assert.equal(waveDownloadURL(direct),true);assert.equal(waveDownloadURL('https://track.pstmrk.it/3s/'+encodeURIComponent(direct.replace('https://',''))+'/fake'),true);assert.equal(waveDownloadURL(direct.replace('wave-prod-accounting.s3.amazonaws.com','evil.example')),false);assert.equal(waveDownloadURL('https://user:secret@wave-prod-accounting.s3.amazonaws.com/accounting_exports/x.zip'),false);assert.equal(waveDownloadURL(direct.replace('accounting_exports','other')),false);assert.equal(waveMailSearch(1).startsWith('https://mail.google.com/mail/u/1/#search/'),true);assert.throws(()=>waveMailSearch(-1));});
test('Native listeners are installed before triggering, restricted to new IDs and removed after success',async()=>{const d=downloads(),inbox=folder('Downloads');inbox.store.set('fake.csv',new File(['synthetic'],'fake.csv'));let checkpoint;const result=await observeNativeDownload({downloads:d,inbox,accept:item=>item.filename.endsWith('fake.csv'),trigger:async()=>{assert.equal(d.made.size,1);d.emit({id:9,startTime:new Date().toISOString(),filename:'C:/Downloads/fake.csv',state:'complete'});},checkpoint:async value=>checkpoint=value});assert.equal(await result.file.text(),'synthetic');assert.deepEqual(checkpoint,{downloadId:9,filename:'fake.csv'});assert.equal(d.made.size,0);assert.equal(d.changed.size,0);});
test('Interrupted downloads, cancellation, timeout and trigger errors release listeners without writing files',async()=>{const d=downloads(),inbox=folder();d.items.set(1,{id:1,filename:'fake.zip',state:'interrupted'});await assert.rejects(observeNativeDownload({downloads:d,inbox,accept:()=>true,resumeId:1}),/interrupted/);assert.equal(d.made.size,0);await assert.rejects(observeNativeDownload({downloads:d,inbox,accept:()=>true,current:()=>false}),/Stopped/);assert.equal(d.changed.size,0);assert.equal((await observeNativeDownload({downloads:d,inbox,accept:()=>true,timeoutMs:0})).waiting,true);await assert.rejects(observeNativeDownload({downloads:d,inbox,accept:()=>true,trigger:async()=>{throw Error('unknown response');}}),/unknown/);assert.equal(d.made.size,0);});
test('Resume checks its own saved download ID rather than enumerating browser history',async()=>{const d=downloads(),inbox=folder();inbox.store.set('own.zip',new File(['local'],'own.zip'));d.items.set(42,{id:42,filename:'own.zip',state:'complete'});const searched=[];const search=d.search;d.search=async query=>{searched.push(query);return search(query);};const result=await observeNativeDownload({downloads:d,inbox,accept:()=>true,resumeId:42});assert.equal(await result.file.text(),'local');assert.deepEqual(searched,[{id:42}]);});
test('Inbox scan picks only the requested date range and holds multiple matching files',async()=>{const inbox=folder(),job={start:'2026-01-01',end:'2026-12-31',requestedAt:new Date(Date.now()-10000).toISOString()};inbox.store.set('unrelated.csv',new File(['other'],'unrelated.csv'));const name='orders_from_20260101_to_20261231_example.csv';inbox.store.set(name,new File([amazon()],name));assert.equal((await findAmazonInbox(inbox,job)).name,name);inbox.store.set(name.replace('example','other'),new File([amazon()],name.replace('example','other')));await assert.rejects(findAmazonInbox(inbox,job),/Several/);});
test('Amazon reports validate order dates and exact importer headers before saving in business scope',async()=>{const root=folder(),range={start:'2026-01-01',end:'2026-12-31'};await assert.rejects(saveAmazonReport(root,new File(['<html>login</html>'],'orders.csv'),range),/Missing/);assert.equal(root.dirs.size,0);await assert.rejects(saveAmazonReport(root,new File([amazon('2025-12-31')],'orders.csv'),range),/dates disagree/);const result=await saveAmazonReport(root,new File([amazon()],'orders.csv'),range);assert.match(result.path,/amazon\/business\//);assert.equal(result.orders,1);assert.equal((await saveAmazonReport(root,new File([amazon()],'orders.csv'),range)).reused,true);});
test('Distinct saves preserve originals and verify content when reusing a changed-name file',async()=>{const root=folder(),first=await saveDistinctFile(root,'report','.csv','one'),same=await saveDistinctFile(root,'report','.csv','one'),changed=await saveDistinctFile(root,'report','.csv','two');assert.equal(same.reused,true);assert.notEqual(changed.name,first.name);assert.equal(await root.store.get(first.name).text(),'one');assert.throws(()=>validRange('2026-12-31','2026-01-01'));await assert.rejects(saveDistinctFile(root,'../bad','.csv','text'),/Unsafe/);});
test('Both stored and deflated Wave ZIPs produce four files and preserve string transaction IDs',async()=>{for(const method of [0,8]){const parsed=await unpackWaveZIP(zipFiles(files(),method));assert.equal(parsed.files.length,4);assert.equal(parsed.dataset.transactions.length,1);assert.equal(parsed.dataset.transactions[0].id,'9000000000000000101');}});
test('Wrong ZIP, traversal, duplicate names, missing accounting and non-CSV entries are rejected',async()=>{for(const entries of [files().map((f,i)=>i?f:['../accounting.csv',csv()]),files().map((f,i)=>i===1?['ACCOUNTING.CSV',csv()]:f),files().slice(0,3),files().map((f,i)=>i?f:['wrong.csv',csv()]),files().map((f,i)=>i===1?['script.js','alert(1)']:f)])await assert.rejects(unpackWaveZIP(zipFiles(entries)));await assert.rejects(unpackWaveZIP(new TextEncoder().encode('<html>expired link</html>')));});
test('CRC mismatch, encryption and advertised decompression bombs are held before import',async()=>{const original=zipFiles(files(),0),central=new DataView(original.buffer).getUint32(original.length-6,true);const crc=original.slice();crc[central+16]^=1;await assert.rejects(unpackWaveZIP(crc),/checksum/);const encrypted=original.slice();new DataView(encrypted.buffer).setUint16(central+8,1,true);await assert.rejects(unpackWaveZIP(encrypted),/Encrypted/);const huge=original.slice();new DataView(huge.buffer).setUint32(central+24,31*1024*1024,true);await assert.rejects(unpackWaveZIP(huge),/size/);});
test('First or mismatched Wave histories need explicit confirmation and never update accounting.csv silently',async()=>{const root=folder(),bytes=zipFiles(files()),business='00000000-0000-4000-8000-000000000123';const preview=await saveWaveArchive(root,bytes,{business});assert.equal(preview.needsConfirmation,true);assert.equal(root.dirs.get('wave').store.has('accounting.csv'),false);await saveWaveArchive(root,bytes,{business,confirmed:true});const before=await root.dirs.get('wave').store.get('accounting.csv').text();const mismatch=await saveWaveArchive(root,zipFiles(files(csv('9000000000000009999'))),{business});assert.equal(mismatch.needsConfirmation,true);assert.equal(await root.dirs.get('wave').store.get('accounting.csv').text(),before);});
test('Matching history updates latest CSV only after preserving ZIP, all four files and previous CSV',async()=>{const root=folder(),business='00000000-0000-4000-8000-000000000123',bytes=zipFiles(files());await saveWaveArchive(root,bytes,{business,confirmed:true});const next=zipFiles(files(csv()));const result=await saveWaveArchive(root,next,{business});assert.equal(result.historyMatched,true);const wave=root.dirs.get('wave');assert.equal(wave.dirs.get('history').store.size,1);const exportDir=[...wave.dirs.get('exports').dirs.values()][0];assert.equal(exportDir.store.size,6);assert.ok(exportDir.store.has('bill_items.csv'));assert.ok(![...exportDir.store.values()].some(f=>f.name.includes('Signature')));});
test('History matching checks ID coverage and financial identity, not category choices',()=>{const previous=importAccounting(csv()),next=importAccounting(csv().replace('Fictional Parts','Fictional Supplies'));assert.equal(sameWaveHistory(previous,next),true);assert.equal(sameWaveHistory(previous,importAccounting(csv('9000000000000009999'))),false);assert.equal(sameWaveHistory(previous,importAccounting(csv('9000000000000000101','11.00'))),false);});
test('Stopping before a native download prevents the provider trigger entirely',async()=>{const d=downloads();let clicked=false;await assert.rejects(observeNativeDownload({downloads:d,inbox:folder(),accept:()=>true,current:()=>false,trigger:async()=>clicked=true}),/Stopped/);assert.equal(clicked,false);assert.equal(d.made.size,0);});
test('Wave ZIP fetch validates fresh exact-origin links, omits credentials and hides signed failures',async()=>{
 const url='https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/fictional-export.zip?Expires='+Math.floor((Date.now()+3600000)/1000)+'&Signature=fictional-secret';
 let calls=0;const bytes=zipFiles(files());assert.deepEqual(await fetchWaveArchive(url,{fetcher:async(value,options)=>{calls++;assert.equal(options.credentials,'omit');assert.equal(options.redirect,'error');assert.equal(options.referrerPolicy,'no-referrer');return new Response(bytes);}}),bytes);
 for(const bad of [url.replace('wave-prod-accounting.s3.amazonaws.com','evil.example'),url.replace(/Expires=\d+/,'Expires=1'),url.replace(/Expires=\d+/,'Expires=NaN'),url.replace('accounting_exports','receipts'),url.replace('https:','http:')])await assert.rejects(fetchWaveArchive(bad,{fetcher:()=>{calls++;}}),/invalid|expired/);
 assert.equal(calls,1);await assert.rejects(fetchWaveArchive(url,{fetcher:async()=>{throw Error(url);}}),e=>!e.message.includes('Signature')&&/directly/.test(e.message));
});
test('Wave ZIP fetch enforces advertised and streamed byte limits and supports Stop',async()=>{
 const url='https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/fictional-export.zip?Expires=1999999999';
 await assert.rejects(fetchWaveArchive(url,{fetcher:async()=>new Response('large',{headers:{'content-length':'100'}}),maxBytes:2}),/under 40 MB/);
 await assert.rejects(fetchWaveArchive(url,{fetcher:async()=>new Response('large'),maxBytes:2}),/under 40 MB/);
 let called=false;await assert.rejects(fetchWaveArchive(url,{current:()=>false,fetcher:async()=>{called=true;}}),/Stopped/);assert.equal(called,false);
 let current=true;await assert.rejects(fetchWaveArchive(url,{current:()=>current,fetcher:async()=>{current=false;return new Response('small');}}),/Stopped/);
});
test('Wave ZIP fetch timeout aborts without exposing its URL',async()=>{
 const url='https://wave-prod-accounting.s3.amazonaws.com/accounting_exports/fictional-export.zip?Expires=1999999999';
 await assert.rejects(fetchWaveArchive(url,{timeoutMs:5,fetcher:async(value,{signal})=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(Error(value))))}),e=>/directly/.test(e.message)&&!e.message.includes('Expires'));
});
test('Wave email search refreshes empty results for more than 30 seconds and finds late mail',async()=>{
 let time=0,refreshes=0,opens=0;const result=await waitWaveMail({now:()=>time,pause:async ms=>time+=ms,refresh:async()=>refreshes++,openLatest:async()=>opens++,read:async()=>({searchPage:true,readyLinks:refreshes>=7?1:0})});
 assert.equal(result.ready,true);assert.equal(refreshes,7);assert.ok(time>=35000);assert.ok(opens>30);
});
test('Wave email waits expire or stop without creating a second export',async()=>{
 let time=0,refreshes=0;const result=await waitWaveMail({timeoutMs:31000,now:()=>time,pause:async ms=>time+=ms,refresh:async()=>refreshes++,openLatest:async()=>{},read:async()=>({searchPage:true,readyLinks:0})});
 assert.equal(result.waiting,true);assert.equal(refreshes,6);
 await assert.rejects(waitWaveMail({current:()=>false,read:async()=>{throw Error('should not read');}}),/Stopped/);
 let failures=0;await assert.rejects(waitWaveMail({read:async()=>{failures++;throw Error('Wrong mailbox');},pause:async()=>{}}),/Wrong mailbox/);assert.equal(failures,3);
});

test('A captured CSV text response completes native observation immediately and releases both listeners',async()=>{
 const d=downloads(),file=new File(['synthetic CSV'],'paypal.csv');
 const result=await observeNativeDownload({downloads:d,inbox:folder(),accept:()=>false,trigger:async()=>({file})});
 assert.equal(result.file,file);assert.equal(result.provided,true);assert.equal(d.made.size,0);assert.equal(d.changed.size,0);
});
