import test from 'node:test';
import assert from 'node:assert/strict';
import {paypalPeriods,paypalReportKey,eligiblePayPalReports,savePayPalCSV,verifyPayPalFile,collectPayPalReports,paypalOrigins} from '../extension/paypal.js';
import {importPayPalCSV,paypalDate,paypalMoney} from '../extension/paypal-csv.js';
import {sourceProvider,readEvidenceFile,modelEvidenceFiles} from '../extension/source-files.js';
const header='Date,Name,Type,Status,Currency,Gross,Fee,Net,Transaction ID,Reference Txn ID,Payment Source,Item Title,Note';
const csv=(id='FAKE0000000000001',date='01/02/2025',extra={})=>header+'\n'+[date,'Fictional Tools','Express Checkout Payment',extra.status||'Completed','USD',extra.gross||'-10.00',extra.fee||'0.00',extra.net||'-10.00',id,extra.reference||'',extra.funding||'CreditCard','Fictional tool','Example purchase'].join(',');
const report={type:'All transactions',format:'CSV',start:'2025-01-01',end:'2025-12-31',ready:true};
function folder(name='paypal'){const dirs=new Map(),files=new Map();return {name,dirs,files,getDirectoryHandle:async(name,{create=false}={})=>{if(!dirs.has(name)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});dirs.set(name,folder(name));}return dirs.get(name);},getFileHandle:async(name,{create=false}={})=>{if(!files.has(name)){if(!create)throw Object.assign(Error('missing'),{name:'NotFoundError'});files.set(name,'');}return {getFile:async()=>({text:async()=>files.get(name)}),createWritable:async()=>({write:async value=>files.set(name,value),close:async()=>{},abort:async()=>{}})};}};}
test('PayPal plans oldest-first calendar years within seven-year and twelve-month bounds',()=>{const plan=paypalPeriods(2019,'2026-10-07');assert.equal(plan.periods[0].start,'2019-10-07');assert.equal(plan.periods.at(-1).end,'2026-10-07');assert.equal(plan.periods.length,8);assert.equal(plan.limited,true);for(const p of plan.periods)assert.equal(p.start.slice(0,4),p.end.slice(0,4));assert.equal(paypalPeriods(2019,'2024-02-29').earliest,'2017-02-28');assert.throws(()=>paypalPeriods(2027,'2026-10-07'));assert.deepEqual(paypalOrigins,['https://www.paypal.com/reports/*']);});
test('CSV preserves IDs, item evidence and excludes contact columns',()=>{const parsed=importPayPalCSV(csv());assert.equal(parsed.records[0].sourceId,'FAKE0000000000001');assert.equal(parsed.records[0].items[0].title,'Fictional tool');assert.equal(parsed.records[0].signedCents,-1000);assert.equal(parsed.records[0].statementView,'account');assert.ok(!JSON.stringify(parsed).includes('Email'));});
test('Dates use explicit date order and reject invalid dates; money rejects decimal commas',()=>{assert.equal(paypalDate('02/01/2025','dmy'),'2025-01-02');assert.equal(paypalDate('02/01/2025','mdy'),'2025-02-01');assert.throws(()=>paypalDate('02/30/2025'));assert.throws(()=>paypalDate('01/02/2025','guess'));assert.equal(paypalMoney('-1,234.56'),-123456);assert.throws(()=>paypalMoney('12,34'));assert.throws(()=>paypalMoney('12.345'));});
test('HTML, ZIP, wrong periods, malformed rows and missing mandatory fields never save',()=>{for(const value of ['<html>login</html>','PKfake','Date,Amount\n1,10',csv()+'\nFAKE'])assert.throws(()=>importPayPalCSV(value));assert.throws(()=>importPayPalCSV(csv(),{period:{start:'2026-01-01',end:'2026-12-31'}}));assert.throws(()=>importPayPalCSV(csv().replace('-10.00,0.00,-10.00','-10.00,0.00,')));assert.throws(()=>importPayPalCSV(csv()+'\n'+csv().split('\n')[1]));});
test('Pending, memo, refunds, funding and incoming activity cannot become approved purchases',()=>{assert.equal(importPayPalCSV(csv('FAKE1','01/02/2025',{status:'Pending'})).records[0].kind,'Unsettled activity');assert.equal(importPayPalCSV(csv().replace('Express Checkout Payment','Payment Refund')).records[0].kind,'Refund');assert.equal(importPayPalCSV(csv().replace('Express Checkout Payment','General Credit Card Deposit')).records[0].kind,'Funding movement');assert.equal(importPayPalCSV(csv().replaceAll('-10.00','10.00')).records[0].kind,'Incoming payment');assert.equal(importPayPalCSV(csv().replace('Express Checkout Payment','User Initiated Withdrawal')).records[0].kind,'Transfer');});
test('Fees reconcile exactly and remain separate reconciliation evidence',()=>{assert.throws(()=>importPayPalCSV(csv('FAKE1','01/02/2025',{fee:'-1.00'})));const r=importPayPalCSV(csv('FAKE1','01/02/2025',{fee:'-1.00',net:'-11.00'})).records[0];assert.equal(r.feeCents,-100);assert.match(r.blocked,/fees/i);assert.match(r.issues[0],/fees/);});
test('Wallet, unspecified and credit funding never claim an external purchase automatically',()=>{const r=importPayPalCSV(csv().replace('CreditCard','PayPalFunds')).records[0];assert.equal(r.bankExpected,false);assert.match(r.blocked,/Wallet/);assert.equal(importPayPalCSV(csv().replace('CreditCard','BuyerCredit')).records[0].kind,'Financing');assert.equal(importPayPalCSV(csv().replace('CreditCard','ElectronicFundsTransfer')).records[0].accountEnding,'');});
test('Empty reports are valid empty activity, not fabricated transactions',()=>{const p=importPayPalCSV(header);assert.equal(p.controls.empty,true);assert.deepEqual(p.records,[]);});
test('File save validates before writing, reuses hashes and never overwrites changed reports',async()=>{const root=folder();await assert.rejects(savePayPalCSV(root,report,'<html>'));assert.equal(root.dirs.size,0);const first=await savePayPalCSV(root,report,csv()),same=await savePayPalCSV(root,report,csv()),changed=await savePayPalCSV(root,report,csv('FAKE2'));assert.equal(same.reused,true);assert.notEqual(first.name,changed.name);assert.equal(await verifyPayPalFile(root,first),true);assert.equal(root.dirs.get('2025').files.size,2);assert.equal((await savePayPalCSV(root,report,csv('FAKE2'))).reused,true);root.dirs.get('2025').files.set(first.name.split('/')[1],'changed');assert.equal(await verifyPayPalFile(root,first),false);assert.equal(await verifyPayPalFile(root,{...first,name:'../secret.csv'}),false);});
test('Source folder CSV imports feed PayPal evidence and unchanged files are reused',async()=>{assert.equal(sourceProvider('paypal/2025/report.csv'),'paypal');assert.equal(sourceProvider('venmo/statement-business.csv'),'venmo');assert.equal(sourceProvider('Download.CSV'),'paypal');const file=new File([csv()],'paypal-test.csv'),parsed=await readEvidenceFile(file,'paypal/2025/paypal-test.csv');assert.equal(parsed.records.length,1);assert.strictEqual(await readEvidenceFile(file,'paypal/2025/paypal-test.csv',parsed),parsed);const dmy=await readEvidenceFile(new File([csv('FAKE2','31/01/2025')],'report.csv'),'paypal/2025/paypal-all-2025-dmy.csv');assert.equal(dmy.records[0].date,'2025-01-31');assert.equal(modelEvidenceFiles([parsed])[0].provider,'paypal');assert.equal(modelEvidenceFiles([parsed])[0].bankExpected,true);assert.equal(modelEvidenceFiles([parsed])[0].accountEnding,'');});
test('Compatible PDF/CSV copies enrich evidence once; true amount conflicts remain blocked',()=>{const c=importPayPalCSV(csv()).records[0],pdf={...c,sourceFormat:undefined,status:'Statement activity',note:'',items:[],netCents:undefined,accountEnding:'4321',funding:'Visa x4321',sources:[{file:'fictional.pdf',page:1}]};const merged=modelEvidenceFiles([{provider:'paypal',records:[pdf]},{provider:'paypal',records:[c]}]);assert.equal(merged.length,1);assert.equal(merged[0].conflict,false);assert.equal(merged[0].accountEnding,'4321');assert.equal(merged[0].items.length,1);assert.equal(merged[0].sources.length,2);assert.equal(modelEvidenceFiles([{provider:'paypal',records:[pdf]},{provider:'paypal',records:[{...c,signedCents:-999}]}])[0].conflict,true);});
test('Collector saves older ready CSVs before new requests and skips PDFs',async()=>{const calls=[],older={...report,start:'2018-01-01',end:'2018-12-31'},info={reports:[report,{...older,format:'PDF'},older]};assert.equal(eligiblePayPalReports(info)[0].start,'2018-01-01');const result=await collectPayPalReports({periods:[report],read:async()=>info,download:async r=>{calls.push('download '+r.start);return 'synthetic';},save:async r=>({hash:r.start,name:r.start,count:1}),persist:async()=>{},request:async()=>calls.push('create'),verifySaved:async()=>true});assert.deepEqual(calls,['download 2018-01-01','download 2025-01-01']);assert.equal(result.saved,2);});
test('Pending reports and persisted uncertain Create intents never produce duplicate requests',async()=>{for(const options of [{entries:{[paypalReportKey(report)]:{status:'requesting'}},reports:[]},{entries:{},reports:[{...report,ready:false}]}]){let requests=0;const result=await collectPayPalReports({periods:[report],entries:options.entries,read:async()=>({reports:options.reports}),download:async()=>assert.fail(),save:async()=>assert.fail(),persist:async()=>{},request:async()=>requests++});assert.equal(requests,0);assert.equal(result.waiting.start,report.start);}});
test('Request intent is persisted before Create, readiness saves only after download and validation',async()=>{let requested=false;const stages=[];const result=await collectPayPalReports({periods:[report],read:async()=>({reports:requested?[report]:[]}),download:async()=>{stages.push('download');return csv();},save:async()=>{stages.push('save');return {hash:'hash',name:'name'};},persist:async entries=>stages.push(entries[paypalReportKey(report)].status),request:async()=>{assert.equal(stages[0],'requesting');stages.push('create');requested=true;return {submitted:true};}});assert.deepEqual(stages,['requesting','create','requested','download','save','saved']);assert.equal(result.saved,1);});
test('Unsupported controls clear a proven unsubmitted intent; uncertain exceptions retain intent',async()=>{let last={};const config={periods:[report],read:async()=>({reports:[]}),download:async()=>assert.fail(),save:async()=>assert.fail(),persist:async e=>last={...e}};await assert.rejects(collectPayPalReports({...config,request:async()=>({notSubmitted:true,message:'Custom controls needed'})}),/Custom/);assert.deepEqual(last,{});await assert.rejects(collectPayPalReports({...config,request:async()=>{throw Error('Tab closed');}}),/Tab closed/);assert.equal(last[paypalReportKey(report)].status,'requesting');});
test('Stop after a response prevents file writes and completed-file checkpoints',async()=>{let active=true,writes=0;const result=await collectPayPalReports({periods:[report],read:async()=>({reports:[report]}),download:async()=>{active=false;return csv();},save:async()=>writes++,persist:async()=>{},request:async()=>assert.fail(),current:()=>active});assert.equal(writes,0);assert.equal(result.stopped,true);});

test('A validated existing all-transactions interval can satisfy contained years without redundant requests',async()=>{const broad={...report,start:'2024-01-01',end:'2026-01-01'},calls=[];const result=await collectPayPalReports({periods:[report],read:async()=>({reports:[broad]}),download:async()=>{calls.push('download');return 'synthetic';},save:async()=>({hash:'verified',name:'synthetic'}),verifySaved:async()=>true,persist:async()=>{},request:async()=>calls.push('create')});assert.deepEqual(calls,['download']);assert.equal(result.waiting,undefined);});

test('Financial counterparties and an event-type conflict cannot become ordinary purchases',()=>{assert.equal(importPayPalCSV(csv().replace('Fictional Tools','Fictional Bank')).records[0].kind,'Financial review');assert.equal(importPayPalCSV(csv().replace('Fictional Tools','PayPal Credit')).records[0].kind,'Financing');const c=importPayPalCSV(csv()).records[0];const pdf={...c,sourceFormat:undefined,type:'Payment Refund',kind:'Refund'};assert.equal(modelEvidenceFiles([{provider:'paypal',records:[c,pdf]}])[0].conflict,true);});
