import test from 'node:test';import assert from 'node:assert/strict';import {remainingGroups,remainingGroupIdentity} from '../extension/remaining-groups.js';
const t=(id,description,extra={})=>({id,description,date:'2026-10-01',direction:'out',amount:1000,primary:{account:'Fictional checking',type:'Cash and Bank'},categories:['Uncategorized Expense'],kind:'Unclassified',...extra});
test('Venmo entries group across bank wording and case without classifying their purpose',()=>{const rows=[t('001','VENMO PAYMENT 123'),t('002','Purchase Authorized On 10/01 Venmo Jane'),t('003','venmo cashout',{direction:'in',amount:2000})];const [g]=remainingGroups(rows);assert.equal(g.name,'Venmo');assert.equal(g.records.length,3);assert.equal(g.outgoingCents,2000);assert.equal(g.incomingCents,2000);assert.equal(g.records[2].categories[0],'Uncategorized Expense');});
test('Processor names do not match substrings or reference-code metadata',()=>{for(const description of ['Venmostore','Cafe REF VENMO','Hardware CARD VENMO','Cash Application services'])assert.notEqual(remainingGroupIdentity(t('01',description)).type,'service');assert.equal(remainingGroupIdentity(t('02','SQ *Example Cafe')).name,'Square');assert.equal(remainingGroupIdentity(t('03','CASHAPP PAYMENT')).name,'Cash App');});
test('Similar descriptive words normalize case/punctuation and explicit store suffixes only',()=>{const groups=remainingGroups([t('01','Example Shop #123'),t('02','EXAMPLE-SHOP Store 234'),t('03','Example Shop 678'),t('04','Different Shop')]);assert.equal(groups.length,3);assert.equal(groups.find(g=>g.records.length===2).name,'Example Shop');});
test('Approved aliases respect business/account scopes and ambiguous merchant names stay separate',()=>{const rules=[{name:'Fictional tools',aliases:['Example Tools'],category:'Tools',accountNames:['Fictional checking']}];assert.equal(remainingGroupIdentity(t('01','Example Tools branch'),rules).key,'rule:fictional tools');assert.equal(remainingGroupIdentity(t('02','Example Tools branch',{primary:{account:'Other'}}),rules).key,'merchant:example tools branch');assert.equal(remainingGroupIdentity(t('03','Example Tools'),[...rules,{...rules[0],name:'Another merchant'}]).key,'merchant:example tools');});
test('IDs stay strings, duplicate records are counted once and numeric descriptions do not merge',()=>{const rows=[t('0001','123456'),t('0002','123456'),t('0001','123456')],groups=remainingGroups(rows);assert.equal(groups.length,2);assert.deepEqual(groups.map(g=>g.records[0].id),['0001','0002']);});
test('Groups retain accounts, category disagreements and directions separately',()=>{const [g]=remainingGroups([t('01','PayPal vendor',{categories:['Tools']}),t('02','PAYPAL vendor',{categories:['Personal'],primary:{account:'Other'}}),t('03','PayPal refund',{direction:'in',amount:500}),t('04','PayPal unknown',{amount:null})]);assert.equal(g.categories.length,3);assert.equal(g.accounts.length,2);assert.equal(g.outgoingCents,2000);assert.equal(g.incomingCents,500);assert.equal(g.unknownAmounts,1);});
test('Within-group records sort chronologically with stable string IDs',()=>{const [g]=remainingGroups([t('03','VENMO',{date:'2026-10-04'}),t('02','Venmo',{date:'2026-10-02'}),t('01','Venmo',{date:'2026-10-02'})]);assert.deepEqual(g.records.map(r=>r.id),['01','02','03']);});
