import test from 'node:test';import assert from 'node:assert/strict';import {venmoTemplate,venmoPeriods,venmoCollectionPeriods,venmoStatementPage,waitForVenmoControls,venmoRequest,validateVenmoCSV,saveVenmoCSV,collectVenmoProfile} from '../extension/venmo.js';
const source=venmoTemplate('https://account.venmo.com/api/statement/download?startDate=2025-01-01&endDate=2025-01-31&csv=true&profile=fictional-personal'),period=venmoPeriods(2025,'2025-01-31')[0],csv='ID,Datetime,Type,Amount (total)\n0000001,2025-01-02T10:00:00,Payment,-10.00';
function folder(){const files=new Map(),directories=new Map();return {files,async getDirectoryHandle(name,{create=false}={}){if(!directories.has(name)){if(!create)throw Object.assign(Error('Missing'),{name:'NotFoundError'});directories.set(name,folder());}return directories.get(name);},async getFileHandle(name,{create=false}={}){if(!files.has(name)){if(!create)throw Object.assign(Error('Missing'),{name:'NotFoundError'});files.set(name,'');}return {getFile:async()=>({text:async()=>files.get(name)}),createWritable:async()=>({write:async text=>files.set(name,text),close:async()=>{},abort:async()=>{}})};}};}
test('Only observed secure Venmo statement CSV endpoints can become templates',()=>{for(const url of ['https://evil.example/api/statement/download?startDate=2025-01-01&endDate=2025-01-31&csv=true','https://account.venmo.com/api/payment/download?startDate=2025-01-01&endDate=2025-01-31&csv=true','https://account.venmo.com/api/statement/download?startDate=2025-01-01&endDate=2025-01-31&csv=false','https://user:password@account.venmo.com/api/statement/download?startDate=2025-01-01&endDate=2025-01-31&csv=true'])assert.throws(()=>venmoTemplate(url));});
test('All calendar months since 2019 include leap years and stop at today',()=>{const periods=venmoPeriods(2019,'2026-10-05');assert.equal(periods.length,94);assert.equal(periods.find(p=>p.month==='2024-02').end,'2024-02-29');assert.equal(periods.at(-1).end,'2026-10-05');assert.equal(periods.at(-1).partial,true);assert.throws(()=>venmoPeriods(2018,'2026-10-05'));});
test('Date changes preserve captured profile parameters and observed inclusive/exclusive boundaries',()=>{const url=new URL(venmoRequest(source,venmoPeriods(2024,'2024-02-29').at(-1)));assert.equal(url.searchParams.get('profile'),'fictional-personal');assert.equal(url.searchParams.get('endDate'),'2024-02-29');const exclusive=venmoTemplate(source.url.replace('2025-01-31','2025-02-01'));assert.equal(new URL(venmoRequest(exclusive,period)).searchParams.get('endDate'),'2025-02-01');});
test('CSV validation rejects login/JSON replies and wrong-month records but accepts empty statements',()=>{assert.equal(validateVenmoCSV(csv,period).count,1);assert.equal(validateVenmoCSV(csv.split('\n')[0],period).empty,true);for(const text of ['<html>Sign in</html>','{"error":"login"}',csv.replace('2025-01-02','2025-02-02'),'Unrelated,CSV\n1,2'])assert.throws(()=>validateVenmoCSV(text,period));});
test('Personal/business outputs are separate, identical files reused and changed files do not overwrite originals',async()=>{const root=folder(),first=await saveVenmoCSV(root,'personal',period,csv);assert.equal(first.name,'personal/2025/venmo-personal-2025-01.csv');assert.equal((await saveVenmoCSV(root,'personal',period,csv)).reused,true);const changed=await saveVenmoCSV(root,'personal',period,csv.replace('-10.00','-11.00'));assert.notEqual(changed.name,first.name);const business=await saveVenmoCSV(root,'business',period,csv);assert.ok(business.name.startsWith('business/'));assert.equal(await(await(await(await root.getDirectoryHandle('personal')).getDirectoryHandle('2025')).getFileHandle('venmo-personal-2025-01.csv')).getFile().then(f=>f.text()),csv);});
test('Each month is checkpointed only after validation and save; interrupted runs resume without duplicating verified files',async()=>{const periods=venmoPeriods(2025,'2025-02-28'),root=folder();let entries={},reads=0;await assert.rejects(collectVenmoProfile({source,profile:'personal',periods,read:async(url,p)=>{reads++;if(p.month==='2025-02')throw Error('HTTP 429');return csv;},save:(profile,p,text)=>saveVenmoCSV(root,profile,p,text),persist:async value=>entries=value}),/429/);assert.equal(Object.keys(entries).length,1);await collectVenmoProfile({source,profile:'personal',periods,entries,verifySaved:async()=>true,read:async(url,p)=>{reads++;return csv.replaceAll('2025-01','2025-02');},save:(profile,p,text)=>saveVenmoCSV(root,profile,p,text),persist:async value=>entries=value});assert.equal(reads,3);assert.equal(Object.keys(entries).length,2);});
test('Stopping after a response prevents saving it; missing checkpoint files are fetched again',async()=>{let active=true,writes=0;const stopped=await collectVenmoProfile({source,profile:'personal',periods:[period],read:async()=>{active=false;return csv;},save:async()=>{writes++;},persist:async()=>{},current:()=>active});assert.equal(stopped.stopped,true);assert.equal(writes,0);let fetched=0;await collectVenmoProfile({source,profile:'personal',periods:[period],entries:{'personal:2025-01-01:2025-01-31':{hash:'missing',name:'missing.csv'}},read:async()=>{fetched++;return csv;},save:async()=>({hash:'new',name:'new.csv'}),persist:async()=>{}});assert.equal(fetched,1);});

test('Unavailable months are recorded distinctly and never create a fake CSV',async()=>{let saved=0,entries={};await collectVenmoProfile({source,profile:'business',periods:[period],read:async()=>({unavailable:true,httpStatus:404}),save:async()=>saved++,persist:async value=>entries=value});assert.equal(saved,0);assert.equal(Object.values(entries)[0].status,'unavailable');assert.equal(Object.values(entries)[0].hash,undefined);});

test('Injected statement reader checks profile evidence and only clicks the exact CSV control',async()=>{const {venmoPage}=await import('../extension/venmo-page.js');const old={document:globalThis.document,location:globalThis.location,fetch:globalThis.fetch};let clicks=0,fetches=0,buttons=[{innerText:'Download CSV',outerHTML:'<button>Download CSV</button>',getClientRects:()=>[{}],getAttribute:()=>null,click:()=>clicks++},{innerText:'Pay',outerHTML:'<button>Pay</button>',getClientRects:()=>[{}],getAttribute:()=>null,click:()=>assert.fail('Payment control clicked')}];globalThis.location={origin:'https://account.venmo.com',pathname:'/statements',href:'https://account.venmo.com/statements'};globalThis.document={body:{innerText:'Statements'},querySelectorAll:selector=>selector==='nav,[role=navigation],header'?[{innerText:'Fictional Personal Profile'}]:selector==='a[href]'?[{href:source.url}]:buttons};globalThis.fetch=async(url,options)=>{fetches++;assert.equal(options.credentials,'include');assert.equal(options.redirect,'error');return new Response(csv,{status:200});};try{const ctx=await venmoPage({action:'read'});await assert.rejects(venmoPage({action:'download',url:source.url,...ctx,evidence:'Wrong profile'}),/profile/);assert.equal(fetches,0);assert.equal((await venmoPage({action:'download',url:source.url,...ctx})).text,csv);await venmoPage({action:'sample'});assert.equal(clicks,1);buttons.push({...buttons[0]});await assert.rejects(venmoPage({action:'sample'}),/one visible Download CSV/);}finally{for(const [key,value] of Object.entries(old)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}});


test('All profiles chooses the confirmed personal/business transaction controls and never sales tax',async()=>{const {venmoPage}=await import('../extension/venmo-page.js');const old={document:globalThis.document,location:globalThis.location,fetch:globalThis.fetch};const clicked=[];const button=(id,text)=>{const e={innerText:'Download CSV',outerHTML:'<button>Download CSV</button>',getClientRects:()=>[{}],getAttribute:()=>null,click:()=>clicked.push(id)};e.parentElement={innerText:text,contains:c=>c===e,parentElement:null};return e;};let buttons=[button('personal','@fictionalperson transaction fees Download CSV'),button('business','@fictionalshop transaction fees Download CSV'),button('tax','Sales tax collected Download CSV')];globalThis.location={origin:'https://account.venmo.com',pathname:'/statements',href:'https://account.venmo.com/statements'};globalThis.document={body:{innerText:'Statements All profiles'},querySelectorAll:selector=>selector==='nav,[role=navigation],header'?[{innerText:'Statements'}]:selector==='a[href]'?[]:buttons};globalThis.fetch=()=>assert.fail('Changed controls must prevent fetching');try{const ctx=await venmoPage({action:'read'});assert.equal(ctx.downloads.filter(r=>r.tax).length,1);await venmoPage({action:'sample',profile:'personal'});await venmoPage({action:'sample',profile:'business'});assert.deepEqual(clicked,['personal','business']);await assert.rejects(venmoPage({action:'sample'}),/Choose Personal or Business/);buttons[1].parentElement.innerText='@differentprofile transaction fees Download CSV';await assert.rejects(venmoPage({action:'download',url:source.url,...ctx}),/controls changed/);buttons[1].parentElement.innerText='@fictionalperson transaction fees Download CSV';await assert.rejects(venmoPage({action:'sample',profile:'business'}),/Cannot distinguish/);buttons[1].parentElement.innerText='No profile heading Download CSV';await assert.rejects(venmoPage({action:'sample',profile:'business'}),/Cannot distinguish/);assert.deepEqual(clicked,['personal','business']);}finally{for(const [key,value] of Object.entries(old)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}});


test('Collector works back from the latest completed month and handles the January year boundary',()=>{const periods=venmoCollectionPeriods(2019,'2026-10-05');assert.equal(periods.length,94);assert.equal(periods[0].month,'2026-09');assert.equal(periods.at(-2).month,'2019-01');assert.equal(periods.at(-1).month,'2026-10');assert.equal(new Set(periods.map(p=>p.month)).size,94);assert.equal(new URL(venmoStatementPage('2026-01-05')).searchParams.get('year'),'2025');assert.equal(new URL(venmoStatementPage('2026-01-05')).searchParams.get('month'),'12');assert.equal(new URL(venmoStatementPage('2026-10-05')).searchParams.get('month'),'9');});
test('Control readiness waits for loading but stops clearly on a month without transaction downloads',async()=>{let reads=0,pauses=0;const ready=await waitForVenmoControls(async()=>({downloads:++reads===3?[{tax:false}]:[],links:[],pageURL:'https://account.venmo.com/statement?month=10&year=2026'}),{attempts:3,pause:async()=>pauses++});assert.equal(ready.downloads.length,1);assert.equal(pauses,2);await assert.rejects(waitForVenmoControls(async()=>({downloads:[{tax:true}],links:[],pageURL:'https://account.venmo.com/statement?month=10&year=2026'}),{attempts:2,pause:async()=>{}}),/no transaction Download CSV buttons for 2026-10/);});
test('Unavailable newest month does not block the next monthly statement or create a CSV',async()=>{const periods=venmoCollectionPeriods(2025,'2025-02-10'),saved=[],checkpoints=[];await collectVenmoProfile({source,profile:'personal',periods,read:async(url,p)=>p.month==='2025-01'?{unavailable:true,httpStatus:404}:csv.replaceAll('2025-01','2025-02'),save:async(profile,p)=>{saved.push(p.month);return {name:'fictional.csv',hash:'fictional'};},persist:async e=>checkpoints.push({...e})});assert.deepEqual(saved,['2025-02']);assert.equal(checkpoints[0]['personal:2025-01-01:2025-01-31'].status,'unavailable');assert.equal(Object.keys(checkpoints.at(-1)).length,2);});


test('September 2019 boundary excludes the eight earlier months without dropping later years',()=>{const periods=venmoCollectionPeriods(2019,'2026-10-05',9);assert.equal(periods.length,86);assert.equal(periods[0].month,'2026-09');assert.equal(periods.at(-2).month,'2019-09');assert.equal(periods.at(-1).month,'2026-10');assert.ok(periods.every(p=>p.month>='2019-09'));assert.ok(periods.some(p=>p.month==='2020-01'));assert.throws(()=>venmoCollectionPeriods(2019,'2026-10-05',13));assert.throws(()=>venmoCollectionPeriods(2026,'2026-10-05',12));});
